In [9]:
# Imports and pip installations (if needed)
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

# Part 1: Load the dataset

In [2]:
# Load the dataset (load remotely or locally)
df = pd.read_csv("iris.csv")
# Output the first 15 rows of the data
display(df.head(15))
# Display a summary of the table information (number of datapoints, etc.)
display(df.describe())

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

The features are sepal_length, sepal_width, petal_length, and petal_width. The label is the species of flower.

# Part 2: Split the dataset into train and test

In [3]:
# Take the dataset and split it into our features (X) and label (y)
X = df.drop('species', axis=1)
y = df['species']
# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.9, test_size=0.1, random_state=42)
display(X_train)
display(y_train)

     sepal_length  sepal_width  petal_length  petal_width
56            6.3          3.3           4.7          1.6
104           6.5          3.0           5.8          2.2
69            5.6          2.5           3.9          1.1
55            5.7          2.8           4.5          1.3
132           6.4          2.8           5.6          2.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[135 rows x 4 columns]

56     versicolor
104     virginica
69     versicolor
55     versicolor
132     virginica
          ...
71     versicolor
106     virginica
14         setosa
92     versicolor
102     virginica
Name: species, Length: 135, dtype: object

# Part 3: Logistic Regression

In [4]:
# i. Use sklearn to train a LogisticRegression model on the training set
logistic_reg_model = LogisticRegression(max_iter=85, random_state=42).fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
median_features = np.median(X_train, axis=0).reshape(1, -1)
log_reg_y_pred = logistic_reg_model.predict_proba(median_features) 
    # Used the mean of both the sepal and petal length and width
print("Probabilities of each class:", log_reg_y_pred)
# iii. Report on the score for Logistic regression model, what does the score measure?
train_score = logistic_reg_model.score(X_test, y_test)
print("Score:", train_score)
# iv. Extract the coefficents and intercepts for the boundary line(s)
print("Coefficients:", logistic_reg_model.coef_)
print("Intercepts:", logistic_reg_model.intercept_)

Probabilities of each class: [[0.0117824  0.88724149 0.10097611]]
Score: 1.0
Coefficients: [[-0.42829534  0.96813199 -2.44755287 -1.03777439]
 [ 0.51309019 -0.22065385 -0.21608608 -0.84447694]
 [-0.08479485 -0.74747813  2.66363895  1.88225133]]
Intercepts: [  9.54146052   1.89955179 -11.4410123 ]

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

The score measures the accuracy of the logistic regression model using the test data

# Part 4: Support Vector Machine

In [5]:
# i. Use sklearn to train a Support Vector Classifier on the training set
svc = SVC(probability=True).fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
median_features = np.median(X_train, axis=0).reshape(1, -1)
svc_y_pred = svc.predict_proba(median_features)
print(svc_y_pred)
    # Used the mean of both the sepal and petal length and width
# iii. Report on the score for the SVM, what does the score measure?
svc_test_score = svc.score(X_test, y_test)
print(svc_test_score)

[[0.00839603 0.96597731 0.02562666]]
1.0

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

The score measures the accuracy of the support vector classifier using the test data

# Part 5: Neural Network

In [6]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
median_features = np.median(X_train, axis=0).reshape(1, -1)
clf_y_pred = clf.predict_proba(median_features)
print(clf_y_pred)
# iii. Report on the score for the Neural Network, what does the score measure?
clf_test_score = clf.score(X_test, y_test)
print(clf_test_score)
# iv: Experiment with different options for the neural network, report on your best configuration

[[0.02269791 0.74961358 0.22768851]]
1.0

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

The score measures the accuracy of the neural network using the test data

# Part 6: K-Nearest Neighbors

In [15]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
knn = KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
median_features = np.median(X_train, axis=0).reshape(1, -1)
knn_y_pred = knn.predict_proba(median_features)
print(knn_y_pred)
# iii. Report on the score for kNN, what does the score measure?
knn_test_score = knn.score(X_test, y_test)
print(knn_test_score)

[[0. 1. 0.]]
1.0

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

The score measures the accuracy of the k-nearest neighbors classifier using the test data

# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

I'm not sure how to evaluate which model performed the best on the dataset. I feel like I did something wrong with all my scores being 1.0, but I'm not sure what went wrong.