How many late days are you using for this assignment? 0 late days

In [1]:
# Imports and pip installations (if needed)
import pandas as pd
import numpy as np
from scipy import stats
#from sklearn.preprocessing import MinMaxScaler

In [2]:
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

# Part 1: Load the dataset

In [3]:
# Load the given datasets
cat_df = pd.read_csv("chronic_kidney_disease_categorical.csv")
num_df = pd.read_csv("chronic_kidney_disease_numerical.csv")

# Print the data
display(cat_df)

,unique_id,al,su,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,Target
0,224481,3.0,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,yes,no,ckd
1,992643,0.0,0.0,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,notckd
2,308740,1.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,no,no,good,yes,no,ckd
3,450314,1.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,yes,ckd
4,881763,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
5,114717,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
6,950823,4.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
7,901528,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
8,433613,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
9,621332,1.0,0.0,abnormal,normal,notpresent,notpresent,no,yes,no,poor,no,no,ckd
10,708255,2.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
11,365669,1.0,0.0,normal,abnormal,notpresent,notpresent,no,no,no,poor,yes,yes,ckd
12,460465,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
13,517373,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
14,910351,NaN,NaN,NaN,NaN,notpresent,notpresent,no,no,no,poor,yes,yes,ckd
15,129654,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
16,608641,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
17,261025,2.0,1.0,NaN,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
18,532520,2.0,0.0,abnormal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
19,168242,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
20,384209,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
21,536401,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,no,yes,poor,no,no,ckd
22,902019,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,no,no,good,yes,yes,ckd
23,720366,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
24,851448,2.0,2.0,normal,NaN,notpresent,notpresent,yes,yes,no,good,no,no,ckd
25,994377,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
26,951380,0.0,0.0,NaN,abnormal,notpresent,notpresent,no,no,no,good,no,yes,ckd
27,325962,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
28,734698,3.0,0.0,normal,abnormal,notpresent,notpresent,no,yes,no,good,yes,no,ckd
29,834066,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
30,461152,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
31,462735,0.0,0.0,NaN,NaN,notpresent,notpresent,no,yes,no,poor,yes,no,ckd
32,643841,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
33,310480,3.0,0.0,abnormal,abnormal,present,notpresent,yes,yes,no,poor,yes,no,ckd
34,441170,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
35,737689,3.0,0.0,abnormal,NaN,notpresent,notpresent,yes,yes,no,good,no,no,ckd
36,208034,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,yes,good,yes,no,ckd
37,540586,2.0,0.0,normal,normal,notpresent,present,no,no,no,poor,no,no,ckd
38,754973,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
39,240975,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
40,516547,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,no,ckd
41,937729,0.0,0.0,NaN,normal,notpresent,notpresent,no,yes,no,good,no,no,ckd
42,947246,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
43,522912,1.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
44,161848,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
45,679864,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
46,311824,0.0,0.0,NaN,normal,notpresent,notpresent,no,yes,no,good,no,no,ckd
47,750202,NaN,NaN,normal,NaN,notpresent,notpresent,yes,no,no,good,yes,yes,ckd
48,504652,2.0,2.0,normal,NaN,notpresent,notpresent,yes,no,yes,good,no,no,ckd
49,210452,2.0,0.0,NaN,abnormal,present,notpresent,no,no,no,good,no,no,ckd
50,105923,1.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
51,354223,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
52,719711,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
53,608902,4.0,1.0,normal,abnormal,present,notpresent,yes,yes,no,poor,yes,yes,ckd
54,484175,2.0,0.0,abnormal,abnormal,present,notpresent,yes,yes,no,poor,no,yes,ckd
55,647552,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
56,577147,3.0,0.0,NaN,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
57,976875,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
58,266335,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
59,719916,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
60,449458,3.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
61,746487,4.0,2.0,normal,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
62,271687,2.0,0.0,NaN,normal,notpresent,present,no,no,no,poor,no,no,ckd
63,419342,3.0,2.0,NaN,abnormal,notpresent,notpresent,yes,yes,yes,poor,yes,no,ckd
64,311664,2.0,0.0,abnormal,abnormal,present,notpresent,no,no,no,poor,yes,yes,ckd
65,991031,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
66,353930,1.0,0.0,abnormal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
67,781942,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
68,418316,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
69,162229,0.0,2.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
70,436833,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
71,283427,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
72,926033,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
73,486397,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
74,302906,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
75,325238,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,poor,no,yes,ckd\t
76,590905,3.0,2.0,NaN,abnormal,present,notpresent,yes,yes,no,good,no,yes,ckd
77,750155,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
78,488012,1.0,0.0,abnormal,abnormal,notpresent,notpresent,no,no,no,good,yes,no,ckd
79,707555,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
80,949813,2.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
81,549224,1.0,0.0,normal,abnormal,present,notpresent,yes,yes,no,poor,no,no,ckd
82,515110,NaN,NaN,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,notckd
83,330559,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
84,782554,0.0,3.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
85,393837,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
86,207140,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
87,353025,3.0,4.0,normal,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
88,856244,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,no,no,ckd
89,352995,NaN,NaN,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
90,566581,1.0,4.0,abnormal,abnormal,present,notpresent,no,yes,no,good,no,no,ckd
91,696591,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
92,617948,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
93,968971,0.0,0.0,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,notckd
94,501321,1.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
95,146553,2.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
96,943166,2.0,4.0,NaN,abnormal,present,notpresent,yes,yes,no,good,no,yes,ckd
97,466320,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,poor,no,yes,ckd
98,816565,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,yes,good,yes,no,ckd
99,602549,3.0,0.0,normal,abnormal,present,notpresent,yes,yes,no,good,no,yes,ckd
100,146661,1.0,0.0,NaN,abnormal,notpresent,notpresent,no,no,no,good,no,no,ckd
101,943161,2.0,0.0,normal,abnormal,present,notpresent,yes,yes,no,poor,no,no,ckd\t
102,328705,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
103,227450,4.0,4.0,NaN,normal,present,notpresent,yes,yes,no,good,no,no,ckd
104,943378,NaN,NaN,normal,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
105,124446,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
106,727550,2.0,2.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
107,809452,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
108,213257,3.0,0.0,abnormal,normal,notpresent,notpresent,no,no,no,good,yes,no,ckd
109,271932,NaN,NaN,NaN,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
110,602404,2.0,1.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
111,640519,NaN,NaN,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,ckd
112,614376,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
113,840392,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,no,no,poor,no,no,ckd
114,322882,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
115,235579,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
116,559168,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
117,454830,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,yes,good,yes,yes,ckd
118,888096,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
119,617089,1.0,3.0,normal,abnormal,notpresent,notpresent,no,no,no,good,yes,no,ckd
120,343784,1.0,0.0,NaN,normal,notpresent,notpresent,no,yes,no,good,no,no,ckd
121,534245,2.0,0.0,normal,abnormal,present,notpresent,no,no,no,good,no,no,ckd
122,373780,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
123,741117,0.0,0.0,normal,normal,notpresent,notpresent,NaN,NaN,NaN,good,no,no,notckd
124,261137,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
125,240430,0.0,0.0,normal,normal,NaN,NaN,no,no,no,good,no,no,notckd
126,475200,4.0,2.0,abnormal,abnormal,notpresent,present,yes,yes,no,good,yes,no,ckd
127,530138,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
128,995177,4.0,3.0,normal,abnormal,present,present,yes,yes,yes,good,yes,yes,ckd
129,643007,NaN,NaN,NaN,normal,notpresent,notpresent,yes,yes,yes,poor,no,no,ckd
130,819747,1.0,3.0,NaN,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
131,489160,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
132,566924,3.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
133,315377,0.0,0.0,abnormal,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
134,385412,NaN,NaN,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
135,523454,1.0,0.0,NaN,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
136,790358,0.0,0.0,NaN,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
137,764115,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
138,862719,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
139,155872,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
140,434594,2.0,NaN,NaN,NaN,notpresent,notpresent,no,yes,no,poor,yes,no,ckd
141,674446,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
142,553221,1.0,0.0,normal,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
143,750226,3.0,0.0,abnormal,normal,present,present,no,no,no,good,no,no,ckd
144,103570,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
145,431871,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
146,360756,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
147,551175,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
148,401423,NaN,NaN,NaN,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
149,395450,1.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
150,585932,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
151,878575,3.0,3.0,NaN,abnormal,present,notpresent,yes,yes,no,good,yes,no,ckd
152,794293,3.0,0.0,NaN,normal,present,notpresent,yes,yes,no,poor,yes,no,ckd
153,292312,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
154,203466,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
155,760698,4.0,0.0,abnormal,abnormal,notpresent,notpresent,no,no,no,good,yes,no,ckd
156,625487,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
157,495500,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
158,337834,4.0,0.0,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd
159,861723,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
160,572140,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
161,223886,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,no,no,good,yes,no,ckd
162,482105,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
163,109053,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
164,234299,4.0,0.0,normal,abnormal,notpresent,notpresent,yes,no,no,good,no,yes,ckd
165,104675,2.0,1.0,normal,normal,present,notpresent,no,yes,no,good,no,no,ckd
166,250046,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
167,411659,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
168,124304,3.0,4.0,normal,abnormal,notpresent,notpresent,yes,yes,yes,good,yes,no,ckd
169,412799,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
170,155117,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
171,271057,3.0,1.0,NaN,normal,present,notpresent,yes,yes,yes,poor,yes,no,ckd
172,766869,4.0,3.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
173,593735,0.0,0.0,NaN,normal,notpresent,notpresent,no,yes,no,good,no,no,ckd
174,572320,0.0,0.0,normal,normal,notpresent,notpresent,NaN,NaN,NaN,good,no,no,notckd
175,683771,NaN,NaN,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,notckd
176,557347,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
177,335961,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
178,508465,1.0,0.0,abnormal,normal,notpresent,notpresent,no,no,no,good,no,yes,ckd
179,997629,0.0,0.0,normal,normal,NaN,NaN,no,no,no,good,no,no,notckd
180,917844,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
181,862446,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
182,577753,3.0,4.0,normal,abnormal,present,notpresent,yes,yes,yes,poor,yes,no,ckd
183,544587,0.0,4.0,NaN,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
184,769512,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
185,837169,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
186,137392,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,no,no,poor,no,no,ckd
187,553648,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
188,963946,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
189,942148,2.0,0.0,normal,abnormal,present,notpresent,yes,yes,no,poor,no,yes,ckd
190,631648,0.0,0.0,NaN,normal,notpresent,notpresent,yes,no,no,poor,no,yes,ckd
191,313476,3.0,0.0,normal,abnormal,notpresent,notpresent,no,no,no,good,yes,no,ckd
192,585863,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
193,203694,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
194,246165,3.0,0.0,abnormal,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
195,349892,1.0,3.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,good,no,no,ckd
196,471614,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
197,712694,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
198,838360,2.0,0.0,NaN,abnormal,present,present,no,no,no,good,no,no,ckd
199,389919,0.0,2.0,NaN,normal,notpresent,notpresent,no,yes,no,poor,no,yes,ckd
200,353938,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,no,no,good,no,no,ckd
201,837729,0.0,0.0,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,notckd
202,828592,3.0,0.0,normal,abnormal,present,present,yes,yes,yes,good,no,no,ckd
203,693440,1.0,0.0,normal,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
204,750284,4.0,3.0,normal,abnormal,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
205,319394,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
206,971494,2.0,0.0,NaN,normal,present,notpresent,no,no,no,good,no,no,ckd
207,316414,1.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
208,670655,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
209,118596,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
210,201677,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
211,283469,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,no,no,poor,no,no,ckd
212,955478,0.0,0.0,abnormal,normal,notpresent,notpresent,no,no,no,poor,no,no,ckd
213,499221,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
214,202793,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,no,ckd
215,997876,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
216,726486,0.0,4.0,NaN,normal,notpresent,notpresent,no,yes,no,good,no,no,ckd
217,301291,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
218,731540,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
219,481293,3.0,1.0,normal,abnormal,present,notpresent,yes,no,no,poor,no,yes,ckd
220,585429,1.0,0.0,normal,NaN,present,present,no,yes,no,poor,no,no,ckd
221,654306,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
222,183890,3.0,0.0,NaN,abnormal,present,notpresent,no,no,no,poor,no,no,ckd
223,977137,3.0,2.0,normal,normal,present,notpresent,yes,yes,yes,good,no,no,ckd
224,850360,1.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
225,857435,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
226,175008,0.0,0.0,NaN,normal,notpresent,notpresent,yes,no,yes,good,yes,no,ckd
227,340466,5.0,0.0,abnormal,abnormal,notpresent,present,yes,yes,yes,poor,yes,yes,ckd
228,107297,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
229,438182,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,good,no,no,ckd
230,353996,1.0,0.0,normal,NaN,notpresent,notpresent,yes,yes,no,good,no,no,ckd
231,856244,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,no,no,ckd
232,948185,2.0,0.0,normal,abnormal,present,notpresent,yes,yes,no,good,no,no,ckd
233,583717,NaN,NaN,NaN,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
234,636769,2.0,0.0,normal,abnormal,present,present,no,no,no,poor,yes,yes,ckd
235,546010,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
236,673081,1.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
237,619200,0.0,0.0,NaN,abnormal,notpresent,notpresent,no,yes,no,good,no,no,ckd
238,365358,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,NaN,NaN,NaN,notckd
239,746768,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
240,928378,2.0,0.0,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd
241,667326,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
242,369844,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
243,459229,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
244,119638,2.0,4.0,normal,abnormal,notpresent,notpresent,no,yes,no,good,yes,no,ckd
245,899916,3.0,0.0,normal,normal,notpresent,notpresent,yes,no,no,poor,no,yes,ckd
246,840399,3.0,0.0,NaN,NaN,notpresent,notpresent,yes,yes,no,good,yes,no,ckd
247,421471,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
248,504617,1.0,4.0,normal,NaN,notpresent,notpresent,yes,yes,no,good,no,no,ckd
249,648958,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,no,no,ckd
250,858794,0.0,0.0,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,notckd

In [4]:
display(num_df)

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc
0,203694,38.0,80.0,99.0,19.0,0.50,147.0,3.5,13.6,44.0,7300.0,6.4
1,938027,43.0,60.0,108.0,25.0,1.00,144.0,5.0,17.8,43.0,7200.0,5.5
2,421471,37.0,60.0,111.0,35.0,0.80,135.0,4.1,16.2,50.0,5500.0,5.7
3,764115,70.0,90.0,144.0,125.0,4.00,136.0,4.6,12.0,37.0,8200.0,4.5
4,240975,47.0,80.0,95.0,35.0,0.90,140.0,4.1,NaN,NaN,NaN,NaN
5,992643,35.0,70.0,82.0,36.0,1.10,150.0,3.5,14.5,52.0,9400.0,6.1
6,573400,60.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,109053,64.0,60.0,106.0,27.0,0.70,150.0,3.3,14.4,42.0,8100.0,4.7
8,352995,33.0,60.0,130.0,41.0,0.90,141.0,4.4,15.5,52.0,4300.0,5.8
9,395450,65.0,70.0,203.0,46.0,1.40,NaN,NaN,11.4,36.0,5000.0,4.1
10,261025,62.0,90.0,169.0,48.0,2.40,138.0,2.9,13.4,47.0,11000.0,6.1
11,389919,61.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9800.0,NaN
12,210452,72.0,90.0,124.0,53.0,2.30,NaN,NaN,11.9,39.0,NaN,NaN
13,349892,59.0,70.0,424.0,55.0,1.70,138.0,4.5,12.6,37.0,10200.0,4.1
14,943161,65.0,60.0,192.0,17.0,1.70,130.0,4.3,NaN,NaN,9500.0,NaN
15,224481,54.0,60.0,125.0,21.0,1.30,137.0,3.4,15.0,46.0,NaN,NaN
16,335961,67.0,80.0,99.0,40.0,0.50,NaN,NaN,17.8,44.0,5900.0,5.2
17,630177,58.0,80.0,131.0,18.0,1.10,141.0,3.5,15.8,53.0,6800.0,6.1
18,741276,23.0,60.0,95.0,24.0,0.80,145.0,5.0,15.0,52.0,6300.0,4.6
19,546010,49.0,80.0,122.0,32.0,1.20,139.0,3.9,17.0,41.0,5600.0,4.9
20,460465,47.0,60.0,109.0,25.0,1.10,141.0,4.7,15.8,41.0,8300.0,5.2
21,619200,68.0,80.0,171.0,30.0,1.00,NaN,NaN,13.7,43.0,4900.0,5.2
22,965166,48.0,80.0,75.0,22.0,0.80,137.0,5.0,16.8,51.0,6000.0,6.5
23,201677,33.0,80.0,89.0,19.0,1.10,144.0,5.0,15.0,40.0,10300.0,4.8
24,976875,33.0,60.0,80.0,25.0,0.90,146.0,3.5,14.1,48.0,7800.0,5.1
25,340466,57.0,90.0,NaN,322.0,13.00,126.0,4.8,8.0,24.0,4200.0,3.3
26,515110,47.0,80.0,93.0,33.0,0.90,144.0,4.5,13.3,52.0,8100.0,5.2
27,673081,44.0,90.0,NaN,20.0,1.10,NaN,NaN,15.0,48.0,NaN,NaN
28,508469,15.0,60.0,86.0,15.0,0.60,138.0,4.0,11.0,33.0,7700.0,3.8
29,917844,61.0,60.0,108.0,75.0,1.90,141.0,5.2,9.9,29.0,8400.0,3.7
30,726486,26.0,70.0,250.0,20.0,1.10,NaN,NaN,15.6,52.0,6900.0,6.0
31,819747,75.0,70.0,123.0,31.0,1.40,NaN,NaN,NaN,NaN,NaN,NaN
32,856086,60.0,90.0,NaN,180.0,76.00,4.5,NaN,10.9,32.0,6200.0,3.6
33,719711,43.0,80.0,114.0,32.0,1.10,135.0,3.9,NaN,42.0,NaN,NaN
34,104675,65.0,80.0,215.0,133.0,2.50,NaN,NaN,13.2,41.0,NaN,NaN
35,431871,57.0,60.0,132.0,18.0,1.10,150.0,4.7,15.4,42.0,11000.0,4.5
36,857435,60.0,70.0,140.0,27.0,1.20,NaN,NaN,NaN,NaN,NaN,NaN
37,534003,42.0,80.0,132.0,24.0,0.70,140.0,4.1,14.4,50.0,5000.0,4.5
38,300354,61.0,70.0,100.0,28.0,2.10,NaN,NaN,12.6,43.0,NaN,NaN
39,717463,67.0,70.0,NaN,106.0,6.00,137.0,4.9,6.1,19.0,6500.0,NaN
40,737689,62.0,NaN,NaN,NaN,NaN,NaN,NaN,14.3,42.0,10200.0,4.8
41,947246,73.0,60.0,127.0,48.0,0.50,150.0,3.5,15.1,52.0,11000.0,4.7
42,441170,79.0,80.0,111.0,44.0,1.20,146.0,3.6,16.3,40.0,8000.0,6.4
43,359624,43.0,80.0,NaN,30.0,1.10,NaN,NaN,14.0,42.0,14900.0,NaN
44,675800,60.0,80.0,172.0,32.0,2.70,NaN,NaN,11.2,36.0,NaN,NaN
45,917565,45.0,90.0,360.0,45.0,2.40,128.0,4.4,8.3,29.0,5500.0,3.7
46,557347,34.0,80.0,121.0,27.0,1.20,144.0,3.9,13.6,52.0,9200.0,6.3
47,643841,23.0,80.0,99.0,46.0,1.20,142.0,4.0,17.7,46.0,4300.0,5.5
48,504652,63.0,80.0,NaN,NaN,3.40,136.0,4.2,13.0,40.0,9800.0,4.2
49,943378,47.0,100.0,122.0,NaN,16.90,138.0,5.2,10.8,33.0,10200.0,3.8
50,480497,67.0,70.0,102.0,48.0,3.20,137.0,5.0,11.9,34.0,7100.0,3.7
51,583717,54.0,70.0,233.0,50.1,1.90,NaN,NaN,11.7,NaN,NaN,NaN
52,608902,56.0,90.0,176.0,309.0,13.30,124.0,6.5,3.1,9.0,5400.0,2.1
53,261137,35.0,60.0,105.0,39.0,0.50,135.0,3.9,14.7,43.0,5800.0,6.2
54,721270,58.0,70.0,102.0,48.0,1.20,139.0,4.3,15.0,40.0,8100.0,4.9
55,385412,46.0,90.0,213.0,68.0,2.80,146.0,6.3,9.3,NaN,NaN,NaN
56,980291,62.0,70.0,122.0,42.0,1.70,136.0,4.7,12.6,39.0,7900.0,3.9
57,488012,50.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,271687,66.0,90.0,153.0,76.0,3.30,NaN,NaN,NaN,NaN,NaN,NaN
59,566581,73.0,90.0,234.0,56.0,1.90,NaN,NaN,10.3,28.0,NaN,NaN
60,311664,42.0,90.0,93.0,153.0,2.70,139.0,4.3,9.8,34.0,9800.0,NaN
61,872034,70.0,90.0,184.0,98.6,3.30,138.0,3.9,5.8,NaN,NaN,NaN
62,373780,24.0,80.0,93.0,46.0,1.00,145.0,3.5,NaN,NaN,10700.0,6.3
63,902019,NaN,100.0,129.0,107.0,6.70,132.0,4.4,4.8,14.0,6300.0,NaN
64,418316,62.0,80.0,78.0,45.0,0.60,138.0,3.5,16.1,50.0,5400.0,5.7
65,750284,52.0,90.0,224.0,166.0,5.60,133.0,47.0,8.1,23.0,5000.0,2.9
66,524004,30.0,80.0,82.0,42.0,0.70,146.0,5.0,14.9,45.0,9400.0,5.9
67,268609,56.0,80.0,139.0,15.0,1.20,135.0,5.0,14.8,42.0,5600.0,5.5
68,308740,65.0,70.0,139.0,29.0,1.00,NaN,NaN,10.5,32.0,NaN,NaN
69,549224,70.0,100.0,169.0,47.0,2.90,NaN,NaN,11.1,32.0,5800.0,5.0
70,461152,50.0,NaN,92.0,19.0,1.20,150.0,4.8,14.9,48.0,4700.0,5.4
71,328705,39.0,70.0,131.0,46.0,0.60,145.0,5.0,15.6,41.0,9400.0,4.7
72,365358,75.0,60.0,110.0,50.0,0.70,135.0,5.0,14.3,40.0,8300.0,5.8
73,948185,45.0,60.0,268.0,86.0,4.00,134.0,5.1,10.0,29.0,9200.0,NaN
74,971494,65.0,70.0,112.0,73.0,3.30,NaN,NaN,10.9,37.0,NaN,NaN
75,559987,78.0,60.0,114.0,74.0,2.90,135.0,5.9,8.0,24.0,NaN,NaN
76,852091,45.0,70.0,NaN,20.0,0.70,NaN,NaN,NaN,NaN,NaN,NaN
77,770544,55.0,70.0,107.0,26.0,1.10,NaN,NaN,17.0,50.0,6700.0,6.1
78,501321,4.0,NaN,99.0,23.0,0.60,138.0,4.4,12.0,34.0,NaN,NaN
79,283427,55.0,80.0,140.0,49.0,0.50,150.0,4.9,15.7,47.0,6700.0,4.9
80,490253,43.0,80.0,81.0,46.0,0.60,135.0,4.9,13.9,48.0,6900.0,4.9
81,302906,59.0,100.0,NaN,96.0,6.40,NaN,NaN,6.6,NaN,NaN,NaN
82,991031,30.0,80.0,89.0,42.0,0.50,139.0,5.0,16.7,52.0,10200.0,5.0
83,271932,72.0,90.0,84.0,145.0,7.10,135.0,5.3,NaN,NaN,NaN,NaN
84,319394,33.0,90.0,92.0,19.0,0.80,NaN,NaN,11.8,34.0,7000.0,NaN
85,379507,17.0,60.0,114.0,50.0,1.00,135.0,4.9,14.2,51.0,7200.0,5.9
86,676393,63.0,70.0,113.0,25.0,0.60,146.0,4.9,16.5,52.0,8000.0,5.1
87,175008,65.0,80.0,92.0,37.0,1.50,140.0,5.2,8.8,25.0,10700.0,3.2
88,311824,48.0,70.0,124.0,24.0,1.20,142.0,4.2,12.4,37.0,6400.0,4.7
89,114717,41.0,80.0,122.0,25.0,0.80,138.0,5.0,17.1,41.0,9100.0,5.2
90,760698,34.0,70.0,153.0,22.0,0.90,133.0,3.8,NaN,NaN,NaN,NaN
91,950823,7.0,50.0,NaN,18.0,0.80,NaN,NaN,11.3,38.0,6000.0,NaN
92,462735,14.0,NaN,192.0,15.0,0.80,137.0,4.2,14.3,40.0,9500.0,5.4
93,534245,45.0,70.0,117.0,52.0,2.20,136.0,3.8,10.0,30.0,19100.0,3.7
94,137148,73.0,100.0,295.0,90.0,5.60,140.0,2.9,9.2,30.0,7000.0,3.2
95,766869,56.0,90.0,242.0,132.0,16.40,140.0,4.2,8.4,26.0,NaN,3.0
96,750155,46.0,60.0,123.0,46.0,1.00,135.0,5.0,15.7,50.0,6300.0,4.8
97,536401,48.0,100.0,103.0,79.0,5.30,135.0,6.3,6.3,19.0,7200.0,2.6
98,708255,3.0,NaN,NaN,22.0,0.70,NaN,NaN,10.7,34.0,12300.0,NaN
99,734262,35.0,80.0,79.0,202.0,10.80,134.0,3.4,7.9,24.0,7900.0,3.1
100,559168,44.0,70.0,NaN,NaN,NaN,NaN,NaN,13.8,48.0,7800.0,4.4
101,393837,76.0,90.0,172.0,46.0,1.70,141.0,5.5,9.6,30.0,NaN,NaN
102,124446,65.0,80.0,115.0,32.0,11.50,139.0,4.0,14.1,42.0,6800.0,5.2
103,203466,22.0,60.0,97.0,18.0,1.20,138.0,4.3,13.5,42.0,7900.0,6.4
104,593735,39.0,70.0,121.0,20.0,0.80,133.0,3.5,10.9,32.0,NaN,NaN
105,213257,35.0,80.0,NaN,NaN,NaN,NaN,NaN,9.5,28.0,NaN,NaN
106,484175,53.0,90.0,70.0,107.0,7.20,114.0,3.7,9.5,29.0,12100.0,3.7
107,872034,70.0,90.0,184.0,98.6,3.30,138.0,3.9,5.8,NaN,NaN,NaN
108,895508,62.0,80.0,309.0,113.0,2.90,130.0,2.5,10.6,34.0,12800.0,4.9
109,277576,80.0,70.0,NaN,49.0,1.20,NaN,NaN,NaN,NaN,NaN,NaN
110,205058,75.0,70.0,158.0,49.0,1.40,135.0,4.7,11.1,NaN,NaN,NaN
111,228849,58.0,80.0,100.0,50.0,1.20,140.0,3.5,14.0,50.0,6700.0,6.5
112,840399,60.0,90.0,74.0,25.0,1.10,142.0,3.2,12.2,39.0,7800.0,4.4
113,431172,55.0,70.0,99.0,25.0,1.20,NaN,NaN,11.4,NaN,NaN,NaN
114,754973,39.0,60.0,86.0,37.0,0.60,150.0,5.0,13.6,51.0,5800.0,4.5
115,422844,NaN,70.0,110.0,115.0,6.00,134.0,2.7,9.1,26.0,9200.0,3.4
116,517373,36.0,80.0,103.0,NaN,NaN,NaN,NaN,11.9,36.0,8800.0,NaN
117,103570,24.0,80.0,125.0,NaN,NaN,136.0,3.5,15.4,43.0,5600.0,4.5
118,353930,17.0,70.0,22.0,1.5,7.30,145.0,2.8,13.1,41.0,11200.0,NaN
119,673458,5.0,50.0,NaN,25.0,0.60,NaN,NaN,11.8,36.0,12400.0,NaN
120,259239,62.0,80.0,423.0,53.0,1.80,NaN,NaN,9.6,31.0,7500.0,NaN
121,343784,63.0,100.0,78.0,61.0,1.80,141.0,4.4,12.2,36.0,10500.0,4.3
122,840392,47.0,80.0,114.0,87.0,5.20,139.0,3.7,12.1,NaN,NaN,NaN
123,235579,46.0,60.0,102.0,27.0,0.70,142.0,4.9,13.2,44.0,11000.0,5.4
124,997629,35.0,NaN,99.0,30.0,0.50,135.0,4.9,15.4,48.0,5000.0,5.2
125,614376,57.0,80.0,119.0,17.0,1.20,135.0,4.7,15.4,42.0,6200.0,6.2
126,450314,5.0,NaN,NaN,16.0,0.70,138.0,3.2,8.1,NaN,NaN,NaN
127,466489,8.0,60.0,78.0,27.0,0.90,NaN,NaN,12.3,41.0,6700.0,NaN
128,643007,76.0,90.0,93.0,155.0,7.30,132.0,4.9,NaN,NaN,NaN,NaN
129,125587,37.0,60.0,109.0,47.0,1.10,141.0,4.9,15.0,48.0,7000.0,5.2
130,679864,53.0,60.0,91.0,114.0,3.25,142.0,4.3,8.6,28.0,11000.0,3.8
131,516741,12.0,60.0,NaN,51.0,1.80,NaN,NaN,12.1,NaN,10300.0,NaN
132,647552,61.0,70.0,120.0,29.0,0.70,137.0,3.5,17.4,52.0,7000.0,5.3
133,353938,60.0,70.0,124.0,52.0,2.50,NaN,NaN,NaN,NaN,NaN,NaN
134,523454,60.0,70.0,109.0,96.0,3.90,135.0,4.0,13.8,41.0,NaN,NaN
135,602404,55.0,90.0,273.0,235.0,14.20,132.0,3.4,8.3,22.0,14600.0,2.9
136,315377,37.0,100.0,NaN,19.0,1.30,NaN,NaN,15.0,44.0,4100.0,5.2
137,514721,56.0,90.0,129.0,107.0,6.70,131.0,4.8,9.1,29.0,6400.0,3.4
138,878575,64.0,90.0,NaN,35.0,1.30,NaN,NaN,10.3,NaN,NaN,NaN
139,723356,41.0,70.0,NaN,68.0,2.80,132.0,4.1,11.1,33.0,NaN,NaN
140,412799,25.0,60.0,119.0,27.0,0.50,NaN,NaN,15.2,40.0,9200.0,5.2
141,436833,57.0,80.0,120.0,48.0,1.60,NaN,NaN,11.3,36.0,7200.0,3.8
142,596932,45.0,80.0,425.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,499228,32.0,70.0,100.0,29.0,1.10,142.0,4.5,14.3,43.0,6700.0,5.9
144,459229,57.0,80.0,133.0,48.0,1.20,147.0,4.3,14.8,46.0,6600.0,5.5
145,506348,81.0,60.0,148.0,39.0,2.10,147.0,4.2,10.9,35.0,9400.0,2.4
146,781942,47.0,60.0,137.0,17.0,0.50,150.0,3.5,13.6,44.0,7900.0,4.5
147,617948,34.0,70.0,87.0,38.0,0.50,144.0,4.8,17.1,47.0,7400.0,6.1
148,750202,50.0,NaN,219.0,176.0,13.80,136.0,4.5,8.6,24.0,13200.0,2.7
149,721270,58.0,70.0,102.0,48.0,1.20,139.0,4.3,15.0,40.0,8100.0,4.9
150,687021,52.0,80.0,99.0,25.0,0.80,135.0,3.7,15.0,52.0,6300.0,5.3
151,968971,51.0,60.0,129.0,25.0,1.20,139.0,5.0,17.2,40.0,8100.0,5.9
152,428486,73.0,70.0,70.0,32.0,0.90,125.0,4.0,10.0,29.0,18900.0,3.5
153,734698,59.0,50.0,241.0,191.0,12.00,114.0,2.9,9.6,31.0,15700.0,3.8
154,481293,60.0,60.0,288.0,36.0,1.70,130.0,3.0,7.9,25.0,15200.0,3.0
155,213698,65.0,80.0,294.0,71.0,4.40,128.0,5.4,10.0,32.0,9000.0,3.9
156,843449,30.0,80.0,131.0,38.0,1.00,147.0,3.8,14.1,45.0,9400.0,5.3
157,415241,30.0,60.0,138.0,15.0,1.10,135.0,4.4,NaN,NaN,NaN,NaN
158,746082,46.0,90.0,99.0,80.0,2.10,NaN,NaN,11.1,32.0,9100.0,4.1
159,996412,70.0,60.0,120.0,40.0,0.50,140.0,4.6,16.0,43.0,4500.0,4.9
160,316414,32.0,90.0,NaN,223.0,18.10,113.0,6.5,5.5,15.0,2600.0,2.8
161,129654,52.0,80.0,125.0,22.0,1.20,139.0,4.6,16.5,43.0,4700.0,4.6
162,495500,19.0,80.0,107.0,23.0,0.70,141.0,4.2,14.4,44.0,NaN,NaN
163,434594,70.0,70.0,NaN,46.0,1.50,NaN,NaN,9.9,NaN,NaN,NaN
164,411659,32.0,60.0,102.0,17.0,0.40,147.0,4.7,14.6,41.0,6800.0,5.1
165,923121,30.0,70.0,101.0,106.0,6.50,135.0,4.3,NaN,NaN,NaN,NaN
166,640519,54.0,70.0,111.0,146.0,7.50,141.0,4.7,11.0,35.0,8600.0,4.6
167,707555,44.0,60.0,96.0,33.0,0.90,147.0,4.5,16.9,41.0,7200.0,5.0
168,837169,46.0,110.0,130.0,16.0,0.90,NaN,NaN,NaN,NaN,NaN,NaN
169,283469,69.0,60.0,171.0,26.0,48.10,NaN,NaN,NaN,NaN,NaN,NaN
170,741117,56.0,70.0,70.0,46.0,1.20,135.0,4.9,15.9,50.0,11000.0,5.1
171,240975,47.0,80.0,95.0,35.0,0.90,140.0,4.1,NaN,NaN,NaN,NaN
172,746487,59.0,100.0,252.0,40.0,3.20,137.0,4.7,11.2,30.0,26400.0,3.9
173,441170,79.0,80.0,111.0,44.0,1.20,146.0,3.6,16.3,40.0,8000.0,6.4
174,901528,73.0,80.0,118.0,44.0,0.70,137.0,3.5,14.8,45.0,9300.0,4.7
175,667326,35.0,80.0,104.0,31.0,1.20,135.0,5.0,16.1,45.0,4300.0,5.2
176,508465,46.0,70.0,150.0,111.0,6.10,131.0,3.7,7.5,27.0,NaN,NaN
177,853426,41.0,70.0,125.0,38.0,0.60,140.0,5.0,16.8,41.0,6300.0,5.9
178,360756,55.0,90.0,143.0,88.0,2.00,NaN,NaN,NaN,NaN,NaN,NaN
179,856244,75.0,80.0,156.0,45.0,2.40,140.0,3.4,11.6,35.0,10300.0,4.0
180,553221,48.0,70.0,127.0,19.0,1.00,134.0,3.6,NaN,NaN,NaN,NaN
181,615697,6.0,60.0,94.0,67.0,1.00,135.0,4.9,9.9,30.0,16700.0,4.8
182,769512,38.0,60.0,91.0,36.0,0.70,135.0,3.7,14.0,46.0,9100.0,5.8
183,862446,54.0,120.0,103.0,18.0,1.20,NaN,NaN,NaN,NaN,NaN,NaN
184,925810,34.0,60.0,117.0,28.0,2.20,138.0,3.8,NaN,NaN,NaN,NaN
185,261137,35.0,60.0,105.0,39.0,0.50,135.0,3.9,14.7,43.0,5800.0,6.2
186,337834,48.0,70.0,117.0,56.0,3.80,111.0,2.5,11.2,32.0,6700.0,3.9
187,285690,45.0,80.0,82.0,49.0,0.60,147.0,4.4,15.9,46.0,9100.0,4.7
188,585429,70.0,70.0,171.0,153.0,5.20,NaN,NaN,NaN,NaN,NaN,NaN
189,565636,65.0,90.0,172.0,82.0,13.50,145.0,6.3,8.8,31.0,NaN,NaN
190,454830,64.0,70.0,113.0,94.0,7.30,137.0,4.3,7.9,21.0,NaN,NaN
191,202793,74.0,60.0,108.0,68.0,1.80,NaN,NaN,NaN,NaN,NaN,NaN
192,246165,69.0,80.0,NaN,103.0,4.10,132.0,5.9,12.5,NaN,NaN,NaN
193,949813,34.0,90.0,104.0,50.0,1.60,137.0,4.1,11.9,39.0,NaN,NaN
194,769512,38.0,60.0,91.0,36.0,0.70,135.0,3.7,14.0,46.0,9100.0,5.8
195,791928,68.0,70.0,100.0,54.0,24.00,104.0,4.0,12.4,36.0,NaN,NaN
196,654306,41.0,80.0,112.0,48.0,0.70,140.0,5.0,17.0,52.0,7200.0,5.8
197,321189,8.0,NaN,80.0,66.0,2.50,142.0,3.6,12.2,38.0,NaN,NaN
198,951380,47.0,80.0,NaN,28.0,0.90,NaN,NaN,12.4,44.0,5600.0,4.3
199,354223,64.0,70.0,97.0,27.0,0.70,145.0,4.8,13.8,49.0,6400.0,4.8
200,995177,69.0,70.0,214.0,96.0,6.30,120.0,3.9,9.4,28.0,11500.0,3.3
201,415906,60.0,80.0,131.0,10.0,0.50,146.0,5.0,14.5,41.0,10700.0,5.1
202,881763,42.0,70.0,75.0,31.0,1.20,141.0,3.5,16.5,54.0,7800.0,6.2
203,365669,54.0,90.0,150.0,18.0,1.20,140.0,4.2,NaN,NaN,NaN,NaN
204,782554,71.0,90.0,303.0,30.0,1.30,136.0,4.1,13.0,38.0,9200.0,4.6
205,928378,76.0,70.0,226.0,217.0,10.20,NaN,NaN,10.2,36.0,12700.0,4.2
206,183890,73.0,90.0,107.0,33.0,1.50,141.0,4.6,10.1,30.0,7800.0,4.0
207,330559,34.0,60.0,91.0,49.0,1.20,135.0,4.5,13.5,48.0,8600.0,4.9
208,583971,62.0,90.0,94.0,25.0,1.10,131.0,3.7,NaN,NaN,NaN,NaN
209,923613,64.0,60.0,239.0,58.0,4.30,137.0,5.4,9.5,29.0,7500.0,3.4
210,102677,59.0,70.0,76.0,186.0,15.00,135.0,7.6,7.1,22.0,3800.0,2.1
211,471614,52.0,80.0,128.0,30.0,1.20,140.0,4.5,15.2,52.0,4300.0,5.7
212,731540,63.0,70.0,130.0,37.0,0.90,150.0,5.0,13.4,41.0,7300.0,4.7
213,354223,64.0,70.0,97.0,27.0,0.70,145.0,4.8,13.8,49.0,6400.0,4.8
214,628271,65.0,90.0,270.0,39.0,2.00,NaN,NaN,12.0,36.0,9800.0,4.9
215,572140,55.0,80.0,104.0,28.0,0.90,142.0,4.8,17.3,52.0,8200.0,4.8
216,273038,47.0,60.0,117.0,22.0,1.20,138.0,3.5,13.0,45.0,5200.0,5.6
217,784295,29.0,80.0,70.0,16.0,0.70,138.0,3.5,13.7,54.0,5400.0,5.8
218,475527,47.0,100.0,204.0,29.0,1.00,139.0,4.2,9.7,33.0,9200.0,4.5
219,937729,65.0,70.0,93.0,66.0,1.60,137.0,4.5,11.6,36.0,11900.0,3.9
220,943166,50.0,60.0,490.0,55.0,4.00,NaN,NaN,9.4,28.0,NaN,NaN
221,133327,60.0,100.0,263.0,27.0,1.30,135.0,4.3,12.7,37.0,11400.0,4.3
222,623377,34.0,70.0,NaN,33.0,1.00,150.0,5.0,15.3,44.0,10500.0,6.1
223,546742,65.0,100.0,90.0,98.0,2.50,NaN,NaN,9.1,28.0,5500.0,3.6
224,924216,65.0,60.0,109.0,39.0,1.00,144.0,3.5,13.9,48.0,9600.0,4.8
225,476143,21.0,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,504617,55.0,100.0,297.0,53.0,2.80,139.0,4.5,11.2,34.0,13600.0,4.4
227,577147,54.0,80.0,208.0,89.0,5.90,130.0,4.9,9.3,NaN,NaN,NaN
228,977137,71.0,60.0,424.0,48.0,1.50,132.0,4.0,10.9,31.0,NaN,NaN
229,397388,63.0,100.0,280.0,35.0,3.20,143.0,3.5,13.0,40.0,9800.0,4.2
230,570056,61.0,90.0,159.0,39.0,1.50,133.0,4.9,11.3,34.0,9600.0,4.0
231,545996,62.0,80.0,246.0,24.0,1.00,NaN,NaN,13.6,40.0,8500.0,4.7
232,828492,NaN,70.0,219.0,36.0,1.30,139.0,3.7,12.5,37.0,9800.0,4.4
233,809452,66.0,70.0,94.0,19.0,0.70,135.0,3.9,16.0,41.0,5300.0,5.9
234,727550,80.0,70.0,141.0,53.0,2.20,NaN,NaN,12.7,40.0,9600.0,NaN
235,910351,27.0,60.0,76.0,44.0,3.90,127.0,4.3,NaN,NaN,NaN,NaN
236,780219,70.0,100.0,118.0,125.0,5.30,136.0,4.9,12.0,37.0,8400.0,8.0
237,696591,46.0,70.0,100.0,47.0,0.50,142.0,3.5,16.4,43.0,5700.0,6.5
238,996076,57.0,60.0,105.0,49.0,1.20,150.0,4.7,15.7,44.0,10400.0,6.2
239,850360,48.0,80.0,121.0,36.0,1.20,NaN,NaN,15.4,44.0,7800.0,5.2
240,489160,28.0,60.0,79.0,50.0,0.50,145.0,5.0,17.6,51.0,6500.0,5.0
241,636769,50.0,90.0,128.0,208.0,9.20,134.0,4.8,8.2,22.0,16300.0,2.7
242,834066,55.0,80.0,133.0,17.0,1.20,135.0,4.8,13.2,41.0,6800.0,5.3
243,991374,34.0,70.0,NaN,219.0,12.20,130.0,3.8,6.0,NaN,NaN,NaN
244,302906,59.0,100.0,NaN,96.0,6.40,NaN,NaN,6.6,NaN,NaN,NaN
245,431871,57.0,60.0,132.0,18.0,1.10,150.0,4.7,15.4,42.0,11000.0,4.5
246,794293,54.0,100.0,162.0,66.0,1.60,136.0,4.4,10.3,33.0,NaN,NaN
247,930504,45.0,70.0,113.0,93.0,2.30,NaN,NaN,7.9,26.0,5700.0,NaN
248,687021,52.0,80.0,99.0,25.0,0.80,135.0,3.7,15.0,52.0,6300.0,5.3
249,843449,30.0,80.0,131.0,38.0,1.00,147.0,3.8,14.1,45.0,9400.0,5.3
250,648958,68.0,90.0,238.0,57.0,2.50,NaN,NaN,9.8,28.0,8000.0,3.3
251,438182,73.0,80.0,253.0,142.0,4.60,138.0,5.8,10.5,33.0,7200.0,4.3
252,353996,66.0,70.0,248.0,30.0,1.70,138.0,5.3,NaN,NaN,NaN,NaN
253,250046,56.0,60.0,132.0,18.0,1.10,147.0,4.7,13.7,45.0,7500.0,5.6
254,544587,56.0,180.0,298.0,24.0,1.20,139.0,3.9,11.2,32.0,10400.0,4.2
255,251975,NaN,80.0,100.0,49.0,1.00,140.0,5.0,16.3,53.0,8500.0,4.9
256,234626,24.0,70.0,140.0,23.0,0.60,140.0,4.7,16.3,48.0,5800.0,5.6
257,390779,48.0,80.0,122.0,33.0,0.90,146.0,3.9,13.9,48.0,9500.0,4.8
258,625487,57.0,80.0,NaN,111.0,9.30,124.0,5.3,6.8,NaN,4300.0,3.0
259,580048,61.0,80.0,360.0,19.0,0.70,137.0,4.4,15.2,44.0,8300.0,5.2
260,118596,74.0,60.0,88.0,50.0,0.60,147.0,3.7,17.2,53.0,6000.0,4.5
261,955830,55.0,80.0,214.0,73.0,3.90,137.0,4.9,10.9,34.0,7400.0,3.7
262,223886,70.0,80.0,158.0,85.0,3.20,141.0,3.5,10.1,30.0,NaN,NaN
263,369844,20.0,60.0,NaN,NaN,NaN,137.0,4.7,14.0,41.0,4500.0,5.5
264,746768,25.0,70.0,88.0,42.0,0.50,136.0,3.5,13.3,48.0,7000.0,4.9
265,628271,65.0,90.0,270.0,39.0,2.00,NaN,NaN,12.0,36.0,9800.0,4.9
266,674446,55.0,80.0,130.0,50.0,1.20,147.0,5.0,15.5,41.0,9100.0,6.0
267,617089,67.0,80.0,182.0,391.0,32.00,163.0,39.0,NaN,NaN,NaN,NaN
268,918330,60.0,80.0,81.0,15.0,0.50,141.0,3.6,15.0,46.0,10500.0,5.3
269,862719,61.0,80.0,131.0,23.0,0.80,140.0,4.1,11.3,35.0,NaN,NaN
270,602549,52.0,100.0,138.0,60.0,1.90,NaN,NaN,10.8,33.0,9600.0,4.0
271,146165,40.0,80.0,119.0,15.0,0.70,150.0,4.9,NaN,NaN,NaN,NaN
272,499221,30.0,80.0,96.0,25.0,0.50,144.0,4.8,13.8,42.0,9000.0,4.5
273,862719,61.0,80.0,131.0,23.0,0.80,140.0,4.1,11.3,35.0,NaN,NaN
274,828592,71.0,70.0,219.0,82.0,3.60,133.0,4.4,10.4,33.0,5600.0,3.6
275,843362,71.0,60.0,118.0,125.0,5.30,136.0,4.9,11.4,35.0,15200.0,4.3
276,634224,75.0,70.0,107.0,48.0,0.80,144.0,3.5,13.6,46.0,10300.0,4.8
277,552449,72.0,90.0,308.0,36.0,2.50,131.0,4.3,NaN,NaN,NaN,NaN
278,482105,44.0,60.0,95.0,46.0,0.50,138.0,4.2,15.0,50.0,7700.0,6.3
279,888096,NaN,90.0,207.0,80.0,6.80,142.0,5.5,8.5,NaN,NaN,NaN
280,143270,63.0,90.0,123.0,19.0,2.00,142.0,3.8,11.7,34.0,11400.0,4.7
281,670655,80.0,80.0,119.0,46.0,0.70,141.0,4.9,13.9,49.0,5100.0,5.0
282,131563,29.0,80.0,83.0,49.0,0.90,139.0,3.3,17.5,40.0,9900.0,4.7
283,163383,NaN,70.0,104.0,16.0,0.50,NaN,NaN,NaN,NaN,NaN,NaN
284,923398,51.0,80.0,94.0,15.0,1.20,144.0,3.7,15.5,46.0,9500.0,6.4
285,693440,76.0,70.0,92.0,29.0,1.80,133.0,3.9,10.3,32.0,NaN,NaN
286,604045,30.0,60.0,120.0,31.0,0.80,150.0,4.6,13.4,44.0,10700.0,5.8
287,551175,47.0,80.0,124.0,44.0,1.00,140.0,4.9,14.9,41.0,7000.0,5.7
288,466320,50.0,140.0,101.0,106.0,6.50,135.0,4.3,6.2,18.0,5800.0,2.3
289,837729,65.0,70.0,85.0,20.0,1.00,142.0,4.8,16.1,43.0,9600.0,4.5
290,955478,34.0,70.0,139.0,19.0,0.90,NaN,NaN,12.7,42.0,2200.0,NaN
291,162229,NaN,70.0,220.0,68.0,2.80,NaN,NaN,8.7,27.0,NaN,NaN
292,202793,74.0,60.0,108.0,68.0,1.80,NaN,NaN,NaN,NaN,NaN,NaN
293,585863,29.0,70.0,127.0,44.0,1.20,145.0,5.0,14.8,48.0,NaN,NaN
294,858794,71.0,70.0,79.0,47.0,0.50,142.0,4.8,16.6,40.0,5800.0,5.9
295,997876,64.0,70.0,107.0,15.0,NaN,NaN,NaN,12.8,38.0,NaN,NaN
296,963946,50.0,80.0,137.0,46.0,0.80,139.0,5.0,14.1,45.0,9500.0,4.6
297,816565,65.0,80.0,74.0,66.0,2.00,136.0,5.4,9.1,25.0,NaN,NaN
298,297893,68.0,80.0,157.0,90.0,4.10,130.0,6.4,5.6,16.0,11000.0,2.6
299,224481,54.0,60.0,125.0,21.0,1.30,137.0,3.4,15.0,46.0,NaN,NaN
300,856244,75.0,80.0,156.0,45.0,2.40,140.0,3.4,11.6,35.0,10300.0,4.0
301,805571,41.0,80.0,210.0,165.0,18.00,135.0,4.7,NaN,NaN,NaN,NaN
302,153227,60.0,90.0,490.0,95.0,2.70,131.0,3.8,11.5,35.0,12000.0,4.5

# Part 2: Analyze the Dataset

Refer to this: https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease

Explain what the each data is in your own words. What are the features and labels? Are the features in the given datasets : categorical, numerical or both? Give 3 examples of categorical and numerical columns each (if they exist)

Answer: This dataset contains many health-related features, such as specific blood test results and common comorbidities, as well as whether or not the person has chronic kidney disease, in order to predict chronic kidney disease.

The features of this dataset are age, blood pressure (bp, in mm/Hg), specific gravity (sg), albumin (al), sugar (su), red blood cells (rbc), pus cell (pc), pus cell clumps (pcc), bacteria (ba), blood glucose random (bgr, in mgs/dl), blood urea (bu, in mgs/dl), serum creatinine (sc, in mgs/dl), sodium (sod, in mEq/L), potassium (pot, in mEq/L), hemoglobin (hemo, in gms), packed cell volume (pcv), white blood cell count (wbcc, in cells/cmm), red blood cell count (rbcc, in millions/cmm), hypertension (htn), diabetes mellitus (dm), coronary artery disease (cad), appetite (appet), pedal edema (pe), and anemia (ane).

The labels of this dataset are "ckd" and "not ckd" from the class or Target column, indicating whether or not the person has chronic kidney disease.

The dataset has both categorical and numerical features as columns. 3 categorical features are hypertension, appetite, and anemia. 3 numerical features are age, blood pressure, and potassium.

# Part 3: Data Preprocessing

A fundamental skill in Machine Learning is mastering the art of data cleaning and preprocessing. In this assignment, you will learn and apply essential data cleaning techniques to transform a raw dataset into a clean, ready-to-use form which you can use for regression or classification tasks. By the end of this assignment, you'll have a fully clean dataset and a solid foundation in preparing data for various machine learning models.

## Part 3.1 : Drop Duplicate rows

Let's start by checking if the given datasets have any duplicate rows (same Unique Id). Use pandas to identify and remove these duplicate rows from the given dataset

In [5]:
# For the numerical dataset, check if there are duplicate rows in the dataset. If yes, print total number of duplicate rows
print("The numerical dataset has " + str(num_df.duplicated(subset=["unique_id"]).sum()) + " duplicate rows.")

# Drop these duplicate rows
num_df = num_df.drop_duplicates(subset=["unique_id"])

# Repeat the same for categorical dataset. Print the duplicate rows and drop them
print("The categorical dataset has " + str(cat_df.duplicated(subset=["unique_id"]).sum()) + " duplicate rows.")
cat_df = cat_df.drop_duplicates(subset=["unique_id"])

The numerical dataset has 30 duplicate rows.
The categorical dataset has 30 duplicate rows.

## Part 3.2: Combine two differents datasets

A good skill to have is to know how to combine 2 different datasets.

Are all the unique ids are present in both datasets? Why do you think so? If not, what do the rows that are missing from one of the datasets look like in the combined table?

Answer: Not all of the unique ids are present in both datasets, since the categorical dataset has 10 more unique rows than the numerical dataset (400 vs. 390). The rows that are missing from one of the datasets are not present in the combined table, since merge uses an inner join by default.

In [6]:
# Merge the two given numerical and categorical datasets based on their unique_ID.
both_df = num_df.merge(cat_df, on='unique_id')
#Print the combined dataset
display(both_df)

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc,al,su,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,Target
0,203694,38.0,80.0,99.0,19.0,0.50,147.0,3.5,13.6,44.0,7300.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
1,938027,43.0,60.0,108.0,25.0,1.00,144.0,5.0,17.8,43.0,7200.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
2,421471,37.0,60.0,111.0,35.0,0.80,135.0,4.1,16.2,50.0,5500.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
3,764115,70.0,90.0,144.0,125.0,4.00,136.0,4.6,12.0,37.0,8200.0,4.5,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
4,240975,47.0,80.0,95.0,35.0,0.90,140.0,4.1,NaN,NaN,NaN,NaN,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
5,992643,35.0,70.0,82.0,36.0,1.10,150.0,3.5,14.5,52.0,9400.0,6.1,0.0,0.0,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,notckd
6,573400,60.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
7,109053,64.0,60.0,106.0,27.0,0.70,150.0,3.3,14.4,42.0,8100.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
8,352995,33.0,60.0,130.0,41.0,0.90,141.0,4.4,15.5,52.0,4300.0,5.8,NaN,NaN,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
9,395450,65.0,70.0,203.0,46.0,1.40,NaN,NaN,11.4,36.0,5000.0,4.1,1.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
10,261025,62.0,90.0,169.0,48.0,2.40,138.0,2.9,13.4,47.0,11000.0,6.1,2.0,1.0,NaN,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
11,389919,61.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9800.0,NaN,0.0,2.0,NaN,normal,notpresent,notpresent,no,yes,no,poor,no,yes,ckd
12,210452,72.0,90.0,124.0,53.0,2.30,NaN,NaN,11.9,39.0,NaN,NaN,2.0,0.0,NaN,abnormal,present,notpresent,no,no,no,good,no,no,ckd
13,349892,59.0,70.0,424.0,55.0,1.70,138.0,4.5,12.6,37.0,10200.0,4.1,1.0,3.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,good,no,no,ckd
14,943161,65.0,60.0,192.0,17.0,1.70,130.0,4.3,NaN,NaN,9500.0,NaN,2.0,0.0,normal,abnormal,present,notpresent,yes,yes,no,poor,no,no,ckd\t
15,224481,54.0,60.0,125.0,21.0,1.30,137.0,3.4,15.0,46.0,NaN,NaN,3.0,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,yes,no,ckd
16,335961,67.0,80.0,99.0,40.0,0.50,NaN,NaN,17.8,44.0,5900.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
17,630177,58.0,80.0,131.0,18.0,1.10,141.0,3.5,15.8,53.0,6800.0,6.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
18,741276,23.0,60.0,95.0,24.0,0.80,145.0,5.0,15.0,52.0,6300.0,4.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
19,546010,49.0,80.0,122.0,32.0,1.20,139.0,3.9,17.0,41.0,5600.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
20,460465,47.0,60.0,109.0,25.0,1.10,141.0,4.7,15.8,41.0,8300.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
21,619200,68.0,80.0,171.0,30.0,1.00,NaN,NaN,13.7,43.0,4900.0,5.2,0.0,0.0,NaN,abnormal,notpresent,notpresent,no,yes,no,good,no,no,ckd
22,965166,48.0,80.0,75.0,22.0,0.80,137.0,5.0,16.8,51.0,6000.0,6.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
23,201677,33.0,80.0,89.0,19.0,1.10,144.0,5.0,15.0,40.0,10300.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
24,976875,33.0,60.0,80.0,25.0,0.90,146.0,3.5,14.1,48.0,7800.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
25,340466,57.0,90.0,NaN,322.0,13.00,126.0,4.8,8.0,24.0,4200.0,3.3,5.0,0.0,abnormal,abnormal,notpresent,present,yes,yes,yes,poor,yes,yes,ckd
26,515110,47.0,80.0,93.0,33.0,0.90,144.0,4.5,13.3,52.0,8100.0,5.2,NaN,NaN,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,notckd
27,673081,44.0,90.0,NaN,20.0,1.10,NaN,NaN,15.0,48.0,NaN,NaN,1.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
28,508469,15.0,60.0,86.0,15.0,0.60,138.0,4.0,11.0,33.0,7700.0,3.8,3.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
29,917844,61.0,60.0,108.0,75.0,1.90,141.0,5.2,9.9,29.0,8400.0,3.7,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
30,726486,26.0,70.0,250.0,20.0,1.10,NaN,NaN,15.6,52.0,6900.0,6.0,0.0,4.0,NaN,normal,notpresent,notpresent,no,yes,no,good,no,no,ckd
31,819747,75.0,70.0,123.0,31.0,1.40,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
32,856086,60.0,90.0,NaN,180.0,76.00,4.5,NaN,10.9,32.0,6200.0,3.6,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,yes,good,no,no,ckd
33,719711,43.0,80.0,114.0,32.0,1.10,135.0,3.9,NaN,42.0,NaN,NaN,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
34,104675,65.0,80.0,215.0,133.0,2.50,NaN,NaN,13.2,41.0,NaN,NaN,2.0,1.0,normal,normal,present,notpresent,no,yes,no,good,no,no,ckd
35,431871,57.0,60.0,132.0,18.0,1.10,150.0,4.7,15.4,42.0,11000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
36,857435,60.0,70.0,140.0,27.0,1.20,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
37,534003,42.0,80.0,132.0,24.0,0.70,140.0,4.1,14.4,50.0,5000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
38,300354,61.0,70.0,100.0,28.0,2.10,NaN,NaN,12.6,43.0,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,no,ckd
39,717463,67.0,70.0,NaN,106.0,6.00,137.0,4.9,6.1,19.0,6500.0,NaN,1.0,0.0,normal,normal,notpresent,notpresent,yes,no,no,good,no,yes,ckd
40,737689,62.0,NaN,NaN,NaN,NaN,NaN,NaN,14.3,42.0,10200.0,4.8,3.0,0.0,abnormal,NaN,notpresent,notpresent,yes,yes,no,good,no,no,ckd
41,947246,73.0,60.0,127.0,48.0,0.50,150.0,3.5,15.1,52.0,11000.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
42,441170,79.0,80.0,111.0,44.0,1.20,146.0,3.6,16.3,40.0,8000.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
43,359624,43.0,80.0,NaN,30.0,1.10,NaN,NaN,14.0,42.0,14900.0,NaN,2.0,3.0,NaN,abnormal,present,present,no,no,no,good,no,no,ckd
44,675800,60.0,80.0,172.0,32.0,2.70,NaN,NaN,11.2,36.0,NaN,NaN,1.0,1.0,NaN,normal,notpresent,notpresent,no,yes,yes,poor,no,no,ckd
45,917565,45.0,90.0,360.0,45.0,2.40,128.0,4.4,8.3,29.0,5500.0,3.7,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,no,ckd
46,557347,34.0,80.0,121.0,27.0,1.20,144.0,3.9,13.6,52.0,9200.0,6.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
47,643841,23.0,80.0,99.0,46.0,1.20,142.0,4.0,17.7,46.0,4300.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
48,504652,63.0,80.0,NaN,NaN,3.40,136.0,4.2,13.0,40.0,9800.0,4.2,2.0,2.0,normal,NaN,notpresent,notpresent,yes,no,yes,good,no,no,ckd
49,943378,47.0,100.0,122.0,NaN,16.90,138.0,5.2,10.8,33.0,10200.0,3.8,NaN,NaN,normal,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
50,480497,67.0,70.0,102.0,48.0,3.20,137.0,5.0,11.9,34.0,7100.0,3.7,1.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,yes,no,ckd
51,583717,54.0,70.0,233.0,50.1,1.90,NaN,NaN,11.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
52,608902,56.0,90.0,176.0,309.0,13.30,124.0,6.5,3.1,9.0,5400.0,2.1,4.0,1.0,normal,abnormal,present,notpresent,yes,yes,no,poor,yes,yes,ckd
53,261137,35.0,60.0,105.0,39.0,0.50,135.0,3.9,14.7,43.0,5800.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
54,721270,58.0,70.0,102.0,48.0,1.20,139.0,4.3,15.0,40.0,8100.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
55,385412,46.0,90.0,213.0,68.0,2.80,146.0,6.3,9.3,NaN,NaN,NaN,NaN,NaN,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
56,980291,62.0,70.0,122.0,42.0,1.70,136.0,4.7,12.6,39.0,7900.0,3.9,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
57,488012,50.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,abnormal,abnormal,notpresent,notpresent,no,no,no,good,yes,no,ckd
58,271687,66.0,90.0,153.0,76.0,3.30,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,normal,notpresent,present,no,no,no,poor,no,no,ckd
59,566581,73.0,90.0,234.0,56.0,1.90,NaN,NaN,10.3,28.0,NaN,NaN,1.0,4.0,abnormal,abnormal,present,notpresent,no,yes,no,good,no,no,ckd
60,311664,42.0,90.0,93.0,153.0,2.70,139.0,4.3,9.8,34.0,9800.0,NaN,2.0,0.0,abnormal,abnormal,present,notpresent,no,no,no,poor,yes,yes,ckd
61,872034,70.0,90.0,184.0,98.6,3.30,138.0,3.9,5.8,NaN,NaN,NaN,2.0,1.0,abnormal,abnormal,notpresent,present,yes,yes,yes,poor,no,no,ckd
62,373780,24.0,80.0,93.0,46.0,1.00,145.0,3.5,NaN,NaN,10700.0,6.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
63,902019,NaN,100.0,129.0,107.0,6.70,132.0,4.4,4.8,14.0,6300.0,NaN,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,no,no,good,yes,yes,ckd
64,418316,62.0,80.0,78.0,45.0,0.60,138.0,3.5,16.1,50.0,5400.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
65,750284,52.0,90.0,224.0,166.0,5.60,133.0,47.0,8.1,23.0,5000.0,2.9,4.0,3.0,normal,abnormal,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
66,524004,30.0,80.0,82.0,42.0,0.70,146.0,5.0,14.9,45.0,9400.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
67,268609,56.0,80.0,139.0,15.0,1.20,135.0,5.0,14.8,42.0,5600.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
68,308740,65.0,70.0,139.0,29.0,1.00,NaN,NaN,10.5,32.0,NaN,NaN,1.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,no,no,good,yes,no,ckd
69,549224,70.0,100.0,169.0,47.0,2.90,NaN,NaN,11.1,32.0,5800.0,5.0,1.0,0.0,normal,abnormal,present,notpresent,yes,yes,no,poor,no,no,ckd
70,461152,50.0,NaN,92.0,19.0,1.20,150.0,4.8,14.9,48.0,4700.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
71,328705,39.0,70.0,131.0,46.0,0.60,145.0,5.0,15.6,41.0,9400.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
72,365358,75.0,60.0,110.0,50.0,0.70,135.0,5.0,14.3,40.0,8300.0,5.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,NaN,NaN,NaN,notckd
73,948185,45.0,60.0,268.0,86.0,4.00,134.0,5.1,10.0,29.0,9200.0,NaN,2.0,0.0,normal,abnormal,present,notpresent,yes,yes,no,good,no,no,ckd
74,971494,65.0,70.0,112.0,73.0,3.30,NaN,NaN,10.9,37.0,NaN,NaN,2.0,0.0,NaN,normal,present,notpresent,no,no,no,good,no,no,ckd
75,559987,78.0,60.0,114.0,74.0,2.90,135.0,5.9,8.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,no,yes,no,good,no,yes,ckd
76,852091,45.0,70.0,NaN,20.0,0.70,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,yes,no,ckd
77,770544,55.0,70.0,107.0,26.0,1.10,NaN,NaN,17.0,50.0,6700.0,6.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
78,501321,4.0,NaN,99.0,23.0,0.60,138.0,4.4,12.0,34.0,NaN,NaN,1.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
79,283427,55.0,80.0,140.0,49.0,0.50,150.0,4.9,15.7,47.0,6700.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
80,490253,43.0,80.0,81.0,46.0,0.60,135.0,4.9,13.9,48.0,6900.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
81,302906,59.0,100.0,NaN,96.0,6.40,NaN,NaN,6.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
82,991031,30.0,80.0,89.0,42.0,0.50,139.0,5.0,16.7,52.0,10200.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
83,271932,72.0,90.0,84.0,145.0,7.10,135.0,5.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
84,319394,33.0,90.0,92.0,19.0,0.80,NaN,NaN,11.8,34.0,7000.0,NaN,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
85,379507,17.0,60.0,114.0,50.0,1.00,135.0,4.9,14.2,51.0,7200.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
86,676393,63.0,70.0,113.0,25.0,0.60,146.0,4.9,16.5,52.0,8000.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
87,175008,65.0,80.0,92.0,37.0,1.50,140.0,5.2,8.8,25.0,10700.0,3.2,0.0,0.0,NaN,normal,notpresent,notpresent,yes,no,yes,good,yes,no,ckd
88,311824,48.0,70.0,124.0,24.0,1.20,142.0,4.2,12.4,37.0,6400.0,4.7,0.0,0.0,NaN,normal,notpresent,notpresent,no,yes,no,good,no,no,ckd
89,114717,41.0,80.0,122.0,25.0,0.80,138.0,5.0,17.1,41.0,9100.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
90,760698,34.0,70.0,153.0,22.0,0.90,133.0,3.8,NaN,NaN,NaN,NaN,4.0,0.0,abnormal,abnormal,notpresent,notpresent,no,no,no,good,yes,no,ckd
91,950823,7.0,50.0,NaN,18.0,0.80,NaN,NaN,11.3,38.0,6000.0,NaN,4.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
92,462735,14.0,NaN,192.0,15.0,0.80,137.0,4.2,14.3,40.0,9500.0,5.4,0.0,0.0,NaN,NaN,notpresent,notpresent,no,yes,no,poor,yes,no,ckd
93,534245,45.0,70.0,117.0,52.0,2.20,136.0,3.8,10.0,30.0,19100.0,3.7,2.0,0.0,normal,abnormal,present,notpresent,no,no,no,good,no,no,ckd
94,137148,73.0,100.0,295.0,90.0,5.60,140.0,2.9,9.2,30.0,7000.0,3.2,3.0,2.0,abnormal,abnormal,present,notpresent,yes,yes,yes,poor,no,no,ckd
95,766869,56.0,90.0,242.0,132.0,16.40,140.0,4.2,8.4,26.0,NaN,3.0,4.0,3.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
96,750155,46.0,60.0,123.0,46.0,1.00,135.0,5.0,15.7,50.0,6300.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
97,536401,48.0,100.0,103.0,79.0,5.30,135.0,6.3,6.3,19.0,7200.0,2.6,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,no,yes,poor,no,no,ckd
98,708255,3.0,NaN,NaN,22.0,0.70,NaN,NaN,10.7,34.0,12300.0,NaN,2.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
99,734262,35.0,80.0,79.0,202.0,10.80,134.0,3.4,7.9,24.0,7900.0,3.1,1.0,0.0,abnormal,NaN,notpresent,notpresent,no,yes,no,good,no,no,ckd
100,559168,44.0,70.0,NaN,NaN,NaN,NaN,NaN,13.8,48.0,7800.0,4.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
101,393837,76.0,90.0,172.0,46.0,1.70,141.0,5.5,9.6,30.0,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
102,124446,65.0,80.0,115.0,32.0,11.50,139.0,4.0,14.1,42.0,6800.0,5.2,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
103,203466,22.0,60.0,97.0,18.0,1.20,138.0,4.3,13.5,42.0,7900.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
104,593735,39.0,70.0,121.0,20.0,0.80,133.0,3.5,10.9,32.0,NaN,NaN,0.0,0.0,NaN,normal,notpresent,notpresent,no,yes,no,good,no,no,ckd
105,213257,35.0,80.0,NaN,NaN,NaN,NaN,NaN,9.5,28.0,NaN,NaN,3.0,0.0,abnormal,normal,notpresent,notpresent,no,no,no,good,yes,no,ckd
106,484175,53.0,90.0,70.0,107.0,7.20,114.0,3.7,9.5,29.0,12100.0,3.7,2.0,0.0,abnormal,abnormal,present,notpresent,yes,yes,no,poor,no,yes,ckd
107,895508,62.0,80.0,309.0,113.0,2.90,130.0,2.5,10.6,34.0,12800.0,4.9,1.0,2.0,NaN,NaN,notpresent,notpresent,no,no,no,good,no,no,ckd
108,277576,80.0,70.0,NaN,49.0,1.20,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,abnormal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
109,205058,75.0,70.0,158.0,49.0,1.40,135.0,4.7,11.1,NaN,NaN,NaN,1.0,0.0,NaN,normal,notpresent,notpresent,yes,no,no,poor,yes,no,ckd
110,228849,58.0,80.0,100.0,50.0,1.20,140.0,3.5,14.0,50.0,6700.0,6.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
111,840399,60.0,90.0,74.0,25.0,1.10,142.0,3.2,12.2,39.0,7800.0,4.4,3.0,0.0,NaN,NaN,notpresent,notpresent,yes,yes,no,good,yes,no,ckd
112,431172,55.0,70.0,99.0,25.0,1.20,NaN,NaN,11.4,NaN,NaN,NaN,3.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,poor,yes,no,ckd
113,754973,39.0,60.0,86.0,37.0,0.60,150.0,5.0,13.6,51.0,5800.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
114,422844,NaN,70.0,110.0,115.0,6.00,134.0,2.7,9.1,26.0,9200.0,3.4,3.0,0.0,normal,normal,notpresent,notpresent,yes,yes,no,poor,no,no,ckd
115,517373,36.0,80.0,103.0,NaN,NaN,NaN,NaN,11.9,36.0,8800.0,NaN,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
116,103570,24.0,80.0,125.0,NaN,NaN,136.0,3.5,15.4,43.0,5600.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
117,353930,17.0,70.0,22.0,1.5,7.30,145.0,2.8,13.1,41.0,11200.0,NaN,1.0,0.0,abnormal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
118,673458,5.0,50.0,NaN,25.0,0.60,NaN,NaN,11.8,36.0,12400.0,NaN,0.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
119,259239,62.0,80.0,423.0,53.0,1.80,NaN,NaN,9.6,31.0,7500.0,NaN,2.0,3.0,normal,normal,notpresent,notpresent,no,yes,no,poor,no,yes,ckd
120,343784,63.0,100.0,78.0,61.0,1.80,141.0,4.4,12.2,36.0,10500.0,4.3,1.0,0.0,NaN,normal,notpresent,notpresent,no,yes,no,good,no,no,ckd
121,840392,47.0,80.0,114.0,87.0,5.20,139.0,3.7,12.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,no,no,poor,no,no,ckd
122,235579,46.0,60.0,102.0,27.0,0.70,142.0,4.9,13.2,44.0,11000.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
123,997629,35.0,NaN,99.0,30.0,0.50,135.0,4.9,15.4,48.0,5000.0,5.2,0.0,0.0,normal,normal,NaN,NaN,no,no,no,good,no,no,notckd
124,614376,57.0,80.0,119.0,17.0,1.20,135.0,4.7,15.4,42.0,6200.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
125,450314,5.0,NaN,NaN,16.0,0.70,138.0,3.2,8.1,NaN,NaN,NaN,1.0,0.0,NaN,normal,notpresent,notpresent,no,no,no,good,no,yes,ckd
126,466489,8.0,60.0,78.0,27.0,0.90,NaN,NaN,12.3,41.0,6700.0,NaN,3.0,0.0,normal,normal,notpresent,notpresent,no,no,no,poor,yes,no,ckd
127,643007,76.0,90.0,93.0,155.0,7.30,132.0,4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,normal,notpresent,notpresent,yes,yes,yes,poor,no,no,ckd
128,125587,37.0,60.0,109.0,47.0,1.10,141.0,4.9,15.0,48.0,7000.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
129,679864,53.0,60.0,91.0,114.0,3.25,142.0,4.3,8.6,28.0,11000.0,3.8,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
130,516741,12.0,60.0,NaN,51.0,1.80,NaN,NaN,12.1,NaN,10300.0,NaN,3.0,0.0,abnormal,abnormal,present,notpresent,no,no,no,good,no,no,ckd
131,647552,61.0,70.0,120.0,29.0,0.70,137.0,3.5,17.4,52.0,7000.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
132,353938,60.0,70.0,124.0,52.0,2.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,no,no,good,no,no,ckd
133,523454,60.0,70.0,109.0,96.0,3.90,135.0,4.0,13.8,41.0,NaN,NaN,1.0,0.0,NaN,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
134,602404,55.0,90.0,273.0,235.0,14.20,132.0,3.4,8.3,22.0,14600.0,2.9,2.0,1.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
135,315377,37.0,100.0,NaN,19.0,1.30,NaN,NaN,15.0,44.0,4100.0,5.2,0.0,0.0,abnormal,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
136,514721,56.0,90.0,129.0,107.0,6.70,131.0,4.8,9.1,29.0,6400.0,3.4,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,no,no,good,no,no,ckd
137,878575,64.0,90.0,NaN,35.0,1.30,NaN,NaN,10.3,NaN,NaN,NaN,3.0,3.0,NaN,abnormal,present,notpresent,yes,yes,no,good,yes,no,ckd
138,723356,41.0,70.0,NaN,68.0,2.80,132.0,4.1,11.1,33.0,NaN,NaN,2.0,0.0,NaN,abnormal,notpresent,present,yes,no,no,good,yes,yes,ckd
139,412799,25.0,60.0,119.0,27.0,0.50,NaN,NaN,15.2,40.0,9200.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
140,436833,57.0,80.0,120.0,48.0,1.60,NaN,NaN,11.3,36.0,7200.0,3.8,0.0,0.0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
141,596932,45.0,80.0,425.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,normal,abnormal,notpresent,notpresent,no,no,no,poor,no,no,ckd
142,499228,32.0,70.0,100.0,29.0,1.10,142.0,4.5,14.3,43.0,6700.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
143,459229,57.0,80.0,133.0,48.0,1.20,147.0,4.3,14.8,46.0,6600.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
144,506348,81.0,60.0,148.0,39.0,2.10,147.0,4.2,10.9,35.0,9400.0,2.4,NaN,NaN,NaN,NaN,notpresent,notpresent,yes,yes,yes,poor,yes,no,ckd
145,781942,47.0,60.0,137.0,17.0,0.50,150.0,3.5,13.6,44.0,7900.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
146,617948,34.0,70.0,87.0,38.0,0.50,144.0,4.8,17.1,47.0,7400.0,6.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
147,750202,50.0,NaN,219.0,176.0,13.80,136.0,4.5,8.6,24.0,13200.0,2.7,NaN,NaN,normal,NaN,notpresent,notpresent,yes,no,no,good,yes,yes,ckd

## Part 3.3: Rows with Missing values

Removing missing values from a dataset is important for classification because it ensures the model is trained on complete and accurate data, leading to better performance and reliable predictions. Incomplete data can introduce bias and errors, negatively impacting the model's effectiveness.

In [7]:
# Calculate the percentage of rows that contain atleast one missing value
proportion = 1 - (len(both_df.dropna()) / len(both_df)) 
# Print %
print("Percent of rows that contain at least one missing value: " + str(100*proportion) + "%")
# Drop these rows from the dataset
both_df = both_df.dropna()
# Print the Dataset
display(both_df)

Percent of rows that contain at least one missing value: 60.769230769230774%

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc,al,su,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,Target
0,203694,38.0,80.0,99.0,19.0,0.5,147.0,3.5,13.6,44.0,7300.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
1,938027,43.0,60.0,108.0,25.0,1.0,144.0,5.0,17.8,43.0,7200.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
2,421471,37.0,60.0,111.0,35.0,0.8,135.0,4.1,16.2,50.0,5500.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
7,109053,64.0,60.0,106.0,27.0,0.7,150.0,3.3,14.4,42.0,8100.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
13,349892,59.0,70.0,424.0,55.0,1.7,138.0,4.5,12.6,37.0,10200.0,4.1,1.0,3.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,good,no,no,ckd
17,630177,58.0,80.0,131.0,18.0,1.1,141.0,3.5,15.8,53.0,6800.0,6.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
18,741276,23.0,60.0,95.0,24.0,0.8,145.0,5.0,15.0,52.0,6300.0,4.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
19,546010,49.0,80.0,122.0,32.0,1.2,139.0,3.9,17.0,41.0,5600.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
20,460465,47.0,60.0,109.0,25.0,1.1,141.0,4.7,15.8,41.0,8300.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
22,965166,48.0,80.0,75.0,22.0,0.8,137.0,5.0,16.8,51.0,6000.0,6.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
23,201677,33.0,80.0,89.0,19.0,1.1,144.0,5.0,15.0,40.0,10300.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
24,976875,33.0,60.0,80.0,25.0,0.9,146.0,3.5,14.1,48.0,7800.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
35,431871,57.0,60.0,132.0,18.0,1.1,150.0,4.7,15.4,42.0,11000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
37,534003,42.0,80.0,132.0,24.0,0.7,140.0,4.1,14.4,50.0,5000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
41,947246,73.0,60.0,127.0,48.0,0.5,150.0,3.5,15.1,52.0,11000.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
42,441170,79.0,80.0,111.0,44.0,1.2,146.0,3.6,16.3,40.0,8000.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
46,557347,34.0,80.0,121.0,27.0,1.2,144.0,3.9,13.6,52.0,9200.0,6.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
47,643841,23.0,80.0,99.0,46.0,1.2,142.0,4.0,17.7,46.0,4300.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
52,608902,56.0,90.0,176.0,309.0,13.3,124.0,6.5,3.1,9.0,5400.0,2.1,4.0,1.0,normal,abnormal,present,notpresent,yes,yes,no,poor,yes,yes,ckd
53,261137,35.0,60.0,105.0,39.0,0.5,135.0,3.9,14.7,43.0,5800.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
54,721270,58.0,70.0,102.0,48.0,1.2,139.0,4.3,15.0,40.0,8100.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
56,980291,62.0,70.0,122.0,42.0,1.7,136.0,4.7,12.6,39.0,7900.0,3.9,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
64,418316,62.0,80.0,78.0,45.0,0.6,138.0,3.5,16.1,50.0,5400.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
65,750284,52.0,90.0,224.0,166.0,5.6,133.0,47.0,8.1,23.0,5000.0,2.9,4.0,3.0,normal,abnormal,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
66,524004,30.0,80.0,82.0,42.0,0.7,146.0,5.0,14.9,45.0,9400.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
67,268609,56.0,80.0,139.0,15.0,1.2,135.0,5.0,14.8,42.0,5600.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
71,328705,39.0,70.0,131.0,46.0,0.6,145.0,5.0,15.6,41.0,9400.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
79,283427,55.0,80.0,140.0,49.0,0.5,150.0,4.9,15.7,47.0,6700.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
80,490253,43.0,80.0,81.0,46.0,0.6,135.0,4.9,13.9,48.0,6900.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
82,991031,30.0,80.0,89.0,42.0,0.5,139.0,5.0,16.7,52.0,10200.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
85,379507,17.0,60.0,114.0,50.0,1.0,135.0,4.9,14.2,51.0,7200.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
86,676393,63.0,70.0,113.0,25.0,0.6,146.0,4.9,16.5,52.0,8000.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
89,114717,41.0,80.0,122.0,25.0,0.8,138.0,5.0,17.1,41.0,9100.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
93,534245,45.0,70.0,117.0,52.0,2.2,136.0,3.8,10.0,30.0,19100.0,3.7,2.0,0.0,normal,abnormal,present,notpresent,no,no,no,good,no,no,ckd
94,137148,73.0,100.0,295.0,90.0,5.6,140.0,2.9,9.2,30.0,7000.0,3.2,3.0,2.0,abnormal,abnormal,present,notpresent,yes,yes,yes,poor,no,no,ckd
96,750155,46.0,60.0,123.0,46.0,1.0,135.0,5.0,15.7,50.0,6300.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
103,203466,22.0,60.0,97.0,18.0,1.2,138.0,4.3,13.5,42.0,7900.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
106,484175,53.0,90.0,70.0,107.0,7.2,114.0,3.7,9.5,29.0,12100.0,3.7,2.0,0.0,abnormal,abnormal,present,notpresent,yes,yes,no,poor,no,yes,ckd
110,228849,58.0,80.0,100.0,50.0,1.2,140.0,3.5,14.0,50.0,6700.0,6.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
113,754973,39.0,60.0,86.0,37.0,0.6,150.0,5.0,13.6,51.0,5800.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
122,235579,46.0,60.0,102.0,27.0,0.7,142.0,4.9,13.2,44.0,11000.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
124,614376,57.0,80.0,119.0,17.0,1.2,135.0,4.7,15.4,42.0,6200.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
128,125587,37.0,60.0,109.0,47.0,1.1,141.0,4.9,15.0,48.0,7000.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
131,647552,61.0,70.0,120.0,29.0,0.7,137.0,3.5,17.4,52.0,7000.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
134,602404,55.0,90.0,273.0,235.0,14.2,132.0,3.4,8.3,22.0,14600.0,2.9,2.0,1.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
136,514721,56.0,90.0,129.0,107.0,6.7,131.0,4.8,9.1,29.0,6400.0,3.4,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,no,no,good,no,no,ckd
142,499228,32.0,70.0,100.0,29.0,1.1,142.0,4.5,14.3,43.0,6700.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
143,459229,57.0,80.0,133.0,48.0,1.2,147.0,4.3,14.8,46.0,6600.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
145,781942,47.0,60.0,137.0,17.0,0.5,150.0,3.5,13.6,44.0,7900.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
146,617948,34.0,70.0,87.0,38.0,0.5,144.0,4.8,17.1,47.0,7400.0,6.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
148,687021,52.0,80.0,99.0,25.0,0.8,135.0,3.7,15.0,52.0,6300.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
150,428486,73.0,70.0,70.0,32.0,0.9,125.0,4.0,10.0,29.0,18900.0,3.5,0.0,0.0,normal,normal,notpresent,notpresent,yes,yes,no,good,yes,no,ckd
151,734698,59.0,50.0,241.0,191.0,12.0,114.0,2.9,9.6,31.0,15700.0,3.8,3.0,0.0,normal,abnormal,notpresent,notpresent,no,yes,no,good,yes,no,ckd
152,481293,60.0,60.0,288.0,36.0,1.7,130.0,3.0,7.9,25.0,15200.0,3.0,3.0,1.0,normal,abnormal,present,notpresent,yes,no,no,poor,no,yes,ckd
154,843449,30.0,80.0,131.0,38.0,1.0,147.0,3.8,14.1,45.0,9400.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
159,129654,52.0,80.0,125.0,22.0,1.2,139.0,4.6,16.5,43.0,4700.0,4.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
162,411659,32.0,60.0,102.0,17.0,0.4,147.0,4.7,14.6,41.0,6800.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
165,707555,44.0,60.0,96.0,33.0,0.9,147.0,4.5,16.9,41.0,7200.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
169,746487,59.0,100.0,252.0,40.0,3.2,137.0,4.7,11.2,30.0,26400.0,3.9,4.0,2.0,normal,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
170,901528,73.0,80.0,118.0,44.0,0.7,137.0,3.5,14.8,45.0,9300.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
171,667326,35.0,80.0,104.0,31.0,1.2,135.0,5.0,16.1,45.0,4300.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
173,853426,41.0,70.0,125.0,38.0,0.6,140.0,5.0,16.8,41.0,6300.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
177,615697,6.0,60.0,94.0,67.0,1.0,135.0,4.9,9.9,30.0,16700.0,4.8,4.0,0.0,abnormal,abnormal,notpresent,present,no,no,no,poor,no,no,ckd
178,769512,38.0,60.0,91.0,36.0,0.7,135.0,3.7,14.0,46.0,9100.0,5.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
181,337834,48.0,70.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9,4.0,0.0,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd
182,285690,45.0,80.0,82.0,49.0,0.6,147.0,4.4,15.9,46.0,9100.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
190,654306,41.0,80.0,112.0,48.0,0.7,140.0,5.0,17.0,52.0,7200.0,5.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
193,354223,64.0,70.0,97.0,27.0,0.7,145.0,4.8,13.8,49.0,6400.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
194,995177,69.0,70.0,214.0,96.0,6.3,120.0,3.9,9.4,28.0,11500.0,3.3,4.0,3.0,normal,abnormal,present,present,yes,yes,yes,good,yes,yes,ckd
195,415906,60.0,80.0,131.0,10.0,0.5,146.0,5.0,14.5,41.0,10700.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
196,881763,42.0,70.0,75.0,31.0,1.2,141.0,3.5,16.5,54.0,7800.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
201,330559,34.0,60.0,91.0,49.0,1.2,135.0,4.5,13.5,48.0,8600.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
203,923613,64.0,60.0,239.0,58.0,4.3,137.0,5.4,9.5,29.0,7500.0,3.4,4.0,1.0,abnormal,abnormal,notpresent,present,yes,yes,no,poor,yes,no,ckd
204,102677,59.0,70.0,76.0,186.0,15.0,135.0,7.6,7.1,22.0,3800.0,2.1,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,no,no,poor,yes,yes,ckd
205,471614,52.0,80.0,128.0,30.0,1.2,140.0,4.5,15.2,52.0,4300.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
206,731540,63.0,70.0,130.0,37.0,0.9,150.0,5.0,13.4,41.0,7300.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
208,572140,55.0,80.0,104.0,28.0,0.9,142.0,4.8,17.3,52.0,8200.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
209,273038,47.0,60.0,117.0,22.0,1.2,138.0,3.5,13.0,45.0,5200.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
210,784295,29.0,80.0,70.0,16.0,0.7,138.0,3.5,13.7,54.0,5400.0,5.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
217,924216,65.0,60.0,109.0,39.0,1.0,144.0,3.5,13.9,48.0,9600.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
222,397388,63.0,100.0,280.0,35.0,3.2,143.0,3.5,13.0,40.0,9800.0,4.2,2.0,2.0,normal,normal,notpresent,present,yes,no,yes,good,no,no,ckd
226,809452,66.0,70.0,94.0,19.0,0.7,135.0,3.9,16.0,41.0,5300.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
229,780219,70.0,100.0,118.0,125.0,5.3,136.0,4.9,12.0,37.0,8400.0,8.0,4.0,0.0,normal,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
230,696591,46.0,70.0,100.0,47.0,0.5,142.0,3.5,16.4,43.0,5700.0,6.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
231,996076,57.0,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,10400.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
233,489160,28.0,60.0,79.0,50.0,0.5,145.0,5.0,17.6,51.0,6500.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
234,636769,50.0,90.0,128.0,208.0,9.2,134.0,4.8,8.2,22.0,16300.0,2.7,2.0,0.0,normal,abnormal,present,present,no,no,no,poor,yes,yes,ckd
235,834066,55.0,80.0,133.0,17.0,1.2,135.0,4.8,13.2,41.0,6800.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
240,438182,73.0,80.0,253.0,142.0,4.6,138.0,5.8,10.5,33.0,7200.0,4.3,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,good,no,no,ckd
242,250046,56.0,60.0,132.0,18.0,1.1,147.0,4.7,13.7,45.0,7500.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
245,234626,24.0,70.0,140.0,23.0,0.6,140.0,4.7,16.3,48.0,5800.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
246,390779,48.0,80.0,122.0,33.0,0.9,146.0,3.9,13.9,48.0,9500.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
249,118596,74.0,60.0,88.0,50.0,0.6,147.0,3.7,17.2,53.0,6000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
250,955830,55.0,80.0,214.0,73.0,3.9,137.0,4.9,10.9,34.0,7400.0,3.7,3.0,1.0,normal,abnormal,present,present,yes,yes,no,good,yes,no,ckd
253,746768,25.0,70.0,88.0,42.0,0.5,136.0,3.5,13.3,48.0,7000.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
254,674446,55.0,80.0,130.0,50.0,1.2,147.0,5.0,15.5,41.0,9100.0,6.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
256,918330,60.0,80.0,81.0,15.0,0.5,141.0,3.6,15.0,46.0,10500.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
260,499221,30.0,80.0,96.0,25.0,0.5,144.0,4.8,13.8,42.0,9000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
261,828592,71.0,70.0,219.0,82.0,3.6,133.0,4.4,10.4,33.0,5600.0,3.6,3.0,0.0,normal,abnormal,present,present,yes,yes,yes,good,no,no,ckd
262,843362,71.0,60.0,118.0,125.0,5.3,136.0,4.9,11.4,35.0,15200.0,4.3,4.0,0.0,normal,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
263,634224,75.0,70.0,107.0,48.0,0.8,144.0,3.5,13.6,46.0,10300.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
265,482105,44.0,60.0,95.0,46.0,0.5,138.0,4.2,15.0,50.0,7700.0,6.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
268,670655,80.0,80.0,119.0,46.0,0.7,141.0,4.9,13.9,49.0,5100.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
269,131563,29.0,80.0,83.0,49.0,0.9,139.0,3.3,17.5,40.0,9900.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
271,923398,51.0,80.0,94.0,15.0,1.2,144.0,3.7,15.5,46.0,9500.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
273,604045,30.0,60.0,120.0,31.0,0.8,150.0,4.6,13.4,44.0,10700.0,5.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
274,551175,47.0,80.0,124.0,44.0,1.0,140.0,4.9,14.9,41.0,7000.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
282,963946,50.0,80.0,137.0,46.0,0.8,139.0,5.0,14.1,45.0,9500.0,4.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
284,297893,68.0,80.0,157.0,90.0,4.1,130.0,6.4,5.6,16.0,11000.0,2.6,3.0,2.0,normal,abnormal,present,present,yes,yes,yes,poor,yes,no,ckd
286,153227,60.0,90.0,490.0,95.0,2.7,131.0,3.8,11.5,35.0,12000.0,4.5,3.0,5.0,abnormal,normal,notpresent,present,yes,yes,no,good,no,no,ckd
288,621332,59.0,80.0,303.0,35.0,1.3,122.0,3.5,10.4,35.0,10900.0,4.3,1.0,0.0,abnormal,normal,notpresent,notpresent,no,yes,no,poor,no,no,ckd
292,322882,33.0,80.0,128.0,38.0,0.6,135.0,3.9,13.1,45.0,6200.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
295,899916,83.0,70.0,102.0,60.0,2.6,115.0,5.7,8.7,26.0,12800.0,3.1,3.0,0.0,normal,normal,notpresent,notpresent,yes,no,no,poor,no,yes,ckd
296,585932,25.0,80.0,121.0,19.0,1.2,142.0,4.9,15.0,48.0,6900.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
299,871127,45.0,80.0,117.0,46.0,1.2,137.0,5.0,16.2,45.0,8600.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
300,546225,46.0,60.0,163.0,92.0,3.3,141.0,4.0,9.8,28.0,14600.0,3.2,1.0,0.0,normal,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
302,433613,50.0,80.0,97.0,40.0,0.6,150.0,4.5,14.2,48.0,10500.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
306,566924,49.0,100.0,129.0,158.0,11.8,122.0,3.2,8.1,24.0,9600.0,3.5,3.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
307,532520,60.0,90.0,105.0,53.0,2.3,136.0,5.2,11.1,33.0,10500.0,4.1,2.0,0.0,abnormal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
311,180660,51.0,60.0,99.0,38.0,0.8,135.0,3.7,13.0,49.0,8300.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
320,343710,61.0,80.0,173.0,148.0,3.9,135.0,5.2,7.7,24.0,9200.0,3.2,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,poor,yes,yes,ckd
321,173519,66.0,70.0,107.0,16.0,1.1,140.0,3.6,13.6,42.0,11000.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
328,994377,71.0,70.0,81.0,18.0,0.8,145.0,5.0,14.7,44.0,9800.0,6.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
330,345689,15.0,80.0,93.0,17.0,0.9,136.0,3.9,16.7,50.0,6200.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
331,197452,56.0,70.0,210.0,26.0,1.7,136.0,3.8,16.1,52.0,12500.0,5.6,4.0,1.0,abnormal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
332,873195,44.0,70.0,92.0,40.0,0.9,141.0,4.9,14.0,52.0,7500.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
333,436056,12.0,80.0,100.0,26.0,0.6,137.0,4.4,15.8,49.0,6600.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
334,460315,23.0,80.0,70.0,36.0,1.0,150.0,4.6,17.0,52.0,9800.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
335,719916,40.0,80.0,140.0,10.0,1.2,135.0,5.0,15.0,48.0,10400.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
337,968221,55.0,80.0,118.0,18.0,0.9,135.0,3.6,15.5,43.0,7200.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
338,310480,63.0,70.0,380.0,60.0,2.7,131.0,4.2,10.8,32.0,4500.0,3.8,3.0,0.0,abnormal,abnormal,present,notpresent,yes,yes,no,poor,yes,no,ckd
339,160040,48.0,110.0,106.0,215.0,15.2,120.0,5.7,8.6,26.0,5000.0,2.5,3.0,0.0,abnormal,normal,present,notpresent,yes,no,yes,good,no,yes,ckd
341,608641,43.0,80.0,130.0,30.0,1.1,143.0,5.0,15.9,45.0,7800.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
342,712694,60.0,60.0,134.0,45.0,0.5,139.0,4.8,14.2,48.0,10700.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
346,129053,48.0,80.0,133.0,139.0,8.5,132.0,5.5,10.3,36.0,6200.0,4.0,4.0,0.0,abnormal,abnormal,notpresent,present,no,yes,no,good,yes,no,ckd
347,789906,69.0,70.0,83.0,42.0,1.2,139.0,3.7,16.2,50.0,9300.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
348,201768,58.0,70.0,88.0,16.0,1.1,147.0,3.5,16.4,53.0,9100.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
349,118191,42.0,70.0,93.0,32.0,0.9,143.0,4.7,16.6,43.0,7100.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
350,883369,59.0,70.0,130.0,39.0,0.7,147.0,4.7,13.5,46.0,6700.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
351,234299,48.0,80.0,95.0,163.0,7.7,136.0,3.8,9.8,32.0,6900.0,3.4,4.0,0.0,normal,abnormal,notpresent,notpresent,yes,no,no,good,no,yes,ckd
354,720366,70.0,80.0,74.0,41.0,0.5,143.0,4.5,15.1,48.0,9700.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
357,553648,33.0,80.0,100.0,37.0,1.2,142.0,4.0,16.9,52.0,6700.0,6.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
360,124304,69.0,70.0,264.0,87.0,2.7,130.0,4.0,12.5,37.0,9600.0,4.1,3.0,4.0,normal,abnormal,notpresent,notpresent,yes,yes,yes,good,yes,no,ckd
366,296998,62.0,80.0,132.0,34.0,0.8,147.0,3.5,17.8,44.0,4700.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd

## Part 3.4: Sort the dataset according to the Labels

In [8]:
# Sort the dataset according to the values in 'Target' column. Make sure reset the indices after sorting
both_df = both_df.sort_values(by="Target", ignore_index=True)
# Print the dataset
display(both_df)

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc,al,su,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,Target
0,474407,21.0,90.0,107.0,40.0,1.7,125.0,3.5,8.3,23.0,12400.0,3.9,4.0,0.0,normal,abnormal,present,present,no,no,no,good,no,yes,ckd
1,137148,73.0,100.0,295.0,90.0,5.6,140.0,2.9,9.2,30.0,7000.0,3.2,3.0,2.0,abnormal,abnormal,present,notpresent,yes,yes,yes,poor,no,no,ckd
2,484175,53.0,90.0,70.0,107.0,7.2,114.0,3.7,9.5,29.0,12100.0,3.7,2.0,0.0,abnormal,abnormal,present,notpresent,yes,yes,no,poor,no,yes,ckd
3,343710,61.0,80.0,173.0,148.0,3.9,135.0,5.2,7.7,24.0,9200.0,3.2,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,poor,yes,yes,ckd
4,532520,60.0,90.0,105.0,53.0,2.3,136.0,5.2,11.1,33.0,10500.0,4.1,2.0,0.0,abnormal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
5,566924,49.0,100.0,129.0,158.0,11.8,122.0,3.2,8.1,24.0,9600.0,3.5,3.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
6,546225,46.0,60.0,163.0,92.0,3.3,141.0,4.0,9.8,28.0,14600.0,3.2,1.0,0.0,normal,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
7,602404,55.0,90.0,273.0,235.0,14.2,132.0,3.4,8.3,22.0,14600.0,2.9,2.0,1.0,abnormal,abnormal,notpresent,notpresent,yes,yes,no,poor,yes,yes,ckd
8,514721,56.0,90.0,129.0,107.0,6.7,131.0,4.8,9.1,29.0,6400.0,3.4,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,no,no,good,no,no,ckd
9,899916,83.0,70.0,102.0,60.0,2.6,115.0,5.7,8.7,26.0,12800.0,3.1,3.0,0.0,normal,normal,notpresent,notpresent,yes,no,no,poor,no,yes,ckd
10,621332,59.0,80.0,303.0,35.0,1.3,122.0,3.5,10.4,35.0,10900.0,4.3,1.0,0.0,abnormal,normal,notpresent,notpresent,no,yes,no,poor,no,no,ckd
11,428486,73.0,70.0,70.0,32.0,0.9,125.0,4.0,10.0,29.0,18900.0,3.5,0.0,0.0,normal,normal,notpresent,notpresent,yes,yes,no,good,yes,no,ckd
12,734698,59.0,50.0,241.0,191.0,12.0,114.0,2.9,9.6,31.0,15700.0,3.8,3.0,0.0,normal,abnormal,notpresent,notpresent,no,yes,no,good,yes,no,ckd
13,481293,60.0,60.0,288.0,36.0,1.7,130.0,3.0,7.9,25.0,15200.0,3.0,3.0,1.0,normal,abnormal,present,notpresent,yes,no,no,poor,no,yes,ckd
14,153227,60.0,90.0,490.0,95.0,2.7,131.0,3.8,11.5,35.0,12000.0,4.5,3.0,5.0,abnormal,normal,notpresent,present,yes,yes,no,good,no,no,ckd
15,297893,68.0,80.0,157.0,90.0,4.1,130.0,6.4,5.6,16.0,11000.0,2.6,3.0,2.0,normal,abnormal,present,present,yes,yes,yes,poor,yes,no,ckd
16,746487,59.0,100.0,252.0,40.0,3.2,137.0,4.7,11.2,30.0,26400.0,3.9,4.0,2.0,normal,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
17,615697,6.0,60.0,94.0,67.0,1.0,135.0,4.9,9.9,30.0,16700.0,4.8,4.0,0.0,abnormal,abnormal,notpresent,present,no,no,no,poor,no,no,ckd
18,337834,48.0,70.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9,4.0,0.0,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd
19,843362,71.0,60.0,118.0,125.0,5.3,136.0,4.9,11.4,35.0,15200.0,4.3,4.0,0.0,normal,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
20,995177,69.0,70.0,214.0,96.0,6.3,120.0,3.9,9.4,28.0,11500.0,3.3,4.0,3.0,normal,abnormal,present,present,yes,yes,yes,good,yes,yes,ckd
21,828592,71.0,70.0,219.0,82.0,3.6,133.0,4.4,10.4,33.0,5600.0,3.6,3.0,0.0,normal,abnormal,present,present,yes,yes,yes,good,no,no,ckd
22,923613,64.0,60.0,239.0,58.0,4.3,137.0,5.4,9.5,29.0,7500.0,3.4,4.0,1.0,abnormal,abnormal,notpresent,present,yes,yes,no,poor,yes,no,ckd
23,102677,59.0,70.0,76.0,186.0,15.0,135.0,7.6,7.1,22.0,3800.0,2.1,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,no,no,poor,yes,yes,ckd
24,955830,55.0,80.0,214.0,73.0,3.9,137.0,4.9,10.9,34.0,7400.0,3.7,3.0,1.0,normal,abnormal,present,present,yes,yes,no,good,yes,no,ckd
25,397388,63.0,100.0,280.0,35.0,3.2,143.0,3.5,13.0,40.0,9800.0,4.2,2.0,2.0,normal,normal,notpresent,present,yes,no,yes,good,no,no,ckd
26,780219,70.0,100.0,118.0,125.0,5.3,136.0,4.9,12.0,37.0,8400.0,8.0,4.0,0.0,normal,normal,notpresent,notpresent,yes,no,no,good,no,no,ckd
27,438182,73.0,80.0,253.0,142.0,4.6,138.0,5.8,10.5,33.0,7200.0,4.3,2.0,0.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,good,no,no,ckd
28,534245,45.0,70.0,117.0,52.0,2.2,136.0,3.8,10.0,30.0,19100.0,3.7,2.0,0.0,normal,abnormal,present,notpresent,no,no,no,good,no,no,ckd
29,197452,56.0,70.0,210.0,26.0,1.7,136.0,3.8,16.1,52.0,12500.0,5.6,4.0,1.0,abnormal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
30,636769,50.0,90.0,128.0,208.0,9.2,134.0,4.8,8.2,22.0,16300.0,2.7,2.0,0.0,normal,abnormal,present,present,no,no,no,poor,yes,yes,ckd
31,129053,48.0,80.0,133.0,139.0,8.5,132.0,5.5,10.3,36.0,6200.0,4.0,4.0,0.0,abnormal,abnormal,notpresent,present,no,yes,no,good,yes,no,ckd
32,475200,64.0,100.0,163.0,54.0,7.2,140.0,4.6,7.9,26.0,7500.0,3.4,4.0,2.0,abnormal,abnormal,notpresent,present,yes,yes,no,good,yes,no,ckd
33,124304,69.0,70.0,264.0,87.0,2.7,130.0,4.0,12.5,37.0,9600.0,4.1,3.0,4.0,normal,abnormal,notpresent,notpresent,yes,yes,yes,good,yes,no,ckd
34,608902,56.0,90.0,176.0,309.0,13.3,124.0,6.5,3.1,9.0,5400.0,2.1,4.0,1.0,normal,abnormal,present,notpresent,yes,yes,no,poor,yes,yes,ckd
35,234299,48.0,80.0,95.0,163.0,7.7,136.0,3.8,9.8,32.0,6900.0,3.4,4.0,0.0,normal,abnormal,notpresent,notpresent,yes,no,no,good,no,yes,ckd
36,980291,62.0,70.0,122.0,42.0,1.7,136.0,4.7,12.6,39.0,7900.0,3.9,3.0,0.0,normal,abnormal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
37,310480,63.0,70.0,380.0,60.0,2.7,131.0,4.2,10.8,32.0,4500.0,3.8,3.0,0.0,abnormal,abnormal,present,notpresent,yes,yes,no,poor,yes,no,ckd
38,353025,40.0,70.0,253.0,150.0,11.9,132.0,5.6,10.9,31.0,8800.0,3.4,3.0,4.0,normal,normal,notpresent,notpresent,yes,yes,no,poor,yes,no,ckd
39,160040,48.0,110.0,106.0,215.0,15.2,120.0,5.7,8.6,26.0,5000.0,2.5,3.0,0.0,abnormal,normal,present,notpresent,yes,no,yes,good,no,yes,ckd
40,750284,52.0,90.0,224.0,166.0,5.6,133.0,47.0,8.1,23.0,5000.0,2.9,4.0,3.0,normal,abnormal,notpresent,notpresent,yes,yes,no,good,no,yes,ckd
41,349892,59.0,70.0,424.0,55.0,1.7,138.0,4.5,12.6,37.0,10200.0,4.1,1.0,3.0,abnormal,abnormal,notpresent,notpresent,yes,yes,yes,good,no,no,ckd
42,499221,30.0,80.0,96.0,25.0,0.5,144.0,4.8,13.8,42.0,9000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
43,436056,12.0,80.0,100.0,26.0,0.6,137.0,4.4,15.8,49.0,6600.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
44,296998,62.0,80.0,132.0,34.0,0.8,147.0,3.5,17.8,44.0,4700.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
45,634224,75.0,70.0,107.0,48.0,0.8,144.0,3.5,13.6,46.0,10300.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
46,482105,44.0,60.0,95.0,46.0,0.5,138.0,4.2,15.0,50.0,7700.0,6.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
47,918330,60.0,80.0,81.0,15.0,0.5,141.0,3.6,15.0,46.0,10500.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
48,155117,68.0,60.0,125.0,41.0,1.1,139.0,3.8,17.4,50.0,6700.0,6.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
49,674446,55.0,80.0,130.0,50.0,1.2,147.0,5.0,15.5,41.0,9100.0,6.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
50,530138,23.0,80.0,111.0,34.0,1.1,145.0,4.0,14.3,41.0,7200.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
51,670655,80.0,80.0,119.0,46.0,0.7,141.0,4.9,13.9,49.0,5100.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
52,746768,25.0,70.0,88.0,42.0,0.5,136.0,3.5,13.3,48.0,7000.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
53,118596,74.0,60.0,88.0,50.0,0.6,147.0,3.7,17.2,53.0,6000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
54,390779,48.0,80.0,122.0,33.0,0.9,146.0,3.9,13.9,48.0,9500.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
55,234626,24.0,70.0,140.0,23.0,0.6,140.0,4.7,16.3,48.0,5800.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
56,486397,20.0,70.0,123.0,44.0,1.0,135.0,3.8,14.6,44.0,5500.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
57,250046,56.0,60.0,132.0,18.0,1.1,147.0,4.7,13.7,45.0,7500.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
58,462892,36.0,80.0,85.0,16.0,1.1,142.0,4.1,15.6,44.0,5800.0,6.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
59,155872,59.0,60.0,113.0,23.0,1.1,139.0,3.5,15.3,54.0,6500.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
60,553648,33.0,80.0,100.0,37.0,1.2,142.0,4.0,16.9,52.0,6700.0,6.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
61,720366,70.0,80.0,74.0,41.0,0.5,143.0,4.5,15.1,48.0,9700.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
62,923398,51.0,80.0,94.0,15.0,1.2,144.0,3.7,15.5,46.0,9500.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
63,345689,15.0,80.0,93.0,17.0,0.9,136.0,3.9,16.7,50.0,6200.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
64,460315,23.0,80.0,70.0,36.0,1.0,150.0,4.6,17.0,52.0,9800.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
65,719916,40.0,80.0,140.0,10.0,1.2,135.0,5.0,15.0,48.0,10400.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
66,994377,71.0,70.0,81.0,18.0,0.8,145.0,5.0,14.7,44.0,9800.0,6.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
67,173519,66.0,70.0,107.0,16.0,1.1,140.0,3.6,13.6,42.0,11000.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
68,968221,55.0,80.0,118.0,18.0,0.9,135.0,3.6,15.5,43.0,7200.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
69,180660,51.0,60.0,99.0,38.0,0.8,135.0,3.7,13.0,49.0,8300.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
70,834066,55.0,80.0,133.0,17.0,1.2,135.0,4.8,13.2,41.0,6800.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
71,608641,43.0,80.0,130.0,30.0,1.1,143.0,5.0,15.9,45.0,7800.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
72,712694,60.0,60.0,134.0,45.0,0.5,139.0,4.8,14.2,48.0,10700.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
73,871127,45.0,80.0,117.0,46.0,1.2,137.0,5.0,16.2,45.0,8600.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
74,585932,25.0,80.0,121.0,19.0,1.2,142.0,4.9,15.0,48.0,6900.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
75,322882,33.0,80.0,128.0,38.0,0.6,135.0,3.9,13.1,45.0,6200.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
76,789906,69.0,70.0,83.0,42.0,1.2,139.0,3.7,16.2,50.0,9300.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
77,201768,58.0,70.0,88.0,16.0,1.1,147.0,3.5,16.4,53.0,9100.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
78,118191,42.0,70.0,93.0,32.0,0.9,143.0,4.7,16.6,43.0,7100.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
79,883369,59.0,70.0,130.0,39.0,0.7,147.0,4.7,13.5,46.0,6700.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
80,963946,50.0,80.0,137.0,46.0,0.8,139.0,5.0,14.1,45.0,9500.0,4.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
81,551175,47.0,80.0,124.0,44.0,1.0,140.0,4.9,14.9,41.0,7000.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
82,873195,44.0,70.0,92.0,40.0,0.9,141.0,4.9,14.0,52.0,7500.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
83,604045,30.0,60.0,120.0,31.0,0.8,150.0,4.6,13.4,44.0,10700.0,5.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
84,131563,29.0,80.0,83.0,49.0,0.9,139.0,3.3,17.5,40.0,9900.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
85,433613,50.0,80.0,97.0,40.0,0.6,150.0,4.5,14.2,48.0,10500.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
86,203694,38.0,80.0,99.0,19.0,0.5,147.0,3.5,13.6,44.0,7300.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
87,996076,57.0,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,10400.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
88,750155,46.0,60.0,123.0,46.0,1.0,135.0,5.0,15.7,50.0,6300.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
89,114717,41.0,80.0,122.0,25.0,0.8,138.0,5.0,17.1,41.0,9100.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
90,676393,63.0,70.0,113.0,25.0,0.6,146.0,4.9,16.5,52.0,8000.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
91,379507,17.0,60.0,114.0,50.0,1.0,135.0,4.9,14.2,51.0,7200.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
92,991031,30.0,80.0,89.0,42.0,0.5,139.0,5.0,16.7,52.0,10200.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
93,490253,43.0,80.0,81.0,46.0,0.6,135.0,4.9,13.9,48.0,6900.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
94,283427,55.0,80.0,140.0,49.0,0.5,150.0,4.9,15.7,47.0,6700.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
95,328705,39.0,70.0,131.0,46.0,0.6,145.0,5.0,15.6,41.0,9400.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
96,268609,56.0,80.0,139.0,15.0,1.2,135.0,5.0,14.8,42.0,5600.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
97,524004,30.0,80.0,82.0,42.0,0.7,146.0,5.0,14.9,45.0,9400.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
98,418316,62.0,80.0,78.0,45.0,0.6,138.0,3.5,16.1,50.0,5400.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
99,721270,58.0,70.0,102.0,48.0,1.2,139.0,4.3,15.0,40.0,8100.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
100,261137,35.0,60.0,105.0,39.0,0.5,135.0,3.9,14.7,43.0,5800.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
101,643841,23.0,80.0,99.0,46.0,1.2,142.0,4.0,17.7,46.0,4300.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
102,557347,34.0,80.0,121.0,27.0,1.2,144.0,3.9,13.6,52.0,9200.0,6.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
103,441170,79.0,80.0,111.0,44.0,1.2,146.0,3.6,16.3,40.0,8000.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
104,947246,73.0,60.0,127.0,48.0,0.5,150.0,3.5,15.1,52.0,11000.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
105,534003,42.0,80.0,132.0,24.0,0.7,140.0,4.1,14.4,50.0,5000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
106,431871,57.0,60.0,132.0,18.0,1.1,150.0,4.7,15.4,42.0,11000.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
107,976875,33.0,60.0,80.0,25.0,0.9,146.0,3.5,14.1,48.0,7800.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
108,201677,33.0,80.0,89.0,19.0,1.1,144.0,5.0,15.0,40.0,10300.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
109,965166,48.0,80.0,75.0,22.0,0.8,137.0,5.0,16.8,51.0,6000.0,6.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
110,460465,47.0,60.0,109.0,25.0,1.1,141.0,4.7,15.8,41.0,8300.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
111,546010,49.0,80.0,122.0,32.0,1.2,139.0,3.9,17.0,41.0,5600.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
112,741276,23.0,60.0,95.0,24.0,0.8,145.0,5.0,15.0,52.0,6300.0,4.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
113,630177,58.0,80.0,131.0,18.0,1.1,141.0,3.5,15.8,53.0,6800.0,6.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
114,109053,64.0,60.0,106.0,27.0,0.7,150.0,3.3,14.4,42.0,8100.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
115,421471,37.0,60.0,111.0,35.0,0.8,135.0,4.1,16.2,50.0,5500.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
116,938027,43.0,60.0,108.0,25.0,1.0,144.0,5.0,17.8,43.0,7200.0,5.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
117,203466,22.0,60.0,97.0,18.0,1.2,138.0,4.3,13.5,42.0,7900.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
118,228849,58.0,80.0,100.0,50.0,1.2,140.0,3.5,14.0,50.0,6700.0,6.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
119,754973,39.0,60.0,86.0,37.0,0.6,150.0,5.0,13.6,51.0,5800.0,4.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
120,235579,46.0,60.0,102.0,27.0,0.7,142.0,4.9,13.2,44.0,11000.0,5.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
121,696591,46.0,70.0,100.0,47.0,0.5,142.0,3.5,16.4,43.0,5700.0,6.5,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
122,809452,66.0,70.0,94.0,19.0,0.7,135.0,3.9,16.0,41.0,5300.0,5.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
123,924216,65.0,60.0,109.0,39.0,1.0,144.0,3.5,13.9,48.0,9600.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
124,784295,29.0,80.0,70.0,16.0,0.7,138.0,3.5,13.7,54.0,5400.0,5.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
125,273038,47.0,60.0,117.0,22.0,1.2,138.0,3.5,13.0,45.0,5200.0,5.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
126,168242,48.0,60.0,112.0,44.0,1.2,142.0,4.9,14.5,44.0,9400.0,6.4,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
127,731540,63.0,70.0,130.0,37.0,0.9,150.0,5.0,13.4,41.0,7300.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
128,471614,52.0,80.0,128.0,30.0,1.2,140.0,4.5,15.2,52.0,4300.0,5.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
129,330559,34.0,60.0,91.0,49.0,1.2,135.0,4.5,13.5,48.0,8600.0,4.9,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
130,881763,42.0,70.0,75.0,31.0,1.2,141.0,3.5,16.5,54.0,7800.0,6.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
131,415906,60.0,80.0,131.0,10.0,0.5,146.0,5.0,14.5,41.0,10700.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
132,354223,64.0,70.0,97.0,27.0,0.7,145.0,4.8,13.8,49.0,6400.0,4.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
133,654306,41.0,80.0,112.0,48.0,0.7,140.0,5.0,17.0,52.0,7200.0,5.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
134,285690,45.0,80.0,82.0,49.0,0.6,147.0,4.4,15.9,46.0,9100.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
135,489160,28.0,60.0,79.0,50.0,0.5,145.0,5.0,17.6,51.0,6500.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
136,769512,38.0,60.0,91.0,36.0,0.7,135.0,3.7,14.0,46.0,9100.0,5.8,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
137,667326,35.0,80.0,104.0,31.0,1.2,135.0,5.0,16.1,45.0,4300.0,5.2,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
138,901528,73.0,80.0,118.0,44.0,0.7,137.0,3.5,14.8,45.0,9300.0,4.7,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
139,707555,44.0,60.0,96.0,33.0,0.9,147.0,4.5,16.9,41.0,7200.0,5.0,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
140,411659,32.0,60.0,102.0,17.0,0.4,147.0,4.7,14.6,41.0,6800.0,5.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
141,129654,52.0,80.0,125.0,22.0,1.2,139.0,4.6,16.5,43.0,4700.0,4.6,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
142,843449,30.0,80.0,131.0,38.0,1.0,147.0,3.8,14.1,45.0,9400.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
143,687021,52.0,80.0,99.0,25.0,0.8,135.0,3.7,15.0,52.0,6300.0,5.3,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
144,617948,34.0,70.0,87.0,38.0,0.5,144.0,4.8,17.1,47.0,7400.0,6.1,0.0,0.0,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd

## Part 3.5: Encoding Categorical data

In this step, we identify and process the categorical columns in the sorted dataset. We map each unique value in these columns to separate "dummy" columns.

For example, the column 'rbc' will be transformed into two columns 'rbc_normal' and 'rbc_abnormal'. If a row's value in 'rbc' is 'normal', the 'rbc_normal' column will be set to 1 and 'rbc_abnormal' will be set to 0.


**Note: Find a correct pandas function to do this **

In [9]:
# Write code here
categorical_columns = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'Target']
both_df = pd.get_dummies(both_df, columns=categorical_columns)
# Print the dataset
display(both_df)

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc,al,su,rbc_abnormal,rbc_normal,pc_abnormal,pc_normal,pcc_notpresent,pcc_present,ba_notpresent,ba_present,htn_no,htn_yes,dm_no,dm_yes,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
0,474407,21.0,90.0,107.0,40.0,1.7,125.0,3.5,8.3,23.0,12400.0,3.9,4.0,0.0,False,True,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False,False,True,True,False
1,137148,73.0,100.0,295.0,90.0,5.6,140.0,2.9,9.2,30.0,7000.0,3.2,3.0,2.0,True,False,True,False,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,True,False
2,484175,53.0,90.0,70.0,107.0,7.2,114.0,3.7,9.5,29.0,12100.0,3.7,2.0,0.0,True,False,True,False,False,True,True,False,False,True,False,True,True,False,False,True,True,False,False,True,True,False
3,343710,61.0,80.0,173.0,148.0,3.9,135.0,5.2,7.7,24.0,9200.0,3.2,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,False,True,False,True,False,True,True,False
4,532520,60.0,90.0,105.0,53.0,2.3,136.0,5.2,11.1,33.0,10500.0,4.1,2.0,0.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
5,566924,49.0,100.0,129.0,158.0,11.8,122.0,3.2,8.1,24.0,9600.0,3.5,3.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,True,False,False,True,False,True,False,True,True,False
6,546225,46.0,60.0,163.0,92.0,3.3,141.0,4.0,9.8,28.0,14600.0,3.2,1.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
7,602404,55.0,90.0,273.0,235.0,14.2,132.0,3.4,8.3,22.0,14600.0,2.9,2.0,1.0,True,False,True,False,True,False,True,False,False,True,False,True,True,False,False,True,False,True,False,True,True,False
8,514721,56.0,90.0,129.0,107.0,6.7,131.0,4.8,9.1,29.0,6400.0,3.4,2.0,0.0,True,False,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False
9,899916,83.0,70.0,102.0,60.0,2.6,115.0,5.7,8.7,26.0,12800.0,3.1,3.0,0.0,False,True,False,True,True,False,True,False,False,True,True,False,True,False,False,True,True,False,False,True,True,False
10,621332,59.0,80.0,303.0,35.0,1.3,122.0,3.5,10.4,35.0,10900.0,4.3,1.0,0.0,True,False,False,True,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,True,False
11,428486,73.0,70.0,70.0,32.0,0.9,125.0,4.0,10.0,29.0,18900.0,3.5,0.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,True,False,False,True,True,False,True,False
12,734698,59.0,50.0,241.0,191.0,12.0,114.0,2.9,9.6,31.0,15700.0,3.8,3.0,0.0,False,True,True,False,True,False,True,False,True,False,False,True,True,False,True,False,False,True,True,False,True,False
13,481293,60.0,60.0,288.0,36.0,1.7,130.0,3.0,7.9,25.0,15200.0,3.0,3.0,1.0,False,True,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,False,True,True,False
14,153227,60.0,90.0,490.0,95.0,2.7,131.0,3.8,11.5,35.0,12000.0,4.5,3.0,5.0,True,False,False,True,True,False,False,True,False,True,False,True,True,False,True,False,True,False,True,False,True,False
15,297893,68.0,80.0,157.0,90.0,4.1,130.0,6.4,5.6,16.0,11000.0,2.6,3.0,2.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,False,True,False,True,True,False,True,False
16,746487,59.0,100.0,252.0,40.0,3.2,137.0,4.7,11.2,30.0,26400.0,3.9,4.0,2.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,False,True,False,True,True,False,True,False
17,615697,6.0,60.0,94.0,67.0,1.0,135.0,4.9,9.9,30.0,16700.0,4.8,4.0,0.0,True,False,True,False,True,False,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False
18,337834,48.0,70.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9,4.0,0.0,False,True,True,False,False,True,True,False,False,True,True,False,True,False,False,True,False,True,False,True,True,False
19,843362,71.0,60.0,118.0,125.0,5.3,136.0,4.9,11.4,35.0,15200.0,4.3,4.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,False,True,False,True,True,False,True,False
20,995177,69.0,70.0,214.0,96.0,6.3,120.0,3.9,9.4,28.0,11500.0,3.3,4.0,3.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,False,True,False,True,True,False
21,828592,71.0,70.0,219.0,82.0,3.6,133.0,4.4,10.4,33.0,5600.0,3.6,3.0,0.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,True,False,True,False,True,False
22,923613,64.0,60.0,239.0,58.0,4.3,137.0,5.4,9.5,29.0,7500.0,3.4,4.0,1.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,False,True,True,False,True,False
23,102677,59.0,70.0,76.0,186.0,15.0,135.0,7.6,7.1,22.0,3800.0,2.1,3.0,0.0,False,True,True,False,True,False,True,False,False,True,True,False,True,False,False,True,False,True,False,True,True,False
24,955830,55.0,80.0,214.0,73.0,3.9,137.0,4.9,10.9,34.0,7400.0,3.7,3.0,1.0,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
25,397388,63.0,100.0,280.0,35.0,3.2,143.0,3.5,13.0,40.0,9800.0,4.2,2.0,2.0,False,True,False,True,True,False,False,True,False,True,True,False,False,True,True,False,True,False,True,False,True,False
26,780219,70.0,100.0,118.0,125.0,5.3,136.0,4.9,12.0,37.0,8400.0,8.0,4.0,0.0,False,True,False,True,True,False,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False
27,438182,73.0,80.0,253.0,142.0,4.6,138.0,5.8,10.5,33.0,7200.0,4.3,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,True,False,True,False
28,534245,45.0,70.0,117.0,52.0,2.2,136.0,3.8,10.0,30.0,19100.0,3.7,2.0,0.0,False,True,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
29,197452,56.0,70.0,210.0,26.0,1.7,136.0,3.8,16.1,52.0,12500.0,5.6,4.0,1.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
30,636769,50.0,90.0,128.0,208.0,9.2,134.0,4.8,8.2,22.0,16300.0,2.7,2.0,0.0,False,True,True,False,False,True,False,True,True,False,True,False,True,False,False,True,False,True,False,True,True,False
31,129053,48.0,80.0,133.0,139.0,8.5,132.0,5.5,10.3,36.0,6200.0,4.0,4.0,0.0,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,True,False
32,475200,64.0,100.0,163.0,54.0,7.2,140.0,4.6,7.9,26.0,7500.0,3.4,4.0,2.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
33,124304,69.0,70.0,264.0,87.0,2.7,130.0,4.0,12.5,37.0,9600.0,4.1,3.0,4.0,False,True,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,True,False,True,False
34,608902,56.0,90.0,176.0,309.0,13.3,124.0,6.5,3.1,9.0,5400.0,2.1,4.0,1.0,False,True,True,False,False,True,True,False,False,True,False,True,True,False,False,True,False,True,False,True,True,False
35,234299,48.0,80.0,95.0,163.0,7.7,136.0,3.8,9.8,32.0,6900.0,3.4,4.0,0.0,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,False,True,True,False
36,980291,62.0,70.0,122.0,42.0,1.7,136.0,4.7,12.6,39.0,7900.0,3.9,3.0,0.0,False,True,True,False,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
37,310480,63.0,70.0,380.0,60.0,2.7,131.0,4.2,10.8,32.0,4500.0,3.8,3.0,0.0,True,False,True,False,False,True,True,False,False,True,False,True,True,False,False,True,False,True,True,False,True,False
38,353025,40.0,70.0,253.0,150.0,11.9,132.0,5.6,10.9,31.0,8800.0,3.4,3.0,4.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,False,True,False,True,True,False,True,False
39,160040,48.0,110.0,106.0,215.0,15.2,120.0,5.7,8.6,26.0,5000.0,2.5,3.0,0.0,True,False,False,True,False,True,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False
40,750284,52.0,90.0,224.0,166.0,5.6,133.0,47.0,8.1,23.0,5000.0,2.9,4.0,3.0,False,True,True,False,True,False,True,False,False,True,False,True,True,False,True,False,True,False,False,True,True,False
41,349892,59.0,70.0,424.0,55.0,1.7,138.0,4.5,12.6,37.0,10200.0,4.1,1.0,3.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,True,False,True,False
42,499221,30.0,80.0,96.0,25.0,0.5,144.0,4.8,13.8,42.0,9000.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
43,436056,12.0,80.0,100.0,26.0,0.6,137.0,4.4,15.8,49.0,6600.0,5.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
44,296998,62.0,80.0,132.0,34.0,0.8,147.0,3.5,17.8,44.0,4700.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
45,634224,75.0,70.0,107.0,48.0,0.8,144.0,3.5,13.6,46.0,10300.0,4.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
46,482105,44.0,60.0,95.0,46.0,0.5,138.0,4.2,15.0,50.0,7700.0,6.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
47,918330,60.0,80.0,81.0,15.0,0.5,141.0,3.6,15.0,46.0,10500.0,5.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
48,155117,68.0,60.0,125.0,41.0,1.1,139.0,3.8,17.4,50.0,6700.0,6.1,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
49,674446,55.0,80.0,130.0,50.0,1.2,147.0,5.0,15.5,41.0,9100.0,6.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
50,530138,23.0,80.0,111.0,34.0,1.1,145.0,4.0,14.3,41.0,7200.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
51,670655,80.0,80.0,119.0,46.0,0.7,141.0,4.9,13.9,49.0,5100.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
52,746768,25.0,70.0,88.0,42.0,0.5,136.0,3.5,13.3,48.0,7000.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
53,118596,74.0,60.0,88.0,50.0,0.6,147.0,3.7,17.2,53.0,6000.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
54,390779,48.0,80.0,122.0,33.0,0.9,146.0,3.9,13.9,48.0,9500.0,4.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
55,234626,24.0,70.0,140.0,23.0,0.6,140.0,4.7,16.3,48.0,5800.0,5.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
56,486397,20.0,70.0,123.0,44.0,1.0,135.0,3.8,14.6,44.0,5500.0,4.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
57,250046,56.0,60.0,132.0,18.0,1.1,147.0,4.7,13.7,45.0,7500.0,5.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
58,462892,36.0,80.0,85.0,16.0,1.1,142.0,4.1,15.6,44.0,5800.0,6.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
59,155872,59.0,60.0,113.0,23.0,1.1,139.0,3.5,15.3,54.0,6500.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
60,553648,33.0,80.0,100.0,37.0,1.2,142.0,4.0,16.9,52.0,6700.0,6.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
61,720366,70.0,80.0,74.0,41.0,0.5,143.0,4.5,15.1,48.0,9700.0,5.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
62,923398,51.0,80.0,94.0,15.0,1.2,144.0,3.7,15.5,46.0,9500.0,6.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
63,345689,15.0,80.0,93.0,17.0,0.9,136.0,3.9,16.7,50.0,6200.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
64,460315,23.0,80.0,70.0,36.0,1.0,150.0,4.6,17.0,52.0,9800.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
65,719916,40.0,80.0,140.0,10.0,1.2,135.0,5.0,15.0,48.0,10400.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
66,994377,71.0,70.0,81.0,18.0,0.8,145.0,5.0,14.7,44.0,9800.0,6.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
67,173519,66.0,70.0,107.0,16.0,1.1,140.0,3.6,13.6,42.0,11000.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
68,968221,55.0,80.0,118.0,18.0,0.9,135.0,3.6,15.5,43.0,7200.0,5.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
69,180660,51.0,60.0,99.0,38.0,0.8,135.0,3.7,13.0,49.0,8300.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
70,834066,55.0,80.0,133.0,17.0,1.2,135.0,4.8,13.2,41.0,6800.0,5.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
71,608641,43.0,80.0,130.0,30.0,1.1,143.0,5.0,15.9,45.0,7800.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
72,712694,60.0,60.0,134.0,45.0,0.5,139.0,4.8,14.2,48.0,10700.0,5.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
73,871127,45.0,80.0,117.0,46.0,1.2,137.0,5.0,16.2,45.0,8600.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
74,585932,25.0,80.0,121.0,19.0,1.2,142.0,4.9,15.0,48.0,6900.0,5.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
75,322882,33.0,80.0,128.0,38.0,0.6,135.0,3.9,13.1,45.0,6200.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
76,789906,69.0,70.0,83.0,42.0,1.2,139.0,3.7,16.2,50.0,9300.0,5.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
77,201768,58.0,70.0,88.0,16.0,1.1,147.0,3.5,16.4,53.0,9100.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
78,118191,42.0,70.0,93.0,32.0,0.9,143.0,4.7,16.6,43.0,7100.0,5.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
79,883369,59.0,70.0,130.0,39.0,0.7,147.0,4.7,13.5,46.0,6700.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
80,963946,50.0,80.0,137.0,46.0,0.8,139.0,5.0,14.1,45.0,9500.0,4.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
81,551175,47.0,80.0,124.0,44.0,1.0,140.0,4.9,14.9,41.0,7000.0,5.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
82,873195,44.0,70.0,92.0,40.0,0.9,141.0,4.9,14.0,52.0,7500.0,6.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
83,604045,30.0,60.0,120.0,31.0,0.8,150.0,4.6,13.4,44.0,10700.0,5.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
84,131563,29.0,80.0,83.0,49.0,0.9,139.0,3.3,17.5,40.0,9900.0,4.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
85,433613,50.0,80.0,97.0,40.0,0.6,150.0,4.5,14.2,48.0,10500.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
86,203694,38.0,80.0,99.0,19.0,0.5,147.0,3.5,13.6,44.0,7300.0,6.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
87,996076,57.0,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,10400.0,6.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
88,750155,46.0,60.0,123.0,46.0,1.0,135.0,5.0,15.7,50.0,6300.0,4.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
89,114717,41.0,80.0,122.0,25.0,0.8,138.0,5.0,17.1,41.0,9100.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
90,676393,63.0,70.0,113.0,25.0,0.6,146.0,4.9,16.5,52.0,8000.0,5.1,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
91,379507,17.0,60.0,114.0,50.0,1.0,135.0,4.9,14.2,51.0,7200.0,5.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
92,991031,30.0,80.0,89.0,42.0,0.5,139.0,5.0,16.7,52.0,10200.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
93,490253,43.0,80.0,81.0,46.0,0.6,135.0,4.9,13.9,48.0,6900.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
94,283427,55.0,80.0,140.0,49.0,0.5,150.0,4.9,15.7,47.0,6700.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
95,328705,39.0,70.0,131.0,46.0,0.6,145.0,5.0,15.6,41.0,9400.0,4.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
96,268609,56.0,80.0,139.0,15.0,1.2,135.0,5.0,14.8,42.0,5600.0,5.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
97,524004,30.0,80.0,82.0,42.0,0.7,146.0,5.0,14.9,45.0,9400.0,5.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
98,418316,62.0,80.0,78.0,45.0,0.6,138.0,3.5,16.1,50.0,5400.0,5.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
99,721270,58.0,70.0,102.0,48.0,1.2,139.0,4.3,15.0,40.0,8100.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
100,261137,35.0,60.0,105.0,39.0,0.5,135.0,3.9,14.7,43.0,5800.0,6.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True

In the example we went through above, another solution is to have a single column for the binary variable. In the downstream modeling would this be equivalent? What effect would this have if the categorical variable could take more than 2 values? For example, let's say we have a categorical feature that is "type of condiment" that can take 5 separate values and we are trying to predict the rating of a particular sandwich.

Answer: For a binary categorical variable, having a single column for that variable would be equivalent, because if you only have two values, you can simply assign "True" to one value and "False" to the other - to get the other column, you can just flip the values, so you don't lose any information. If the categorical variable can take more than 2 values, if you try to simplify it to a single binary variable, you lose information, since multiple different values will be grouped together under the "False" label.

## Part 3.6 : Remove Outliers from Numerical Columns

Outliers can disproportionately influence the fit of a regression model, potentially leading to a model that does not generalize well therefore it is important that we remove outliers from the numerical columns of the dataset.

For this dataset, we define an outlier to be 3 times the standard deviation from the mean. Drop these outliers from the dataset

In [10]:
# Remove outliers
numerical_columns = ['age', 'bp', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc']
for col in numerical_columns:
    both_df = both_df[np.abs(stats.zscore(both_df[col])) < 3]
# Print the dataset
both_df = both_df.reset_index(drop=True)
display(both_df)

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc,al,su,rbc_abnormal,rbc_normal,pc_abnormal,pc_normal,pcc_notpresent,pcc_present,ba_notpresent,ba_present,htn_no,htn_yes,dm_no,dm_yes,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
0,474407,21.0,90.0,107.0,40.0,1.7,125.0,3.5,8.3,23.0,12400.0,3.9,4.0,0.0,False,True,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False,False,True,True,False
1,137148,73.0,100.0,295.0,90.0,5.6,140.0,2.9,9.2,30.0,7000.0,3.2,3.0,2.0,True,False,True,False,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,True,False
2,343710,61.0,80.0,173.0,148.0,3.9,135.0,5.2,7.7,24.0,9200.0,3.2,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,False,True,False,True,False,True,True,False
3,532520,60.0,90.0,105.0,53.0,2.3,136.0,5.2,11.1,33.0,10500.0,4.1,2.0,0.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
4,546225,46.0,60.0,163.0,92.0,3.3,141.0,4.0,9.8,28.0,14600.0,3.2,1.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
5,514721,56.0,90.0,129.0,107.0,6.7,131.0,4.8,9.1,29.0,6400.0,3.4,2.0,0.0,True,False,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False
6,621332,59.0,80.0,303.0,35.0,1.3,122.0,3.5,10.4,35.0,10900.0,4.3,1.0,0.0,True,False,False,True,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,True,False
7,481293,60.0,60.0,288.0,36.0,1.7,130.0,3.0,7.9,25.0,15200.0,3.0,3.0,1.0,False,True,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,False,True,True,False
8,615697,6.0,60.0,94.0,67.0,1.0,135.0,4.9,9.9,30.0,16700.0,4.8,4.0,0.0,True,False,True,False,True,False,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False
9,843362,71.0,60.0,118.0,125.0,5.3,136.0,4.9,11.4,35.0,15200.0,4.3,4.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,False,True,False,True,True,False,True,False
10,995177,69.0,70.0,214.0,96.0,6.3,120.0,3.9,9.4,28.0,11500.0,3.3,4.0,3.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,False,True,False,True,True,False
11,828592,71.0,70.0,219.0,82.0,3.6,133.0,4.4,10.4,33.0,5600.0,3.6,3.0,0.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,True,False,True,False,True,False
12,923613,64.0,60.0,239.0,58.0,4.3,137.0,5.4,9.5,29.0,7500.0,3.4,4.0,1.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,False,True,True,False,True,False
13,955830,55.0,80.0,214.0,73.0,3.9,137.0,4.9,10.9,34.0,7400.0,3.7,3.0,1.0,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
14,397388,63.0,100.0,280.0,35.0,3.2,143.0,3.5,13.0,40.0,9800.0,4.2,2.0,2.0,False,True,False,True,True,False,False,True,False,True,True,False,False,True,True,False,True,False,True,False,True,False
15,438182,73.0,80.0,253.0,142.0,4.6,138.0,5.8,10.5,33.0,7200.0,4.3,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,True,False,True,False
16,197452,56.0,70.0,210.0,26.0,1.7,136.0,3.8,16.1,52.0,12500.0,5.6,4.0,1.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
17,129053,48.0,80.0,133.0,139.0,8.5,132.0,5.5,10.3,36.0,6200.0,4.0,4.0,0.0,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,True,False
18,475200,64.0,100.0,163.0,54.0,7.2,140.0,4.6,7.9,26.0,7500.0,3.4,4.0,2.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
19,124304,69.0,70.0,264.0,87.0,2.7,130.0,4.0,12.5,37.0,9600.0,4.1,3.0,4.0,False,True,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,True,False,True,False
20,234299,48.0,80.0,95.0,163.0,7.7,136.0,3.8,9.8,32.0,6900.0,3.4,4.0,0.0,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,False,True,True,False
21,980291,62.0,70.0,122.0,42.0,1.7,136.0,4.7,12.6,39.0,7900.0,3.9,3.0,0.0,False,True,True,False,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
22,499221,30.0,80.0,96.0,25.0,0.5,144.0,4.8,13.8,42.0,9000.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
23,436056,12.0,80.0,100.0,26.0,0.6,137.0,4.4,15.8,49.0,6600.0,5.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
24,296998,62.0,80.0,132.0,34.0,0.8,147.0,3.5,17.8,44.0,4700.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
25,634224,75.0,70.0,107.0,48.0,0.8,144.0,3.5,13.6,46.0,10300.0,4.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
26,482105,44.0,60.0,95.0,46.0,0.5,138.0,4.2,15.0,50.0,7700.0,6.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
27,918330,60.0,80.0,81.0,15.0,0.5,141.0,3.6,15.0,46.0,10500.0,5.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
28,155117,68.0,60.0,125.0,41.0,1.1,139.0,3.8,17.4,50.0,6700.0,6.1,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
29,674446,55.0,80.0,130.0,50.0,1.2,147.0,5.0,15.5,41.0,9100.0,6.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
30,530138,23.0,80.0,111.0,34.0,1.1,145.0,4.0,14.3,41.0,7200.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
31,670655,80.0,80.0,119.0,46.0,0.7,141.0,4.9,13.9,49.0,5100.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
32,746768,25.0,70.0,88.0,42.0,0.5,136.0,3.5,13.3,48.0,7000.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
33,118596,74.0,60.0,88.0,50.0,0.6,147.0,3.7,17.2,53.0,6000.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
34,390779,48.0,80.0,122.0,33.0,0.9,146.0,3.9,13.9,48.0,9500.0,4.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
35,234626,24.0,70.0,140.0,23.0,0.6,140.0,4.7,16.3,48.0,5800.0,5.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
36,486397,20.0,70.0,123.0,44.0,1.0,135.0,3.8,14.6,44.0,5500.0,4.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
37,250046,56.0,60.0,132.0,18.0,1.1,147.0,4.7,13.7,45.0,7500.0,5.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
38,462892,36.0,80.0,85.0,16.0,1.1,142.0,4.1,15.6,44.0,5800.0,6.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
39,155872,59.0,60.0,113.0,23.0,1.1,139.0,3.5,15.3,54.0,6500.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
40,553648,33.0,80.0,100.0,37.0,1.2,142.0,4.0,16.9,52.0,6700.0,6.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
41,720366,70.0,80.0,74.0,41.0,0.5,143.0,4.5,15.1,48.0,9700.0,5.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
42,923398,51.0,80.0,94.0,15.0,1.2,144.0,3.7,15.5,46.0,9500.0,6.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
43,345689,15.0,80.0,93.0,17.0,0.9,136.0,3.9,16.7,50.0,6200.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
44,460315,23.0,80.0,70.0,36.0,1.0,150.0,4.6,17.0,52.0,9800.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
45,719916,40.0,80.0,140.0,10.0,1.2,135.0,5.0,15.0,48.0,10400.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
46,994377,71.0,70.0,81.0,18.0,0.8,145.0,5.0,14.7,44.0,9800.0,6.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
47,173519,66.0,70.0,107.0,16.0,1.1,140.0,3.6,13.6,42.0,11000.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
48,968221,55.0,80.0,118.0,18.0,0.9,135.0,3.6,15.5,43.0,7200.0,5.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
49,180660,51.0,60.0,99.0,38.0,0.8,135.0,3.7,13.0,49.0,8300.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
50,834066,55.0,80.0,133.0,17.0,1.2,135.0,4.8,13.2,41.0,6800.0,5.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
51,608641,43.0,80.0,130.0,30.0,1.1,143.0,5.0,15.9,45.0,7800.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
52,712694,60.0,60.0,134.0,45.0,0.5,139.0,4.8,14.2,48.0,10700.0,5.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
53,871127,45.0,80.0,117.0,46.0,1.2,137.0,5.0,16.2,45.0,8600.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
54,585932,25.0,80.0,121.0,19.0,1.2,142.0,4.9,15.0,48.0,6900.0,5.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
55,322882,33.0,80.0,128.0,38.0,0.6,135.0,3.9,13.1,45.0,6200.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
56,789906,69.0,70.0,83.0,42.0,1.2,139.0,3.7,16.2,50.0,9300.0,5.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
57,201768,58.0,70.0,88.0,16.0,1.1,147.0,3.5,16.4,53.0,9100.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
58,118191,42.0,70.0,93.0,32.0,0.9,143.0,4.7,16.6,43.0,7100.0,5.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
59,883369,59.0,70.0,130.0,39.0,0.7,147.0,4.7,13.5,46.0,6700.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
60,963946,50.0,80.0,137.0,46.0,0.8,139.0,5.0,14.1,45.0,9500.0,4.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
61,551175,47.0,80.0,124.0,44.0,1.0,140.0,4.9,14.9,41.0,7000.0,5.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
62,873195,44.0,70.0,92.0,40.0,0.9,141.0,4.9,14.0,52.0,7500.0,6.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
63,604045,30.0,60.0,120.0,31.0,0.8,150.0,4.6,13.4,44.0,10700.0,5.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
64,131563,29.0,80.0,83.0,49.0,0.9,139.0,3.3,17.5,40.0,9900.0,4.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
65,433613,50.0,80.0,97.0,40.0,0.6,150.0,4.5,14.2,48.0,10500.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
66,203694,38.0,80.0,99.0,19.0,0.5,147.0,3.5,13.6,44.0,7300.0,6.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
67,996076,57.0,60.0,105.0,49.0,1.2,150.0,4.7,15.7,44.0,10400.0,6.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
68,750155,46.0,60.0,123.0,46.0,1.0,135.0,5.0,15.7,50.0,6300.0,4.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
69,114717,41.0,80.0,122.0,25.0,0.8,138.0,5.0,17.1,41.0,9100.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
70,676393,63.0,70.0,113.0,25.0,0.6,146.0,4.9,16.5,52.0,8000.0,5.1,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
71,379507,17.0,60.0,114.0,50.0,1.0,135.0,4.9,14.2,51.0,7200.0,5.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
72,991031,30.0,80.0,89.0,42.0,0.5,139.0,5.0,16.7,52.0,10200.0,5.0,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
73,490253,43.0,80.0,81.0,46.0,0.6,135.0,4.9,13.9,48.0,6900.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
74,283427,55.0,80.0,140.0,49.0,0.5,150.0,4.9,15.7,47.0,6700.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
75,328705,39.0,70.0,131.0,46.0,0.6,145.0,5.0,15.6,41.0,9400.0,4.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
76,268609,56.0,80.0,139.0,15.0,1.2,135.0,5.0,14.8,42.0,5600.0,5.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
77,524004,30.0,80.0,82.0,42.0,0.7,146.0,5.0,14.9,45.0,9400.0,5.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
78,418316,62.0,80.0,78.0,45.0,0.6,138.0,3.5,16.1,50.0,5400.0,5.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
79,721270,58.0,70.0,102.0,48.0,1.2,139.0,4.3,15.0,40.0,8100.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
80,261137,35.0,60.0,105.0,39.0,0.5,135.0,3.9,14.7,43.0,5800.0,6.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
81,643841,23.0,80.0,99.0,46.0,1.2,142.0,4.0,17.7,46.0,4300.0,5.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
82,557347,34.0,80.0,121.0,27.0,1.2,144.0,3.9,13.6,52.0,9200.0,6.3,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
83,441170,79.0,80.0,111.0,44.0,1.2,146.0,3.6,16.3,40.0,8000.0,6.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
84,947246,73.0,60.0,127.0,48.0,0.5,150.0,3.5,15.1,52.0,11000.0,4.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
85,534003,42.0,80.0,132.0,24.0,0.7,140.0,4.1,14.4,50.0,5000.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
86,431871,57.0,60.0,132.0,18.0,1.1,150.0,4.7,15.4,42.0,11000.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
87,976875,33.0,60.0,80.0,25.0,0.9,146.0,3.5,14.1,48.0,7800.0,5.1,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
88,201677,33.0,80.0,89.0,19.0,1.1,144.0,5.0,15.0,40.0,10300.0,4.8,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
89,965166,48.0,80.0,75.0,22.0,0.8,137.0,5.0,16.8,51.0,6000.0,6.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
90,460465,47.0,60.0,109.0,25.0,1.1,141.0,4.7,15.8,41.0,8300.0,5.2,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
91,546010,49.0,80.0,122.0,32.0,1.2,139.0,3.9,17.0,41.0,5600.0,4.9,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
92,741276,23.0,60.0,95.0,24.0,0.8,145.0,5.0,15.0,52.0,6300.0,4.6,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
93,630177,58.0,80.0,131.0,18.0,1.1,141.0,3.5,15.8,53.0,6800.0,6.1,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
94,109053,64.0,60.0,106.0,27.0,0.7,150.0,3.3,14.4,42.0,8100.0,4.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
95,421471,37.0,60.0,111.0,35.0,0.8,135.0,4.1,16.2,50.0,5500.0,5.7,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
96,938027,43.0,60.0,108.0,25.0,1.0,144.0,5.0,17.8,43.0,7200.0,5.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
97,203466,22.0,60.0,97.0,18.0,1.2,138.0,4.3,13.5,42.0,7900.0,6.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
98,228849,58.0,80.0,100.0,50.0,1.2,140.0,3.5,14.0,50.0,6700.0,6.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
99,754973,39.0,60.0,86.0,37.0,0.6,150.0,5.0,13.6,51.0,5800.0,4.5,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
100,235579,46.0,60.0,102.0,27.0,0.7,142.0,4.9,13.2,44.0,11000.0,5.4,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True

## Part 3.7 : Normalize the Numerical Columns

Normalizing numerical attributes ensures that all features contribute equally to the model by scaling them to a consistent range, which improves model performance and convergence. It prevents features with larger scales from disproportionately influencing the model's learning process.

In [11]:
# Normalize the all Numerical Attributes in the dataset.
for col in numerical_columns:
    both_df[col] = (both_df[col] - both_df[col].min()) / (both_df[col].max() - both_df[col].min())
# Print the dataset
display(both_df)

,unique_id,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc,al,su,rbc_abnormal,rbc_normal,pc_abnormal,pc_normal,pcc_notpresent,pcc_present,ba_notpresent,ba_present,htn_no,htn_yes,dm_no,dm_yes,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
0,474407,0.202703,0.75,0.158798,0.196078,0.160494,0.166667,0.206897,0.059406,0.000000,0.653226,0.257143,4.0,0.0,False,True,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False,False,True,True,False
1,137148,0.905405,1.00,0.965665,0.522876,0.641975,0.666667,0.000000,0.148515,0.225806,0.217742,0.057143,3.0,2.0,True,False,True,False,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,True,False
2,343710,0.743243,0.50,0.442060,0.901961,0.432099,0.500000,0.793103,0.000000,0.032258,0.395161,0.057143,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,False,True,False,True,False,True,True,False
3,532520,0.729730,0.75,0.150215,0.281046,0.234568,0.533333,0.793103,0.336634,0.322581,0.500000,0.314286,2.0,0.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
4,546225,0.540541,0.00,0.399142,0.535948,0.358025,0.700000,0.379310,0.207921,0.161290,0.830645,0.057143,1.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
5,514721,0.675676,0.75,0.253219,0.633987,0.777778,0.366667,0.655172,0.138614,0.193548,0.169355,0.114286,2.0,0.0,True,False,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False
6,621332,0.716216,0.50,1.000000,0.163399,0.111111,0.066667,0.206897,0.267327,0.387097,0.532258,0.371429,1.0,0.0,True,False,False,True,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,True,False
7,481293,0.729730,0.00,0.935622,0.169935,0.160494,0.333333,0.034483,0.019802,0.064516,0.879032,0.000000,3.0,1.0,False,True,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,False,True,True,False
8,615697,0.000000,0.00,0.103004,0.372549,0.074074,0.500000,0.689655,0.217822,0.225806,1.000000,0.514286,4.0,0.0,True,False,True,False,True,False,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False
9,843362,0.878378,0.00,0.206009,0.751634,0.604938,0.533333,0.689655,0.366337,0.387097,0.879032,0.371429,4.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,False,True,False,True,True,False,True,False
10,995177,0.851351,0.25,0.618026,0.562092,0.728395,0.000000,0.344828,0.168317,0.161290,0.580645,0.085714,4.0,3.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,False,True,False,True,True,False
11,828592,0.878378,0.25,0.639485,0.470588,0.395062,0.433333,0.517241,0.267327,0.322581,0.104839,0.171429,3.0,0.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,True,False,True,False,True,False
12,923613,0.783784,0.00,0.725322,0.313725,0.481481,0.566667,0.862069,0.178218,0.193548,0.258065,0.114286,4.0,1.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,False,True,True,False,True,False
13,955830,0.662162,0.50,0.618026,0.411765,0.432099,0.566667,0.689655,0.316832,0.354839,0.250000,0.200000,3.0,1.0,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
14,397388,0.770270,1.00,0.901288,0.163399,0.345679,0.766667,0.206897,0.524752,0.548387,0.443548,0.342857,2.0,2.0,False,True,False,True,True,False,False,True,False,True,True,False,False,True,True,False,True,False,True,False,True,False
15,438182,0.905405,0.50,0.785408,0.862745,0.518519,0.600000,1.000000,0.277228,0.322581,0.233871,0.371429,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,True,False,True,False
16,197452,0.675676,0.25,0.600858,0.104575,0.160494,0.533333,0.310345,0.831683,0.935484,0.661290,0.742857,4.0,1.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
17,129053,0.567568,0.50,0.270386,0.843137,1.000000,0.400000,0.896552,0.257426,0.419355,0.153226,0.285714,4.0,0.0,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,True,False
18,475200,0.783784,1.00,0.399142,0.287582,0.839506,0.666667,0.586207,0.019802,0.096774,0.258065,0.114286,4.0,2.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
19,124304,0.851351,0.25,0.832618,0.503268,0.283951,0.333333,0.379310,0.475248,0.451613,0.427419,0.314286,3.0,4.0,False,True,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,True,False,True,False
20,234299,0.567568,0.50,0.107296,1.000000,0.901235,0.533333,0.310345,0.207921,0.290323,0.209677,0.114286,4.0,0.0,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,False,True,True,False
21,980291,0.756757,0.25,0.223176,0.209150,0.160494,0.533333,0.620690,0.485149,0.516129,0.290323,0.257143,3.0,0.0,False,True,True,False,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
22,499221,0.324324,0.50,0.111588,0.098039,0.012346,0.800000,0.655172,0.603960,0.612903,0.379032,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
23,436056,0.081081,0.50,0.128755,0.104575,0.024691,0.566667,0.517241,0.801980,0.838710,0.185484,0.685714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
24,296998,0.756757,0.50,0.266094,0.156863,0.049383,0.900000,0.206897,1.000000,0.677419,0.032258,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
25,634224,0.932432,0.25,0.158798,0.248366,0.049383,0.800000,0.206897,0.584158,0.741935,0.483871,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
26,482105,0.513514,0.00,0.107296,0.235294,0.012346,0.600000,0.448276,0.722772,0.870968,0.274194,0.942857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
27,918330,0.729730,0.50,0.047210,0.032680,0.012346,0.700000,0.241379,0.722772,0.741935,0.500000,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
28,155117,0.837838,0.00,0.236052,0.202614,0.086420,0.633333,0.310345,0.960396,0.870968,0.193548,0.885714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
29,674446,0.662162,0.50,0.257511,0.261438,0.098765,0.900000,0.724138,0.772277,0.580645,0.387097,0.857143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
30,530138,0.229730,0.50,0.175966,0.156863,0.086420,0.833333,0.379310,0.653465,0.580645,0.233871,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
31,670655,1.000000,0.50,0.210300,0.235294,0.037037,0.700000,0.689655,0.613861,0.838710,0.064516,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
32,746768,0.256757,0.25,0.077253,0.209150,0.012346,0.533333,0.206897,0.554455,0.806452,0.217742,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
33,118596,0.918919,0.00,0.077253,0.261438,0.024691,0.900000,0.275862,0.940594,0.967742,0.137097,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
34,390779,0.567568,0.50,0.223176,0.150327,0.061728,0.866667,0.344828,0.613861,0.806452,0.419355,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
35,234626,0.243243,0.25,0.300429,0.084967,0.024691,0.666667,0.620690,0.851485,0.806452,0.120968,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
36,486397,0.189189,0.25,0.227468,0.222222,0.074074,0.500000,0.310345,0.683168,0.677419,0.096774,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
37,250046,0.675676,0.00,0.266094,0.052288,0.086420,0.900000,0.620690,0.594059,0.709677,0.258065,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
38,462892,0.405405,0.50,0.064378,0.039216,0.086420,0.733333,0.413793,0.782178,0.677419,0.120968,0.942857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
39,155872,0.716216,0.00,0.184549,0.084967,0.086420,0.633333,0.206897,0.752475,1.000000,0.177419,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
40,553648,0.364865,0.50,0.128755,0.176471,0.098765,0.733333,0.379310,0.910891,0.935484,0.193548,0.857143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
41,720366,0.864865,0.50,0.017167,0.202614,0.012346,0.766667,0.551724,0.732673,0.806452,0.435484,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
42,923398,0.608108,0.50,0.103004,0.032680,0.098765,0.800000,0.275862,0.772277,0.741935,0.419355,0.971429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
43,345689,0.121622,0.50,0.098712,0.045752,0.061728,0.533333,0.344828,0.891089,0.870968,0.153226,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
44,460315,0.229730,0.50,0.000000,0.169935,0.074074,1.000000,0.586207,0.920792,0.935484,0.443548,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
45,719916,0.459459,0.50,0.300429,0.000000,0.098765,0.500000,0.724138,0.722772,0.806452,0.491935,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
46,994377,0.878378,0.25,0.047210,0.052288,0.049383,0.833333,0.724138,0.693069,0.677419,0.443548,0.857143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
47,173519,0.810811,0.25,0.158798,0.039216,0.086420,0.666667,0.241379,0.584158,0.612903,0.540323,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
48,968221,0.662162,0.50,0.206009,0.052288,0.061728,0.500000,0.241379,0.772277,0.645161,0.233871,0.685714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
49,180660,0.608108,0.00,0.124464,0.183007,0.049383,0.500000,0.275862,0.524752,0.838710,0.322581,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
50,834066,0.662162,0.50,0.270386,0.045752,0.098765,0.500000,0.655172,0.544554,0.580645,0.201613,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
51,608641,0.500000,0.50,0.257511,0.130719,0.086420,0.766667,0.724138,0.811881,0.709677,0.282258,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
52,712694,0.729730,0.00,0.274678,0.228758,0.012346,0.633333,0.655172,0.643564,0.806452,0.516129,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
53,871127,0.527027,0.50,0.201717,0.235294,0.098765,0.566667,0.724138,0.841584,0.709677,0.346774,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
54,585932,0.256757,0.50,0.218884,0.058824,0.098765,0.733333,0.689655,0.722772,0.806452,0.209677,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
55,322882,0.364865,0.50,0.248927,0.183007,0.024691,0.500000,0.344828,0.534653,0.709677,0.153226,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
56,789906,0.851351,0.25,0.055794,0.209150,0.098765,0.633333,0.275862,0.841584,0.870968,0.403226,0.685714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
57,201768,0.702703,0.25,0.077253,0.039216,0.086420,0.900000,0.206897,0.861386,0.967742,0.387097,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
58,118191,0.486486,0.25,0.098712,0.143791,0.061728,0.766667,0.620690,0.881188,0.645161,0.225806,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
59,883369,0.716216,0.25,0.257511,0.189542,0.037037,0.900000,0.620690,0.574257,0.741935,0.193548,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
60,963946,0.594595,0.50,0.287554,0.235294,0.049383,0.633333,0.724138,0.633663,0.709677,0.419355,0.457143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
61,551175,0.554054,0.50,0.231760,0.222222,0.074074,0.666667,0.689655,0.712871,0.580645,0.217742,0.771429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
62,873195,0.513514,0.25,0.094421,0.196078,0.061728,0.700000,0.689655,0.623762,0.935484,0.258065,0.914286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
63,604045,0.324324,0.00,0.214592,0.137255,0.049383,1.000000,0.586207,0.564356,0.677419,0.516129,0.800000,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
64,131563,0.310811,0.50,0.055794,0.254902,0.061728,0.633333,0.137931,0.970297,0.548387,0.451613,0.485714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
65,433613,0.594595,0.50,0.115880,0.196078,0.024691,1.000000,0.551724,0.643564,0.806452,0.500000,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
66,203694,0.432432,0.50,0.124464,0.058824,0.012346,0.900000,0.206897,0.584158,0.677419,0.241935,0.971429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
67,996076,0.689189,0.00,0.150215,0.254902,0.098765,1.000000,0.620690,0.792079,0.677419,0.491935,0.914286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
68,750155,0.540541,0.00,0.227468,0.235294,0.074074,0.500000,0.724138,0.792079,0.870968,0.161290,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
69,114717,0.472973,0.50,0.223176,0.098039,0.049383,0.600000,0.724138,0.930693,0.580645,0.387097,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
70,676393,0.770270,0.25,0.184549,0.098039,0.024691,0.866667,0.689655,0.871287,0.935484,0.298387,0.600000,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
71,379507,0.148649,0.00,0.188841,0.261438,0.074074,0.500000,0.689655,0.643564,0.903226,0.233871,0.828571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
72,991031,0.324324,0.50,0.081545,0.209150,0.012346,0.633333,0.724138,0.891089,0.935484,0.475806,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
73,490253,0.500000,0.50,0.047210,0.235294,0.024691,0.500000,0.689655,0.613861,0.806452,0.209677,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
74,283427,0.662162,0.50,0.300429,0.254902,0.012346,1.000000,0.689655,0.792079,0.774194,0.193548,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
75,328705,0.445946,0.25,0.261803,0.235294,0.024691,0.833333,0.724138,0.782178,0.580645,0.411290,0.485714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
76,268609,0.675676,0.50,0.296137,0.032680,0.098765,0.500000,0.724138,0.702970,0.612903,0.104839,0.714286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
77,524004,0.324324,0.50,0.051502,0.209150,0.037037,0.866667,0.724138,0.712871,0.709677,0.411290,0.828571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
78,418316,0.756757,0.50,0.034335,0.228758,0.024691,0.600000,0.206897,0.831683,0.870968,0.088710,0.771429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
79,721270,0.702703,0.25,0.137339,0.248366,0.098765,0.633333,0.482759,0.722772,0.548387,0.306452,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
80,261137,0.391892,0.00,0.150215,0.189542,0.012346,0.500000,0.344828,0.693069,0.645161,0.120968,0.914286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
81,643841,0.229730,0.50,0.124464,0.235294,0.098765,0.733333,0.379310,0.990099,0.741935,0.000000,0.714286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
82,557347,0.378378,0.50,0.218884,0.111111,0.098765,0.800000,0.344828,0.584158,0.935484,0.395161,0.942857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
83,441170,0.986486,0.50,0.175966,0.222222,0.098765,0.866667,0.241379,0.851485,0.548387,0.298387,0.971429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True

## Part 3.8: Remove Unnecessary columns

Are there any columns in this dataset which are not appropriate for modeling and predictions? Which column(s)? Justify their exclusion and remove them

Answer: The column "unique_id" is just an arbitrary id for each person with no medical significance, and thus should not be used for predictions.

In [12]:
#Remove that column
both_df = both_df.drop(columns="unique_id")
# Print the dataset
display(both_df)

,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wbcc,rbcc,al,su,rbc_abnormal,rbc_normal,pc_abnormal,pc_normal,pcc_notpresent,pcc_present,ba_notpresent,ba_present,htn_no,htn_yes,dm_no,dm_yes,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes,Target_ckd,Target_notckd
0,0.202703,0.75,0.158798,0.196078,0.160494,0.166667,0.206897,0.059406,0.000000,0.653226,0.257143,4.0,0.0,False,True,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False,False,True,True,False
1,0.905405,1.00,0.965665,0.522876,0.641975,0.666667,0.000000,0.148515,0.225806,0.217742,0.057143,3.0,2.0,True,False,True,False,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,True,False
2,0.743243,0.50,0.442060,0.901961,0.432099,0.500000,0.793103,0.000000,0.032258,0.395161,0.057143,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,False,True,False,True,False,True,True,False
3,0.729730,0.75,0.150215,0.281046,0.234568,0.533333,0.793103,0.336634,0.322581,0.500000,0.314286,2.0,0.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
4,0.540541,0.00,0.399142,0.535948,0.358025,0.700000,0.379310,0.207921,0.161290,0.830645,0.057143,1.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
5,0.675676,0.75,0.253219,0.633987,0.777778,0.366667,0.655172,0.138614,0.193548,0.169355,0.114286,2.0,0.0,True,False,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False
6,0.716216,0.50,1.000000,0.163399,0.111111,0.066667,0.206897,0.267327,0.387097,0.532258,0.371429,1.0,0.0,True,False,False,True,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,True,False
7,0.729730,0.00,0.935622,0.169935,0.160494,0.333333,0.034483,0.019802,0.064516,0.879032,0.000000,3.0,1.0,False,True,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,False,True,True,False
8,0.000000,0.00,0.103004,0.372549,0.074074,0.500000,0.689655,0.217822,0.225806,1.000000,0.514286,4.0,0.0,True,False,True,False,True,False,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False
9,0.878378,0.00,0.206009,0.751634,0.604938,0.533333,0.689655,0.366337,0.387097,0.879032,0.371429,4.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,False,True,False,True,True,False,True,False
10,0.851351,0.25,0.618026,0.562092,0.728395,0.000000,0.344828,0.168317,0.161290,0.580645,0.085714,4.0,3.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,False,True,False,True,True,False
11,0.878378,0.25,0.639485,0.470588,0.395062,0.433333,0.517241,0.267327,0.322581,0.104839,0.171429,3.0,0.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,True,False,True,False,True,False
12,0.783784,0.00,0.725322,0.313725,0.481481,0.566667,0.862069,0.178218,0.193548,0.258065,0.114286,4.0,1.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,False,True,True,False,True,False
13,0.662162,0.50,0.618026,0.411765,0.432099,0.566667,0.689655,0.316832,0.354839,0.250000,0.200000,3.0,1.0,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
14,0.770270,1.00,0.901288,0.163399,0.345679,0.766667,0.206897,0.524752,0.548387,0.443548,0.342857,2.0,2.0,False,True,False,True,True,False,False,True,False,True,True,False,False,True,True,False,True,False,True,False,True,False
15,0.905405,0.50,0.785408,0.862745,0.518519,0.600000,1.000000,0.277228,0.322581,0.233871,0.371429,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,True,False,True,False
16,0.675676,0.25,0.600858,0.104575,0.160494,0.533333,0.310345,0.831683,0.935484,0.661290,0.742857,4.0,1.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
17,0.567568,0.50,0.270386,0.843137,1.000000,0.400000,0.896552,0.257426,0.419355,0.153226,0.285714,4.0,0.0,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,True,False
18,0.783784,1.00,0.399142,0.287582,0.839506,0.666667,0.586207,0.019802,0.096774,0.258065,0.114286,4.0,2.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
19,0.851351,0.25,0.832618,0.503268,0.283951,0.333333,0.379310,0.475248,0.451613,0.427419,0.314286,3.0,4.0,False,True,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,True,False,True,False
20,0.567568,0.50,0.107296,1.000000,0.901235,0.533333,0.310345,0.207921,0.290323,0.209677,0.114286,4.0,0.0,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,False,True,True,False
21,0.756757,0.25,0.223176,0.209150,0.160494,0.533333,0.620690,0.485149,0.516129,0.290323,0.257143,3.0,0.0,False,True,True,False,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
22,0.324324,0.50,0.111588,0.098039,0.012346,0.800000,0.655172,0.603960,0.612903,0.379032,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
23,0.081081,0.50,0.128755,0.104575,0.024691,0.566667,0.517241,0.801980,0.838710,0.185484,0.685714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
24,0.756757,0.50,0.266094,0.156863,0.049383,0.900000,0.206897,1.000000,0.677419,0.032258,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
25,0.932432,0.25,0.158798,0.248366,0.049383,0.800000,0.206897,0.584158,0.741935,0.483871,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
26,0.513514,0.00,0.107296,0.235294,0.012346,0.600000,0.448276,0.722772,0.870968,0.274194,0.942857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
27,0.729730,0.50,0.047210,0.032680,0.012346,0.700000,0.241379,0.722772,0.741935,0.500000,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
28,0.837838,0.00,0.236052,0.202614,0.086420,0.633333,0.310345,0.960396,0.870968,0.193548,0.885714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
29,0.662162,0.50,0.257511,0.261438,0.098765,0.900000,0.724138,0.772277,0.580645,0.387097,0.857143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
30,0.229730,0.50,0.175966,0.156863,0.086420,0.833333,0.379310,0.653465,0.580645,0.233871,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
31,1.000000,0.50,0.210300,0.235294,0.037037,0.700000,0.689655,0.613861,0.838710,0.064516,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
32,0.256757,0.25,0.077253,0.209150,0.012346,0.533333,0.206897,0.554455,0.806452,0.217742,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
33,0.918919,0.00,0.077253,0.261438,0.024691,0.900000,0.275862,0.940594,0.967742,0.137097,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
34,0.567568,0.50,0.223176,0.150327,0.061728,0.866667,0.344828,0.613861,0.806452,0.419355,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
35,0.243243,0.25,0.300429,0.084967,0.024691,0.666667,0.620690,0.851485,0.806452,0.120968,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
36,0.189189,0.25,0.227468,0.222222,0.074074,0.500000,0.310345,0.683168,0.677419,0.096774,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
37,0.675676,0.00,0.266094,0.052288,0.086420,0.900000,0.620690,0.594059,0.709677,0.258065,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
38,0.405405,0.50,0.064378,0.039216,0.086420,0.733333,0.413793,0.782178,0.677419,0.120968,0.942857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
39,0.716216,0.00,0.184549,0.084967,0.086420,0.633333,0.206897,0.752475,1.000000,0.177419,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
40,0.364865,0.50,0.128755,0.176471,0.098765,0.733333,0.379310,0.910891,0.935484,0.193548,0.857143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
41,0.864865,0.50,0.017167,0.202614,0.012346,0.766667,0.551724,0.732673,0.806452,0.435484,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
42,0.608108,0.50,0.103004,0.032680,0.098765,0.800000,0.275862,0.772277,0.741935,0.419355,0.971429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
43,0.121622,0.50,0.098712,0.045752,0.061728,0.533333,0.344828,0.891089,0.870968,0.153226,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
44,0.229730,0.50,0.000000,0.169935,0.074074,1.000000,0.586207,0.920792,0.935484,0.443548,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
45,0.459459,0.50,0.300429,0.000000,0.098765,0.500000,0.724138,0.722772,0.806452,0.491935,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
46,0.878378,0.25,0.047210,0.052288,0.049383,0.833333,0.724138,0.693069,0.677419,0.443548,0.857143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
47,0.810811,0.25,0.158798,0.039216,0.086420,0.666667,0.241379,0.584158,0.612903,0.540323,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
48,0.662162,0.50,0.206009,0.052288,0.061728,0.500000,0.241379,0.772277,0.645161,0.233871,0.685714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
49,0.608108,0.00,0.124464,0.183007,0.049383,0.500000,0.275862,0.524752,0.838710,0.322581,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
50,0.662162,0.50,0.270386,0.045752,0.098765,0.500000,0.655172,0.544554,0.580645,0.201613,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
51,0.500000,0.50,0.257511,0.130719,0.086420,0.766667,0.724138,0.811881,0.709677,0.282258,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
52,0.729730,0.00,0.274678,0.228758,0.012346,0.633333,0.655172,0.643564,0.806452,0.516129,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
53,0.527027,0.50,0.201717,0.235294,0.098765,0.566667,0.724138,0.841584,0.709677,0.346774,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
54,0.256757,0.50,0.218884,0.058824,0.098765,0.733333,0.689655,0.722772,0.806452,0.209677,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
55,0.364865,0.50,0.248927,0.183007,0.024691,0.500000,0.344828,0.534653,0.709677,0.153226,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
56,0.851351,0.25,0.055794,0.209150,0.098765,0.633333,0.275862,0.841584,0.870968,0.403226,0.685714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
57,0.702703,0.25,0.077253,0.039216,0.086420,0.900000,0.206897,0.861386,0.967742,0.387097,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
58,0.486486,0.25,0.098712,0.143791,0.061728,0.766667,0.620690,0.881188,0.645161,0.225806,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
59,0.716216,0.25,0.257511,0.189542,0.037037,0.900000,0.620690,0.574257,0.741935,0.193548,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
60,0.594595,0.50,0.287554,0.235294,0.049383,0.633333,0.724138,0.633663,0.709677,0.419355,0.457143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
61,0.554054,0.50,0.231760,0.222222,0.074074,0.666667,0.689655,0.712871,0.580645,0.217742,0.771429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
62,0.513514,0.25,0.094421,0.196078,0.061728,0.700000,0.689655,0.623762,0.935484,0.258065,0.914286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
63,0.324324,0.00,0.214592,0.137255,0.049383,1.000000,0.586207,0.564356,0.677419,0.516129,0.800000,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
64,0.310811,0.50,0.055794,0.254902,0.061728,0.633333,0.137931,0.970297,0.548387,0.451613,0.485714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
65,0.594595,0.50,0.115880,0.196078,0.024691,1.000000,0.551724,0.643564,0.806452,0.500000,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
66,0.432432,0.50,0.124464,0.058824,0.012346,0.900000,0.206897,0.584158,0.677419,0.241935,0.971429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
67,0.689189,0.00,0.150215,0.254902,0.098765,1.000000,0.620690,0.792079,0.677419,0.491935,0.914286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
68,0.540541,0.00,0.227468,0.235294,0.074074,0.500000,0.724138,0.792079,0.870968,0.161290,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
69,0.472973,0.50,0.223176,0.098039,0.049383,0.600000,0.724138,0.930693,0.580645,0.387097,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
70,0.770270,0.25,0.184549,0.098039,0.024691,0.866667,0.689655,0.871287,0.935484,0.298387,0.600000,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
71,0.148649,0.00,0.188841,0.261438,0.074074,0.500000,0.689655,0.643564,0.903226,0.233871,0.828571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
72,0.324324,0.50,0.081545,0.209150,0.012346,0.633333,0.724138,0.891089,0.935484,0.475806,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
73,0.500000,0.50,0.047210,0.235294,0.024691,0.500000,0.689655,0.613861,0.806452,0.209677,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
74,0.662162,0.50,0.300429,0.254902,0.012346,1.000000,0.689655,0.792079,0.774194,0.193548,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
75,0.445946,0.25,0.261803,0.235294,0.024691,0.833333,0.724138,0.782178,0.580645,0.411290,0.485714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
76,0.675676,0.50,0.296137,0.032680,0.098765,0.500000,0.724138,0.702970,0.612903,0.104839,0.714286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
77,0.324324,0.50,0.051502,0.209150,0.037037,0.866667,0.724138,0.712871,0.709677,0.411290,0.828571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
78,0.756757,0.50,0.034335,0.228758,0.024691,0.600000,0.206897,0.831683,0.870968,0.088710,0.771429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
79,0.702703,0.25,0.137339,0.248366,0.098765,0.633333,0.482759,0.722772,0.548387,0.306452,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
80,0.391892,0.00,0.150215,0.189542,0.012346,0.500000,0.344828,0.693069,0.645161,0.120968,0.914286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
81,0.229730,0.50,0.124464,0.235294,0.098765,0.733333,0.379310,0.990099,0.741935,0.000000,0.714286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
82,0.378378,0.50,0.218884,0.111111,0.098765,0.800000,0.344828,0.584158,0.935484,0.395161,0.942857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
83,0.986486,0.50,0.175966,0.222222,0.098765,0.866667,0.241379,0.851485,0.548387,0.298387,0.971429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
84,0.905405,0.00,0.244635,0.248366,0.012346,1.000000,0.206897,0.732673,0.935484,0.540323,0.485714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
85,0.486486,0.50,0.266094,0.091503,0.037037,0.666667,0.413793,0.663366,0.870968,0.056452,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True

## Part 3.9: Export the Cleaned Data

Now that you've completed these cleaning steps you should have a pandas dataframe which is much cleaner and ready for modeling. Our final step is to save our work. Export the DataFrame to a two new formats: csv and json.

In [13]:
# Export the dataframe to a new csv file
both_df.to_csv('cleaned.csv', index=False)  
# Export the dataframe to a new json file
both_df.to_json('cleaned.json')

# Part 4: Data conversions with Large Language Models

One powerful use case of ChatGPT (and other generative language models) is cleaning and transforming data. In some cases, these models can directly manipulate loosely structured data that you provide to them into a standard format. In the other cases, you can often prompt the model to create a conversion or extraction script for you in python or Pandas and then run it on your own. 

In this part of the assignment you will prompt 383GPT to explore these capabilities.

## Part 4.1 GPT Data Manipulation

Take the cleaned dataset that you created in part three and output the top 15 rows of that dataset. Then copy the terminal output, open 383gpt and ask it to convert that output to a markdown table. Paste that markdown table in the cell bellow

In [14]:
print(both_df.head(15))

         age    bp       bgr        bu        sc       sod       pot  \
0   0.202703  0.75  0.158798  0.196078  0.160494  0.166667  0.206897
1   0.905405  1.00  0.965665  0.522876  0.641975  0.666667  0.000000
2   0.743243  0.50  0.442060  0.901961  0.432099  0.500000  0.793103
3   0.729730  0.75  0.150215  0.281046  0.234568  0.533333  0.793103
4   0.540541  0.00  0.399142  0.535948  0.358025  0.700000  0.379310
5   0.675676  0.75  0.253219  0.633987  0.777778  0.366667  0.655172
6   0.716216  0.50  1.000000  0.163399  0.111111  0.066667  0.206897
7   0.729730  0.00  0.935622  0.169935  0.160494  0.333333  0.034483
8   0.000000  0.00  0.103004  0.372549  0.074074  0.500000  0.689655
9   0.878378  0.00  0.206009  0.751634  0.604938  0.533333  0.689655
10  0.851351  0.25  0.618026  0.562092  0.728395  0.000000  0.344828
11  0.878378  0.25  0.639485  0.470588  0.395062  0.433333  0.517241
12  0.783784  0.00  0.725322  0.313725  0.481481  0.566667  0.862069
13  0.662162  0.50  0.618026  0.411765  0.432099  0.566667  0.689655
14  0.770270  1.00  0.901288  0.163399  0.345679  0.766667  0.206897

        hemo       pcv      wbcc      rbcc   al   su  rbc_abnormal  \
0   0.059406  0.000000  0.653226  0.257143  4.0  0.0         False
1   0.148515  0.225806  0.217742  0.057143  3.0  2.0          True
2   0.000000  0.032258  0.395161  0.057143  2.0  0.0          True
3   0.336634  0.322581  0.500000  0.314286  2.0  0.0          True
4   0.207921  0.161290  0.830645  0.057143  1.0  0.0         False
5   0.138614  0.193548  0.169355  0.114286  2.0  0.0          True
6   0.267327  0.387097  0.532258  0.371429  1.0  0.0          True
7   0.019802  0.064516  0.879032  0.000000  3.0  1.0         False
8   0.217822  0.225806  1.000000  0.514286  4.0  0.0          True
9   0.366337  0.387097  0.879032  0.371429  4.0  0.0         False
10  0.168317  0.161290  0.580645  0.085714  4.0  3.0         False
11  0.267327  0.322581  0.104839  0.171429  3.0  0.0         False
12  0.178218  0.193548  0.258065  0.114286  4.0  1.0          True
13  0.316832  0.354839  0.250000  0.200000  3.0  1.0         False
14  0.524752  0.548387  0.443548  0.342857  2.0  2.0         False

    rbc_normal  pc_abnormal  pc_normal  pcc_notpresent  pcc_present  \
0         True         True      False           False         True
1        False         True      False           False         True
2        False         True      False            True        False
3        False        False       True            True        False
4         True        False       True            True        False
5        False         True      False            True        False
6        False        False       True            True        False
7         True         True      False           False         True
8        False         True      False            True        False
9         True        False       True            True        False
10        True         True      False           False         True
11        True         True      False           False         True
12       False         True      False            True        False
13        True         True      False           False         True
14        True        False       True            True        False

    ba_notpresent  ba_present  htn_no  htn_yes  dm_no  dm_yes  cad_no  \
0           False        True    True    False   True   False    True
1            True       False   False     True  False    True   False
2            True       False   False     True  False    True   False
3            True       False    True    False   True   False    True
4            True       False   False     True  False    True    True
5            True       False   False     True   True   False    True
6            True       False    True    False  False    True    True
7            True       False   False     True   True   False    True
8           False        True    True    False   True   False    True
9            True       False   False     True  False    True    True
10          False        True   False     True  False    True   False
11          False        True   False     True  False    True   False
12          False        True   False     True  False    True    True
13          False        True   False     True  False    True    True
14          False        True   False     True   True   False   False

    cad_yes  appet_good  appet_poor  pe_no  pe_yes  ane_no  ane_yes  \
0     False        True       False   True   False   False     True
1      True       False        True   True   False    True    False
2      True       False        True  False    True   False     True
3     False        True       False   True   False    True    False
4     False        True       False   True   False    True    False
5     False        True       False   True   False    True    False
6     False       False        True   True   False    True    False
7     False       False        True   True   False   False     True
8     False       False        True   True   False    True    False
9     False       False        True  False    True    True    False
10     True        True       False  False    True   False     True
11     True        True       False   True   False    True    False
12    False       False        True  False    True    True    False
13    False        True       False  False    True    True    False
14     True        True       False   True   False    True    False

    Target_ckd  Target_notckd
0         True          False
1         True          False
2         True          False
3         True          False
4         True          False
5         True          False
6         True          False
7         True          False
8         True          False
9         True          False
10        True          False
11        True          False
12        True          False
13        True          False
14        True          False

### Paste the markdown table here

Paste here: 
| | age | bp | bgr | bu | sc | sod | pot | hemo | pcv | wbcc | rbcc | al | su | rbc_abnormal | rbc_normal | pc_abnormal | pc_normal | pcc_notpresent | pcc_present | ba_notpresent | ba_present | htn_no | htn_yes | dm_no | dm_yes | cad_no | cad_yes | appet_good | appet_poor | pe_no | pe_yes | ane_no | ane_yes | Target_ckd | Target_notckd |
|----|-----------|-------|-----------|-----------|-----------|-----------|-----------|------------|-----------|-----------|-----------|------|------|---------------|------------|-------------|-----------|----------------|-------------|---------------|------------|--------|---------|-------|--------|--------|---------|-------------|-------------|-------|--------|--------|---------|-------------|----------------|
| 0 | 0.202703 | 0.75 | 0.158798 | 0.196078 | 0.160494 | 0.166667 | 0.206897 | 0.059406 | 0.000000 | 0.653226 | 0.257143 | 4.0 | 0.0 | False | True | True | False | False | True | False | True | True | False | True | False | True | False | True | False | True | False | False | True | True | False |
| 1 | 0.905405 | 1.00 | 0.965665 | 0.522876 | 0.641975 | 0.666667 | 0.000000 | 0.148515 | 0.225806 | 0.217742 | 0.057143 | 3.0 | 2.0 | True | False | True | False | False | True | True | False | False | True | False | True | False | True | False | True | True | False | True | False | True | False |
| 2 | 0.743243 | 0.50 | 0.442060 | 0.901961 | 0.432099 | 0.500000 | 0.793103 | 0.000000 | 0.032258 | 0.395161 | 0.057143 | 2.0 | 0.0 | True | False | True | False | True | False | True | False | False | True | False | True | False | True | False | True | False | True | False | True | True | False |
| 3 | 0.729730 | 0.75 | 0.150215 | 0.281046 | 0.234568 | 0.533333 | 0.793103 | 0.336634 | 0.322581 | 0.500000 | 0.314286 | 2.0 | 0.0 | True | False | False | True | True | False | True | False | True | False | True | False | True | False | True | False | True | False | True | False | True | False |
| 4 | 0.540541 | 0.00 | 0.399142 | 0.535948 | 0.358025 | 0.700000 | 0.379310 | 0.207921 | 0.161290 | 0.830645 | 0.057143 | 1.0 | 0.0 | False | True | False | True | True | False | True | False | False | True | False | True | True | False | True | False | True | False | True | False | True | False |
| 5 | 0.675676 | 0.75 | 0.253219 | 0.633987 | 0.777778 | 0.366667 | 0.655172 | 0.138614 | 0.193548 | 0.169355 | 0.114286 | 2.0 | 0.0 | True | False | True | False | True | False | True | False | True | False | True | False | True | False | True | False | True | False | True | False | True | False |
| 6 | 0.716216 | 0.50 | 1.000000 | 0.163399 | 0.111111 | 0.066667 | 0.206897 | 0.267327 | 0.387097 | 0.532258 | 0.371429 | 1.0 | 0.0 | True | False | False | True | True | False | True | False | True | False | False | True | True | False | False | True | True | True | False | True | True | False |
| 7 | 0.729730 | 0.00 | 0.935622 | 0.169935 | 0.160494 | 0.333333 | 0.034483 | 0.019802 | 0.064516 | 0.879032 | 0.000000 | 3.0 | 1.0 | False | True | True | False | False | True | True | False | False | True | True | False | True | False | False | True | True | False | False | True | True | False |
| 8 | 0.000000 | 0.00 | 0.103004 | 0.372549 | 0.074074 | 0.500000 | 0.689655 | 0.217822 | 0.225806 | 1.000000 | 0.514286 | 4.0 | 0.0 | True | False | True | False | True | False | False | True | True | False | True | False | True | False | False | False | True | True | False | True | True | False |
| 9 | 0.878378 | 0.00 | 0.206009 | 0.751634 | 0.604938 | 0.533333 | 0.689655 | 0.366337 | 0.387097 | 0.879032 | 0.371429 | 4.0 | 0.0 | False | True | False | True | True | False | True | False | True | False | True | False | True | False | False | True | True | False | True | False | True | False |
| 10 | 0.851351 | 0.25  | 0.618026 | 0.562092  | 0.728395  | 0.000000   | 0.344828   | 0.168317   | 0.161290  | 0.580645  | 0.085714  | 4.0  | 3.0  | False         | True       | True        | False     | False          | True        | False         | True       | False  | True    | True  | False  | True   | False   | True        | False      | True  | False  | False  | True    | True        | False          |
| 11 | 0.878378 | 0.25  | 0.639485 | 0.470588  | 0.395062  | 0.433333   | 0.517241   | 0.267327   | 0.322581  | 0.104839  | 0.171429  | 3.0  | 0.0  | False         | True       | True        | False     | False          | True        | False         | True       | False  | True    | True  | False  | True   | False   | True        | False      | True  | False  | False  | True    | True        | False          |
| 12 | 0.783784 | 0.00  | 0.725322 | 0.313725  | 0.481481  | 0.566667   | 0.862069   | 0.178218   | 0.193548  | 0.258065  | 0.114286  | 4.0  | 1.0  | True          | False      | True        | False     | True           | False       | False         | True       | False  | True    | True  | False  | True   | False   | False       | True       | True  | False  | False  | True    | True        | False          |
| 13 | 0.662162 | 0.50  | 0.618026 | 0.411765  | 0.432099  | 0.566667   | 0.689655   | 0.316832   | 0.354839  | 0.250000  | 0.200000  | 3.0  | 1.0  | False         | True       | False       | True      | False          | True        | False         | True       | False  | True    | True  | False  | True   | True    | False       | True       | False | False  | True   | False   | True        | False          |
| 14 | 0.770270 | 1.00  | 0.901288 | 0.163399  | 0.345679  | 0.766667   | 0.206897   | 0.524752   | 0.548387  | 0.443548  | 0.342857  | 2.0  | 2.0  | False         | True       | False       | True      | True           | False       | False         | True       | False  | True    | True  | False  | False  | True    | True        | False      | True  | False  | False  | True    | True        | False          |

** Caution: ** while language models can perform data conversions they also can * hallucinate * during this process, particularly for bigger datasets. Reflect on this below, how could you mitigate data conversion hallucinations from LLM conversions?

Answer: You might be able to mitigate hallucinations with prompt engineering, specifically by telling the LLM to double-check its work, or by giving it a few examples of the type of output that you expect (few-shot learning).

## Part 4.2 GPT Pandas Prompting

In this section, you will prompt 383GPT to write pandas code manipulations for you.

After working with this data for awhile, we realized we're starting to forget the meanings of the abbreviated column names. Let's ask 383GPT to fix this for us. First, navigate to the [UCI dataset overview](https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease) and copy the abbrevation to name mapping. Then, go to 383GPT and instruct the LLM to provide you with a pandas script to apply this renaming to all the columns of your dataset. Paste that code below and make any adjustments necessary to run it in your notebook.

In [15]:
# Code to rename all the columns in the dataset
gpt_df = both_df

# Mapping of abbreviations to full names
abbreviation_mapping = {
    'age': 'age',
    'bp': 'blood pressure',
    'sg': 'specific gravity',
    'al': 'albumin',
    'su': 'sugar',
    'rbc': 'red blood cells',
    'pc': 'pus cell',
    'pcc': 'pus cell clumps',
    'ba': 'bacteria',
    'bgr': 'blood glucose random',
    'bu': 'blood urea',
    'sc': 'serum creatinine',
    'sod': 'sodium',
    'pot': 'potassium',
    'hemo': 'hemoglobin',
    'pcv': 'packed cell volume',
    'wc': 'white blood cell count',
    'rc': 'red blood cell count',
    'htn': 'hypertension',
    'dm': 'diabetes mellitus',
    'cad': 'coronary artery disease',
    'appet': 'appetite',
    'pe': 'pedal edema',
    'ane': 'anemia'
}

def rename_columns(col):
    # Split the column into the abbreviation and any suffix
    parts = col.split('_', 1)  # Split at the first underscore only
    prefix = parts[0]           # Get the abbreviation (prefix)
    suffix = parts[1] if len(parts) > 1 else ''  # Get the suffix if it exists

    # Get the full name from the mapping, and add the suffix back if it exists
    full_name = abbreviation_mapping.get(prefix, prefix)  # Default to the original if not found
    return f"{full_name}_{suffix}" if suffix else full_name

# Rename the DataFrame columns
gpt_df.columns = [rename_columns(col) for col in gpt_df.columns]

# Display the renamed DataFrame
display(gpt_df)

,age,blood pressure,blood glucose random,blood urea,serum creatinine,sodium,potassium,hemoglobin,packed cell volume,wbcc,rbcc,albumin,sugar,red blood cells_abnormal,red blood cells_normal,pus cell_abnormal,pus cell_normal,pus cell clumps_notpresent,pus cell clumps_present,bacteria_notpresent,bacteria_present,hypertension_no,hypertension_yes,diabetes mellitus_no,diabetes mellitus_yes,coronary artery disease_no,coronary artery disease_yes,appetite_good,appetite_poor,pedal edema_no,pedal edema_yes,anemia_no,anemia_yes,Target_ckd,Target_notckd
0,0.202703,0.75,0.158798,0.196078,0.160494,0.166667,0.206897,0.059406,0.000000,0.653226,0.257143,4.0,0.0,False,True,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False,False,True,True,False
1,0.905405,1.00,0.965665,0.522876,0.641975,0.666667,0.000000,0.148515,0.225806,0.217742,0.057143,3.0,2.0,True,False,True,False,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,True,False
2,0.743243,0.50,0.442060,0.901961,0.432099,0.500000,0.793103,0.000000,0.032258,0.395161,0.057143,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,False,True,False,True,False,True,True,False
3,0.729730,0.75,0.150215,0.281046,0.234568,0.533333,0.793103,0.336634,0.322581,0.500000,0.314286,2.0,0.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
4,0.540541,0.00,0.399142,0.535948,0.358025,0.700000,0.379310,0.207921,0.161290,0.830645,0.057143,1.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
5,0.675676,0.75,0.253219,0.633987,0.777778,0.366667,0.655172,0.138614,0.193548,0.169355,0.114286,2.0,0.0,True,False,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False
6,0.716216,0.50,1.000000,0.163399,0.111111,0.066667,0.206897,0.267327,0.387097,0.532258,0.371429,1.0,0.0,True,False,False,True,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,True,False
7,0.729730,0.00,0.935622,0.169935,0.160494,0.333333,0.034483,0.019802,0.064516,0.879032,0.000000,3.0,1.0,False,True,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,False,True,True,False
8,0.000000,0.00,0.103004,0.372549,0.074074,0.500000,0.689655,0.217822,0.225806,1.000000,0.514286,4.0,0.0,True,False,True,False,True,False,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False
9,0.878378,0.00,0.206009,0.751634,0.604938,0.533333,0.689655,0.366337,0.387097,0.879032,0.371429,4.0,0.0,False,True,False,True,True,False,True,False,False,True,False,True,True,False,False,True,False,True,True,False,True,False
10,0.851351,0.25,0.618026,0.562092,0.728395,0.000000,0.344828,0.168317,0.161290,0.580645,0.085714,4.0,3.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,False,True,False,True,True,False
11,0.878378,0.25,0.639485,0.470588,0.395062,0.433333,0.517241,0.267327,0.322581,0.104839,0.171429,3.0,0.0,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,True,False,True,False,True,False
12,0.783784,0.00,0.725322,0.313725,0.481481,0.566667,0.862069,0.178218,0.193548,0.258065,0.114286,4.0,1.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,False,True,True,False,True,False
13,0.662162,0.50,0.618026,0.411765,0.432099,0.566667,0.689655,0.316832,0.354839,0.250000,0.200000,3.0,1.0,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
14,0.770270,1.00,0.901288,0.163399,0.345679,0.766667,0.206897,0.524752,0.548387,0.443548,0.342857,2.0,2.0,False,True,False,True,True,False,False,True,False,True,True,False,False,True,True,False,True,False,True,False,True,False
15,0.905405,0.50,0.785408,0.862745,0.518519,0.600000,1.000000,0.277228,0.322581,0.233871,0.371429,2.0,0.0,True,False,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,True,False,True,False
16,0.675676,0.25,0.600858,0.104575,0.160494,0.533333,0.310345,0.831683,0.935484,0.661290,0.742857,4.0,1.0,True,False,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False
17,0.567568,0.50,0.270386,0.843137,1.000000,0.400000,0.896552,0.257426,0.419355,0.153226,0.285714,4.0,0.0,True,False,True,False,True,False,False,True,True,False,False,True,True,False,True,False,False,True,True,False,True,False
18,0.783784,1.00,0.399142,0.287582,0.839506,0.666667,0.586207,0.019802,0.096774,0.258065,0.114286,4.0,2.0,True,False,True,False,True,False,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False
19,0.851351,0.25,0.832618,0.503268,0.283951,0.333333,0.379310,0.475248,0.451613,0.427419,0.314286,3.0,4.0,False,True,True,False,True,False,True,False,False,True,False,True,False,True,True,False,False,True,True,False,True,False
20,0.567568,0.50,0.107296,1.000000,0.901235,0.533333,0.310345,0.207921,0.290323,0.209677,0.114286,4.0,0.0,False,True,True,False,True,False,True,False,False,True,True,False,True,False,True,False,True,False,False,True,True,False
21,0.756757,0.25,0.223176,0.209150,0.160494,0.533333,0.620690,0.485149,0.516129,0.290323,0.257143,3.0,0.0,False,True,True,False,True,False,True,False,False,True,False,True,True,False,True,False,True,False,True,False,True,False
22,0.324324,0.50,0.111588,0.098039,0.012346,0.800000,0.655172,0.603960,0.612903,0.379032,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
23,0.081081,0.50,0.128755,0.104575,0.024691,0.566667,0.517241,0.801980,0.838710,0.185484,0.685714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
24,0.756757,0.50,0.266094,0.156863,0.049383,0.900000,0.206897,1.000000,0.677419,0.032258,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
25,0.932432,0.25,0.158798,0.248366,0.049383,0.800000,0.206897,0.584158,0.741935,0.483871,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
26,0.513514,0.00,0.107296,0.235294,0.012346,0.600000,0.448276,0.722772,0.870968,0.274194,0.942857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
27,0.729730,0.50,0.047210,0.032680,0.012346,0.700000,0.241379,0.722772,0.741935,0.500000,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
28,0.837838,0.00,0.236052,0.202614,0.086420,0.633333,0.310345,0.960396,0.870968,0.193548,0.885714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
29,0.662162,0.50,0.257511,0.261438,0.098765,0.900000,0.724138,0.772277,0.580645,0.387097,0.857143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
30,0.229730,0.50,0.175966,0.156863,0.086420,0.833333,0.379310,0.653465,0.580645,0.233871,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
31,1.000000,0.50,0.210300,0.235294,0.037037,0.700000,0.689655,0.613861,0.838710,0.064516,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
32,0.256757,0.25,0.077253,0.209150,0.012346,0.533333,0.206897,0.554455,0.806452,0.217742,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
33,0.918919,0.00,0.077253,0.261438,0.024691,0.900000,0.275862,0.940594,0.967742,0.137097,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
34,0.567568,0.50,0.223176,0.150327,0.061728,0.866667,0.344828,0.613861,0.806452,0.419355,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
35,0.243243,0.25,0.300429,0.084967,0.024691,0.666667,0.620690,0.851485,0.806452,0.120968,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
36,0.189189,0.25,0.227468,0.222222,0.074074,0.500000,0.310345,0.683168,0.677419,0.096774,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
37,0.675676,0.00,0.266094,0.052288,0.086420,0.900000,0.620690,0.594059,0.709677,0.258065,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
38,0.405405,0.50,0.064378,0.039216,0.086420,0.733333,0.413793,0.782178,0.677419,0.120968,0.942857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
39,0.716216,0.00,0.184549,0.084967,0.086420,0.633333,0.206897,0.752475,1.000000,0.177419,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
40,0.364865,0.50,0.128755,0.176471,0.098765,0.733333,0.379310,0.910891,0.935484,0.193548,0.857143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
41,0.864865,0.50,0.017167,0.202614,0.012346,0.766667,0.551724,0.732673,0.806452,0.435484,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
42,0.608108,0.50,0.103004,0.032680,0.098765,0.800000,0.275862,0.772277,0.741935,0.419355,0.971429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
43,0.121622,0.50,0.098712,0.045752,0.061728,0.533333,0.344828,0.891089,0.870968,0.153226,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
44,0.229730,0.50,0.000000,0.169935,0.074074,1.000000,0.586207,0.920792,0.935484,0.443548,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
45,0.459459,0.50,0.300429,0.000000,0.098765,0.500000,0.724138,0.722772,0.806452,0.491935,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
46,0.878378,0.25,0.047210,0.052288,0.049383,0.833333,0.724138,0.693069,0.677419,0.443548,0.857143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
47,0.810811,0.25,0.158798,0.039216,0.086420,0.666667,0.241379,0.584158,0.612903,0.540323,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
48,0.662162,0.50,0.206009,0.052288,0.061728,0.500000,0.241379,0.772277,0.645161,0.233871,0.685714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
49,0.608108,0.00,0.124464,0.183007,0.049383,0.500000,0.275862,0.524752,0.838710,0.322581,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
50,0.662162,0.50,0.270386,0.045752,0.098765,0.500000,0.655172,0.544554,0.580645,0.201613,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
51,0.500000,0.50,0.257511,0.130719,0.086420,0.766667,0.724138,0.811881,0.709677,0.282258,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
52,0.729730,0.00,0.274678,0.228758,0.012346,0.633333,0.655172,0.643564,0.806452,0.516129,0.742857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
53,0.527027,0.50,0.201717,0.235294,0.098765,0.566667,0.724138,0.841584,0.709677,0.346774,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
54,0.256757,0.50,0.218884,0.058824,0.098765,0.733333,0.689655,0.722772,0.806452,0.209677,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
55,0.364865,0.50,0.248927,0.183007,0.024691,0.500000,0.344828,0.534653,0.709677,0.153226,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
56,0.851351,0.25,0.055794,0.209150,0.098765,0.633333,0.275862,0.841584,0.870968,0.403226,0.685714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
57,0.702703,0.25,0.077253,0.039216,0.086420,0.900000,0.206897,0.861386,0.967742,0.387097,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
58,0.486486,0.25,0.098712,0.143791,0.061728,0.766667,0.620690,0.881188,0.645161,0.225806,0.657143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
59,0.716216,0.25,0.257511,0.189542,0.037037,0.900000,0.620690,0.574257,0.741935,0.193548,0.428571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
60,0.594595,0.50,0.287554,0.235294,0.049383,0.633333,0.724138,0.633663,0.709677,0.419355,0.457143,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
61,0.554054,0.50,0.231760,0.222222,0.074074,0.666667,0.689655,0.712871,0.580645,0.217742,0.771429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
62,0.513514,0.25,0.094421,0.196078,0.061728,0.700000,0.689655,0.623762,0.935484,0.258065,0.914286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
63,0.324324,0.00,0.214592,0.137255,0.049383,1.000000,0.586207,0.564356,0.677419,0.516129,0.800000,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
64,0.310811,0.50,0.055794,0.254902,0.061728,0.633333,0.137931,0.970297,0.548387,0.451613,0.485714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
65,0.594595,0.50,0.115880,0.196078,0.024691,1.000000,0.551724,0.643564,0.806452,0.500000,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
66,0.432432,0.50,0.124464,0.058824,0.012346,0.900000,0.206897,0.584158,0.677419,0.241935,0.971429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
67,0.689189,0.00,0.150215,0.254902,0.098765,1.000000,0.620690,0.792079,0.677419,0.491935,0.914286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
68,0.540541,0.00,0.227468,0.235294,0.074074,0.500000,0.724138,0.792079,0.870968,0.161290,0.514286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
69,0.472973,0.50,0.223176,0.098039,0.049383,0.600000,0.724138,0.930693,0.580645,0.387097,0.628571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
70,0.770270,0.25,0.184549,0.098039,0.024691,0.866667,0.689655,0.871287,0.935484,0.298387,0.600000,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
71,0.148649,0.00,0.188841,0.261438,0.074074,0.500000,0.689655,0.643564,0.903226,0.233871,0.828571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
72,0.324324,0.50,0.081545,0.209150,0.012346,0.633333,0.724138,0.891089,0.935484,0.475806,0.571429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
73,0.500000,0.50,0.047210,0.235294,0.024691,0.500000,0.689655,0.613861,0.806452,0.209677,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
74,0.662162,0.50,0.300429,0.254902,0.012346,1.000000,0.689655,0.792079,0.774194,0.193548,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
75,0.445946,0.25,0.261803,0.235294,0.024691,0.833333,0.724138,0.782178,0.580645,0.411290,0.485714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
76,0.675676,0.50,0.296137,0.032680,0.098765,0.500000,0.724138,0.702970,0.612903,0.104839,0.714286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
77,0.324324,0.50,0.051502,0.209150,0.037037,0.866667,0.724138,0.712871,0.709677,0.411290,0.828571,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
78,0.756757,0.50,0.034335,0.228758,0.024691,0.600000,0.206897,0.831683,0.870968,0.088710,0.771429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
79,0.702703,0.25,0.137339,0.248366,0.098765,0.633333,0.482759,0.722772,0.548387,0.306452,0.542857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
80,0.391892,0.00,0.150215,0.189542,0.012346,0.500000,0.344828,0.693069,0.645161,0.120968,0.914286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
81,0.229730,0.50,0.124464,0.235294,0.098765,0.733333,0.379310,0.990099,0.741935,0.000000,0.714286,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
82,0.378378,0.50,0.218884,0.111111,0.098765,0.800000,0.344828,0.584158,0.935484,0.395161,0.942857,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
83,0.986486,0.50,0.175966,0.222222,0.098765,0.866667,0.241379,0.851485,0.548387,0.298387,0.971429,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True
84,0.905405,0.00,0.244635,0.248366,0.012346,1.000000,0.206897,0.732673,0.935484,0.540323,0.485714,0.0,0.0,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,False,True

## Part 4.3 Augmenting our skills with prompting

In addition, we can also use 383GPT to convert our data manipulation operations between different data manipulation languages and libraries. For example let's prompt 383GPT to convert the following SQL query to a pandas query.

**SQL Query**
```sql
SELECT Target, COUNT(*) AS count
FROM your_table_name
GROUP BY Target;
```

Prompt 383GPT to convert this to a pandas query. Run this query below, then describe what it does. (If you're not familiar with SQL that is okay you need to only comment on the final resulting output.)

In [16]:
# Converted SQL to Pandas code
result = gpt_df.groupby('Target_ckd').size().reset_index(name='count')
display(result)

   Target_ckd  count
0       False    111
1        True     22

Answer: The code above groups the dataframe by the Target_ckd column, counts the number of occurrences of each value (in this case, only True and False), then resets the index of the resulting dataframe and gives a name to the count column.