In [1]:
# Imports section
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

## Part 1. Loading the dataset

In [ ]:
# Using pandas load the dataset
dataset = pd.read_csv("science_data_large.csv")
# Output the first 15 rows of the data
dataset.head(15)

    Temperature °C  Mols KCL     Size nm^3
0              469       647  6.244743e+05
1              403       694  5.779610e+05
2              302       975  6.196847e+05
3              779       916  1.460449e+06
4              901        18  4.325726e+04
5              545       637  7.124634e+05
6              660       519  7.006960e+05
7              143       869  2.718260e+05
8               89       461  8.919803e+04
9              294       776  4.770210e+05
10             991       117  2.441771e+05
11             307       781  5.006455e+05
12             206        70  3.145200e+04
13             437       599  5.390215e+05
14             566        75  9.185271e+04

In [3]:
# Display a summary of the table information (number of datapoints, etc.)
dataset.describe(include='all')

       Temperature °C     Mols KCL     Size nm^3
count     1000.000000  1000.000000  1.000000e+03
mean       500.500000   471.530000  5.086111e+05
std        288.819436   288.482872  4.474838e+05
min          1.000000     1.000000  1.611429e+01
25%        250.750000   226.750000  1.298267e+05
50%        500.500000   459.500000  3.827182e+05
75%        750.250000   710.250000  7.603211e+05
max       1000.000000  1000.000000  1.972127e+06

## Part 2. Splitting the dataset

In [23]:
# Take the pandas dataset and split it into our features (X) and label (y)
X = dataset.drop('Size nm^3', axis=1)
y = dataset['Size nm^3']
# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=5)

## Part 3. Perform a Linear Regression

In [24]:
# Use sklearn to train a model on the training set
model = LinearRegression().fit(X_train, y_train)
# Create a sample datapoint and predict the output of that sample with the trained model
prediction = model.predict(np.array([[827,341]]))
print(prediction)

[655843.40483582]

/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [25]:
# Report on the score for that model, in your own words (markdown, not code) explain what the score means
model.score(X_test, y_test)

0.8905056535948739

This score represents how well the linear model fits the test dataset. For example, this score of 0.89, means that the model will accurately predict the label of the test data 89% of the time. The closer this number is to 1, the better the linear regression fit, basically implying that the model will always predict the correct answer. Alas, in this context the linear model correctly labels the test data 89% of the time. Also, the score represents the $R^2$ value.

In [26]:
# Extract the coefficents and intercept from the model and write an equation for your h(x) using LaTeX
print(model.coef_, model.intercept_)

[ 869.62291329 1029.26363694] -414313.64464917977

My equation: $y = 869.62x_1+1029.26x_2-414313.64$

## Part 4. Use Cross Validation

In [29]:
# Use the cross_val_score function to repeat your experiment across many shuffles of the data
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(model, X, y, cv=kf)
print(scores, "\n")
print(scores.mean(), "\n")
print(scores.std())

[0.86151889 0.82742341 0.87195173 0.88166206 0.85609101]

0.8597294202684646

0.01838773713930639

Report on their finding and their significance: 
Each score represents the accuracy of the model on producing accurate labels based on 5 different partitions of data. This cross validation displays the model's capacity to accurately predict labels for different partitions of the datset. Thus each element in the printed array scores, represents a score for a model on accurately representing that dataset. The cross_val_score method allows for a more dynamic interpreation of the models strength based on different partitions of training and test data. The average score is ~85% accuracy wth a standard deviation of about 1.8%. The more consistant the model's scores are, the smaller the standard deviation, the better the model is. Therefore it is a useful metric to look at the standard deviation of the scores so see how universally accurate the model is.

## Part 5. Using Polynomial Regression

In [43]:
# Using the PolynomialFeatures library perform another regression on an augmented dataset of degree 2
x_poly = PolynomialFeatures(degree=2).fit_transform(X)
polyModel = LinearRegression().fit(x_poly, y)
# Report on the metrics and output the resultant equation as you did in Part 3.
polyModel.score(PolynomialFeatures(degree=2).fit_transform(X_test), y_test)

1.0

An $R^2$ value of 1, implies that the polynomial regression perfectly fits the data. It will accurately label the test data 100% of the time.

The resultant equation is

$y = 12x - x^2 - x^3 + 2x^4 + 0.0286 x^5$

In [45]:
print(polyModel.coef_, polyModel.intercept_ )

[ 0.00000000e+00  1.20000000e+01 -1.23110504e-07 -1.05648823e-11
  2.00000000e+00  2.85714287e-02] 1.657189568504691e-05