In [180]:
# Imports section
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import PolynomialFeatures

## Part 1. Loading the dataset

In [181]:
# Using pandas load the dataset (load remotely, not locally)
df = pd.read_csv("science_data_large.csv")
# Output the first 15 rows of the data
display(df.head(15))
# Display a summary of the table information (number of datapoints, etc.)
display(df.describe())

    Temperature °C  Mols KCL     Size nm^3
0              469       647  6.244743e+05
1              403       694  5.779610e+05
2              302       975  6.196847e+05
3              779       916  1.460449e+06
4              901        18  4.325726e+04
5              545       637  7.124634e+05
6              660       519  7.006960e+05
7              143       869  2.718260e+05
8               89       461  8.919803e+04
9              294       776  4.770210e+05
10             991       117  2.441771e+05
11             307       781  5.006455e+05
12             206        70  3.145200e+04
13             437       599  5.390215e+05
14             566        75  9.185271e+04

       Temperature °C     Mols KCL     Size nm^3
count     1000.000000  1000.000000  1.000000e+03
mean       500.500000   471.530000  5.086111e+05
std        288.819436   288.482872  4.474838e+05
min          1.000000     1.000000  1.611429e+01
25%        250.750000   226.750000  1.298267e+05
50%        500.500000   459.500000  3.827182e+05
75%        750.250000   710.250000  7.603211e+05
max       1000.000000  1000.000000  1.972127e+06

## Part 2. Splitting the dataset

In [182]:
# Take the pandas dataset and split it into our features (X) and label (y)
X = df.drop('Size nm^3', axis=1)
y = df['Size nm^3']
# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.9, test_size=0.1, random_state=42)
display(X_train)
display(y_train)

     Temperature °C  Mols KCL
716              95       499
351             243       384
936              47       211
256             495       497
635              82       421
..              ...       ...
106             439        40
270             665       245
860             471       620
435             829       259
102             636       388

[900 rows x 2 columns]

716    103064.31430
351    193753.02860
936     21670.02857
256    505027.40000
635     75092.02857
           ...
106     40433.71429
270    335545.00000
860    600674.85710
435    441286.60000
102    505469.25710
Name: Size nm^3, Length: 900, dtype: float64

## Part 3. Perform a Linear Regression

In [183]:
# Use sklearn to train a model on the training set
model = LinearRegression().fit(X_train, y_train)
# Create a sample datapoint and predict the output of that sample with the trained model
y_pred = model.predict([[500,471]]) # Used the mean of Temperature and Mols
# Report on the score for that model, in your own words (markdown, not code) explain what the score means
train_score = model.score(X_train, y_train)
print(train_score)
# Extract the coefficents and intercept from the model and write an equation for your h(x) using LaTeX
print(model.coef_)
print(model.intercept_)

0.8610082946223787
[ 866.14641337 1032.69506649]
-409391.47958340775

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

Sample equation: $E = mc^2$

Answer:

The score of a model indicates how accurate the model is at predicting outcomes.

h(x) = -416367.37884415616 + (871.41449757 * x_1) + (1038.23844296 * x_2)

## Part 4. Use Cross Validation

In [184]:
# Use the cross_val_score function to repeat your experiment across many shuffles of the data
cross_val = cross_val_score(model, X, y, cv=6)
print(cross_val)
# Report on their finding and their significance

[0.84218925 0.86742607 0.87093863 0.8604674  0.84826261 0.86031557]

By using cross validation on the trained model, we are reducing overfitting by including more of the original dataset, which weren't included in the trained data.

## Part 5. Using Polynomial Regression

In [185]:
# Using the PolynomialFeatures library perform another regression on an augmented dataset of degree 2
X_poly = PolynomialFeatures(2)
X_poly.fit_transform(X)
# Report on the metrics and output the resultant equation as you did in Part 3.
poly_model = LinearRegression().fit(X, y)
print(poly_model.coef_)
print(poly_model.intercept_)

[ 875.90992708 1031.59502452]
-416209.81738620513

h(x) = -416209.81738620513 + (875.90992708 * x_1) + (1031.59502452 * x_2)